### ISSUE TITLE
Combine topics and private topics?

### ISSUE THREAD

**Issue by kylefiedler** [thredded/thredded#101]
The forms and display from a HTML and CSS standpoint are identical. It might be good to remove some of the duplication that is happening in some of the views.

**Comment by jayroh** [comment]
Agreed, Kyle. There can be some consolidation here.

**Comment by glebm** [comment]
JS consolidated in #140

**Comment by glebm** [comment]
This is now done, basically.

**Comment by jayroh** [comment]
👍🏼
