### ISSUE TITLE
Refactor controllers to expose only a single view-model to the view

### ISSUE THREAD

**Issue by jayroh** [thredded/thredded#110]
As I'm looking through the contents of all of the controllers, there's a wealth of arbitrary instance variables -- some consistently named, some not -- and plenty of mixed convention.

Rolling everything up into common conventions like

1. A resources' index action has one object exposed - the plural of that resource name. Messageboard => `messageboards`. It responds to `.each` and loops through a collection of decorated messageboard objects
2. A resources' new, show, edit -- anything that works with a single object -- exposes the singular of that resource name. Messageboard => `messageboard`. It returns a decorated messageboard.

etc. etc.

This common treatment reduces guessing, increases readability, increases testability, and lends to better documentation.

**Comment by TheDudeWithTheThing** [comment]
any objections to me jumping versions being worked on and grabbing this?  Straight forward enough that I think I could plow through it

**Comment by glebm** [comment]
I'm actually really confused by decorators. With the exception of the read state, they seem to handle pure view/form concerns (gut feel: decorators are evil). View models are much better. But exposing several variables is no different from exposing one variable with several methods.

**Comment by jayroh** [comment]
That's an interesting thought. Considering how this has evolved over time and how much love the view layer has gotten as of late, it might make sense to evolve some of the decorators into view models. For example - the `post_decorator` might be qualified as a "decorator" but it serves the same or similar purpose of a view model. It's all in the naming at that point.

I'd love to see some discussion on what we would all consider being a "decorator" versus what would be a "view model".

To be honest I've seen the names be interchangeable ... maybe with "decorator" having a slightly stronger view-layer bent.

@TheDudeWithTheThing - to answer your question, though, once we have consensus on the naming and intent, I have no problem seeing you pick this up. Why tf not.

**Comment by TheDudeWithTheThing** [comment]
I was about to say, how is a view model different from a decorator (from a what it provides perspective)?  I guess it wouldn't have any of the underlying AR functionality available and only have those methods that is needed for viewing?  Would that create a lot of duplicate methods?

so `class Topic < ActiveRecord::Base` has `title` available

we'd then have `class TopicView` and that would also have a `title` method that it extracted the value from the `class Topic < ActiveRecord::Base` version?

I'm ok either way, looking forward to an interesting discussion.  The view layer of rails is very foreign to me as 90% of my experience with rails is as an API only.

**Comment by jayroh** [comment]
This whole exercise, by the way, would be a great opportunity to simultaneously document all of these public objects per #111

**Comment by glebm** [comment]
> I was about to say, how is a view model different from a decorator (from a what it provides perspective)?

Exactly, decorators delegate all the methods of the underlying instance, so they are on the opposite spectrum of view models.

There are additional restrictions that should be imposed on view models:

1. Methods accept no arguments.
2. Methods return simple serializable types: String, Boolean, etc.

With this restrictions imposed, a view model can be trivially converted to JSON if someone wants to write an Android client or SPA web frontend.

**Comment by TheDudeWithTheThing** [comment]
I'll get a PR going and see how we feel

**Comment by glebm** [comment]
:+1:

**Comment by glebm** [comment]
@TheDudeWithTheThing I actually have the beginnings of a conversion locally, just pushed it so you can have a look https://github.com/thredded/thredded/commit/d078fb78abd5fe5e579a9f2d3270d883ce77a9a3

**Comment by TheDudeWithTheThing** [comment]
all you, my time to work on this is very limited so don't feel bad about grabbing anything I try to claim

**Comment by glebm** [comment]
Refactored topics#show to use a view model in https://github.com/thredded/thredded/commit/a0459c8ec8a428b02ed1a47afb1369c7f9953cf3, because I needed a single object for the collection to get [multi-get caching](http://edgeguides.rubyonrails.org/caching_with_rails.html#collection-caching) working correctly.

**Comment by glebm** [comment]
Done! We now only expose a single documented view model to the view (well, sometimes it's two models, where one is for the new post/topic form but that's OK).
