### ISSUE TITLE
add support for managing permissions in the container app

### ISSUE THREAD

**Issue by saturnflyer** [thredded/thredded#126]
We've yet to implement permissions to control the thredded forum in https://github.com/saturnflyer/purple_door/ but my expectation is that I'll need to have a lot of knowledge of the internal implementation of thredded to get my own prefrences form to hook things up.

Although I haven't tried yet, I'd love to be able to have some kind of convention to follow in my own preferences form. For example if i pass in the values `forum_access: true` (or something) that my controller or model could see that value and have a standard way to add someone to thredded.

Here's an idea of something I'd want: `Thredded.add_user(user) if params[:forum_access]`
I don't know exactly how that fits in. Perhaps `add_admin` or something might work too.

I'm not sure if the code is the best example, but the gist of what I'd want is: I've added thredded and already have a user edit screen, now what? How do I provide access to create message boards to my users?

**Comment by jayroh** [comment]
@saturnflyer I see what you're saying with regards to providing an intuitive API for doing this. Question for you on a related note - would it be easier if a roles resource was exposed allowing you to set that admin, or moderator, bit?

Right now there's nothing available in terms of a UI to do that and I'm thinking it's definitely necessary

**Comment by glebm** [comment]
Related: Instead of storing a roles table, it would be nice to have a more flexible way of doing this. E.g. let the user specify the scopes and the methods to check for permission. I would imagine most forums do not need per-user permissions.

**Comment by jayroh** [comment]
I really like that idea. I went way too far with the authorization code in here and tried to anticipate the different combinations one might want to restrict or allow access.

Follow-up question to this would be, of course, how would that interface look? Two or three scopes for a messageboard resource - participate, moderate, admin? That could cover most of the bases for most of the use cases. Could open up a project-defined proc per each of those three that take a user and messageboard and return a bool?

**Comment by glebm** [comment]
We could require 3 methods and a scope on the user:

```ruby
class User
  # Users that can read and post in the given messageboards
  scope :thredded_messageboards, -> (messageboards) { 
    # for example
    all
  }

  # @return [Array<Thredded::Messageboard>, ActiveRecord::Relation]
  #    messageboards that the user can read and post in
  def thredded_messageboards
    # for example
    Thredded::Messageboard.all
  end

  # @return [Array<Thredded::Messageboard>, ActiveRecord::Relation]
  def thredded_moderates_messageboards
    # for example 
    moderator? ? Thredded::Messageboard.all : Thredded::Messageboard.none
  end

  # @return [Array<Thredded::Messageboard>, ActiveRecord::Relation]
  def thredded_admin_of_messageboards
    # for example
    admin? ? Thredded::Messageboard.all : Thredded::Messageboard.none
  end
end
```

Then, on thredded side, the checks are:

* Accessible messageboards:
  
  ```ruby
  Thredded.user_class.send(:thredded_messageboards)
  ```

* Permissions check for a `messageboard`:

  ```ruby
  Thredded.user_class.send(:thredded_messageboards).includes?(messageboard)
  ```

* Users that can be contacted via private topics by a given `user`:

  ```ruby
  Thredded.user_class.thredded_messageboards(user.thredded_messageboards.to_a)
  ```

**Comment by jayroh** [comment]
So from a high level it would be an interface that allows the parent app to define the authorization. Essentially asking devs to implement the following checks:

* What messageboards can this user view?
* What messageboards can this user moderate?
* What messagbeoards can this user administrate?

Implementation aside I think this would be *great* to remove the responsibility from the gem. It'd remove complexity and a whole lot of code!

**Comment by glebm** [comment]
Done
