### ISSUE TITLE
Should private topics be tied to Messageboards?

### ISSUE THREAD

**Issue by glebm** [thredded/thredded#138]
Seems like the private topics should not need a Messageboard.

**Comment by jayroh** [comment]
Great question. I'll answer this with the context of someone involved in a single community (read: a single messageboard within a domain/site) amongst several other isolated messageboards. On thredded.com there was a period where there were 5 pretty active boards, with 400-500 users signed up, and about 150 active users. If private topics were open across all users, across the entire site, there would/could have been some abuse (I know, I know - abuse?) from one side to another. It's weird.

You could simulate behavior like you're talking about if you have a single messageboard on a domain, and split participation in verticals among categories.

**Comment by glebm** [comment]
Ah, I see. How about this: a user can add participants only among the participants of the messageboards the user has access to.

E.g., assuming the messageboard has a `writeable_by_user(scope)` and a `users` relationship:

```ruby
users = Mesageboard.writeable_by_user(current_user).flat_map(&:users).uniq
```

**Comment by jayroh** [comment]
Interesting thought! So this would, in effect, bubble everything up to the same level as the messageboards themselves. Effectively pulling it out of the context of being *within* a messageboard.

Hmmm. I could probably get behind that, actually

**Comment by glebm** [comment]
Done
