### ISSUE TITLE
Not installable when using SQLite3

### ISSUE THREAD

**Issue by Quintasan** [thredded/thredded#142]
Hi,

When trying to install thredded in my Rails 4.2.3 application I get the following error:
`/home/vagrant/.rvm/gems/ruby-2.1.5/bundler/gems/thredded-7e4699fecddd/lib/thredded/case_insensitive_string_finder.rb:25:in 'use_adapter!': Please define CaseInsensitiveStringFinder for sqlite3 (RuntimeError)`

If this is intended then please mention it in the documentation.

**Comment by glebm** [comment]
Hi @Quintasan, this gem currently only supports MySQL 5.6+ and Postgres, and this should definitely be mentioned in the docs.

The gem requires that the database provides full text search and case-insensitive exact match. It seems that the recent versions of SQLite3 also [provide](https://www.sqlite.org/fts3.html#section_3) Full Text Search. Would you like to improve thredded by implementing sqlite3 support?

**Comment by glebm** [comment]
Resolved by #167
