### ISSUE TITLE
Thredded.theme setting in initializer.rb not working for me or I'm doing something wrong.

### ISSUE THREAD

**Issue by blimey85** [thredded/thredded#157]
When trying to enable the theme initializer so I can customize the theme I get the following error:

`/Users/gary/Projects/thredded/config/initializers/thredded.rb:90:in `<top (required)>': undefined method `theme=' for Thredded:Module (NoMethodError)`

I might just be doing something wrong but just by uncommenting `Thredded.theme = :default` I'm getting this error. By default it's pulling theme files from within the gem, and obviously I don't want to make changes to those files, although I did change one template due to errors with devise paths. But I figured once I get it setup using a local copy of the template that wouldn't be a problem.

**Comment by glebm** [comment]
The theme documentation is a bit out of date. If you want to adjust the views, simply place your versions in `app/views/thredded/`.

**Comment by jayroh** [comment]
Yeah, Gleb is right. There's some documentation that needs updating in
there. Sorry about that Gary!

**Comment by blimey85** [comment]
That did the trick. One related question... I copied the thredded folder from `vendor/views` and that worked fine. It's automagically pulling from there now. However, there is also a related file in the layouts folder, and then in `vendor/assets/' I see a number of thredded folders. When copying the theme on the command line, should it not be placing the files in the vendor folder? Do I need to keep a copy in the vendor folder? And should I copy these other files into my app folder structure or are those not ok to modify? Thank you!!

**Comment by glebm** [comment]
Sorry, the current generator puts stuff in the vendor folder but actually nothing should be in the vendor folder.

1. Remove the vendor folder.
2. Copy the views you want to modify to app/.
3. If you don't modify the view, don't copy it. It will be pulled from the gem, and this has the advantage of easier updates.
