### ISSUE TITLE
Squash database migrations into a single migration

### ISSUE THREAD

**Issue by jayroh** [thredded/thredded#167]
As mentioned in issue #141. Squashing migrations would certainly give us a smaller, cleaner start on projects. @glebm could you talk to me about some of the other benefits to doing this? I could go either way but would love to know your thoughts.

**Comment by glebm** [comment]
Migrations are copied into the parent project. This is to avoid polluting the parent project with several dozen files we have currently.

When we do this, the squashed migration can have the same number as the last unsquashed migration, so there are no issues for the few existing installations.

Going forward, I like the ComfortableMexicanSofa approach:

1. One migration file for new installations:
https://github.com/comfy/comfortable-mexican-sofa/tree/master/db/upgrade_migrations

2. "Upgrade" migrations for tagged releases:
https://github.com/comfy/comfortable-mexican-sofa/tree/master/db/upgrade_migrations

3. Concise instructions:
https://github.com/comfy/comfortable-mexican-sofa/wiki/Upgrading-ComfortableMexicanSofa

**Comment by jayroh** [comment]
This is EXACTLY what I was hoping you would respond with! Thank you @glebm!

**Comment by glebm** [comment]
Depends on #182 for database-agnostic FTS/CI index / CI column creation

**Comment by jayroh** [comment]
This has been merged in and pushed up with version 0.2.1

@glebm you're the man
