### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by glebm** [thredded/thredded#179]
The README needs updating almost everywhere.

**Comment by jayroh** [comment]
Great start with thing done in #181 

One thing I'm noticing that would help in the readme are some details on implementing visibility of messageboards and topics using the new permission API

**Comment by glebm** [comment]
Well, the messageboards are visibile only if the user has read permissions. Topics have no separate per-topic permissions, they just use the messageboard permissions (so a user can either see all the topics in a messageboard, or none of them).
