### ISSUE TITLE
User timezone default

### ISSUE THREAD

**Issue by glebm** [thredded/thredded#180]
Currently, there is an arbitrary default for the user timezone column. Instead, the column should default to `null` and Thredded should use the browser timezone when the column is `null`.

**Comment by TheDudeWithTheThing** [comment]
Are you saying there'd be a `nil` timezone check with each request from a user?

**Comment by glebm** [comment]
I've looked at the code, and we already do it correctly, that is:

All times are stored in the same timezone (UTC if the parent app is sensible), and the client-side JS bit transforms it to the browser timezone.

The `time_zone` column appears to be unused. We should just remove it.

**Comment by jayroh** [comment]
> ... in the same timezone (UTC if the parent app is sensible)

Who are these monsters not storing as UTC?

**Comment by jayroh** [comment]
If this timezone isn't being used for much of anything, then yeah - we should lop it off.

**Comment by glebm** [comment]
> Who are these monsters not storing as UTC?

I know of a certain large company that stores all of the timestamps in Mountain View timezone :sob:

**Comment by jayroh** [comment]
LOL
