### ISSUE TITLE
Images and videos should have size constraints to fit into the post DIVs

### ISSUE THREAD

**Issue by jayroh** [thredded/thredded#187]
When testing out master against live data there are many images, and some videos that will blow out the post divs. The images can be fixed relatively easily - with some css for max-width - but videos will need something like [fitvids.js](http://fitvidsjs.com).

**Comment by glebm** [comment]
How are there any videos at all? The sanitization filter doesn't allow them: https://github.com/thredded/thredded/blob/master/app/models/concerns/thredded/post_common.rb#L55

**Comment by glebm** [comment]
If we only allow the `video` HTML5 tag, it can also be styled with pure CSS!

**Comment by jayroh** [comment]
I guess that was something I set up on thredded.com!

Stuff like YouTube and Vimeo - what do you think about auto-embedding those?

This might then reach into the issue detailing the switch from bbcode OR
markdown to just markdown and *some* bbcode.

**Comment by jayroh** [comment]
Got it - that's issue #68

**Comment by jayroh** [comment]
re: vimeo and youtube - 

* https://github.com/dlackty/html-pipeline-vimeo Boom! :boom: 
* https://github.com/st0012/html-pipeline-youtube Boom! :boom:

**Comment by jayroh** [comment]
Image issue fixed with #188
