### ISSUE TITLE
Provide an example of custom handling of Thredded errors

### ISSUE THREAD

**Issue by glebm** [thredded/thredded#212]
Handle LoginRequired in the demo app by rendering the log in form

**Comment by jayroh** [comment]
Was this handled with the following, @glebm?

* 386c6d9 - Dummy app redirect back on login if back not login (4 hours ago) <Gleb Mazovetskiy>
* 711a663 - Dummy app: login form on Errors::LoginRequired (4 hours ago) <Gleb Mazovetskiy>

**Comment by glebm** [comment]
Yeah, just need to add this to the initializer, will do this next.
