### ISSUE TITLE
Change copy from "Private Topics" to "Messages"?

### ISSUE THREAD

**Issue by glebm** [thredded/thredded#213]
Private topics are basically messages, and everyone is familiar with how messages work, while I've never seen "Private Topics" before. Should we change the copy?
@jayroh

**Comment by jayroh** [comment]
Naming is hard.

I think this is a perfect opportunity to throw this label title in an i18n translation and let anyone change it to what they want.

* Messages
* Private Topics
* Private Messages
* Direct Messages
* Group Messages

It could be so many things!

**Comment by glebm** [comment]
The nav/label is already in i18n (but not the mailers, yet). I'm talking about the default here. "Private topics" does not seem like a good default, it's not well-recognized.

**Comment by jayroh** [comment]
I can see the argument against "private topics", but I would say that just "messages" is a bit on the vague side. I think "Private Messages" would be a safe and happy compromise.  Looks like that's what discourse uses:

![](https://www.evernote.com/l/AUqFdRkOIORNJYdvEkLX6EzrHZmJ1W-9u_MB/image.png)

I don't *want* to mimic discourse but if they've rolled that functionality out with that then it must be intuitive enough.

**Comment by glebm** [comment]
:+1: Private messages are intuitive enough
