### ISSUE TITLE
Error when creating new private message

### ISSUE THREAD

**Issue by TheDudeWithTheThing** [thredded/thredded#218]
Not sure if it's just how the dummy app is initialized but when creating a new private topic I get the following

undefined method `notify_on_message?' for #<Thredded::UserPreference:0x007fb1a0726740>

**Comment by glebm** [comment]
I think you've created the database before #210 went in, and didn't run the upgrade migrations after that.

**Comment by TheDudeWithTheThing** [comment]
oh maybe, any harm in leaving my changes?

**Comment by glebm** [comment]
If there are any errors for users with no preference records, we might not notice them because all seeded users have preference records. Though this is covered by tests currently.
