### ISSUE TITLE
Markdown images no longer work

### ISSUE THREAD

**Issue by glebm** [thredded/thredded#230]
```
![img](https://cloud.githubusercontent.com/assets/216339/14379806/da716a1e-fd73-11e5-90f1-6dbdb708d3d5.png)
```

Expected:

> an image here

Actual:

> !(https://cloud.githubusercontent.com/assets/216339/14379806/da716a1e-fd73-11e5-90f1-6dbdb708d3d5.png)

**Comment by jayroh** [comment]
Mf'er
