### ISSUE TITLE
Preview post contents

### ISSUE THREAD

**Issue by jayroh** [thredded/thredded#237]
Per github, waffle.io, discourse, et al ... would be nice to be able to preview the output of a post similarly.

Have something like `PreviewController#show` return some json with the generated html, maybe?

**Comment by timdiggins** [comment]
@jayroh @glebm FYI I'm doing this in my main_app using https://github.com/markdown-it/markdown-it and about 5 lines of code in the after_content for post

It's not perfect (doesn't highlight mentioned users) but it's pretty good. And seems a bit crazy to make the server to do this for us.

**Comment by glebm** [comment]
@timdiggins The server would be the more correct way to do it because of the user highlight as you mention, but also HTML stripping, emoji replacement, etc (and any custom plugins the user may have installed). Additionally, the architecture at the moment allows for any html pipeline (i.e. not necessarily markdown).

It would be super-simple to implement too, the view would be just:

```erb
<%= Thredded::ContentFormatter.new(self).format_content(@content) %>
```

and the controller:

```ruby
def show
  @content = params[:content]
  render layout: false
end
```

**Comment by kivikakk** [comment]
As an aside, this is indeed why we (GitHub) render server-side; user/commit/issue highlights are the main thing, as well as task lists, math rendering, various emoji input styles, etc. It'd be very difficult to keep a separate client-side implementation in sync, so :+1: for that method.

**Comment by glebm** [comment]
I've started on the implementation. Promoting from plugin to core, as this functionality applies to any markup engine, even a WYSIWYG one. Though perhaps we should also provide an easy way to disable the UI for this.

**Comment by timdiggins** [comment]
Fantastic @glebm. Agree it should be core -- is there a way to override with something like a view hook? Feel like we need to control growth of  configuration options if possible.

**Comment by timdiggins** [comment]
Fantastic @glebm. Agree it should be core -- is there a way to override with something like a view hook? Feel like we need to control growth of  configuration options if possible.

**Comment by glebm** [comment]
@timdiggins Good point, in the PR I've sent there is no configuration option, just a view hook.

**Comment by jayroh** [comment]
I'm excited to check this out!
