### ISSUE TITLE
A standalone forum app generator (thredded_create_app)

### ISSUE THREAD

**Issue by glebm** [thredded/thredded#250]
A repo that lets the user clone it, fill-in a few settings, and deploy standalone forums, e.g. to Heroku.

Basically packages thredded, devise, railsconfig, comfortable_mexican_sofa, etc together, so that Thredded can be deployed by hobbyist with no knowledge of Rails ecosystem.

Discourse would fill this niche already but it can be very complex to set it up.

**Comment by xuliaP** [comment]
i think..at beginning you'll must to edit readme
 rails new q
 add gem devise 
 and add thredded
After signup -errors...

**Comment by glebm** [comment]
Will be working on a generator here: https://github.com/thredded/thredded_create_app

**Comment by glebm** [comment]
Got everything working in the app generator, except:

* simple_form, blocked by a new release of devise-i18n with https://github.com/tigrish/devise-i18n/pull/139 in it.
* JavaScript, blocked by Turbolinks 5 support in jquery.turbolinks, tracking PR https://github.com/kossnocorp/jquery.turbolinks/pull/58.

**Comment by timdiggins** [comment]
@glebm looks cool and good progress. Thought: if devise gets released soon, then might as well turn off tubolinks and move towards release?

Discovered some issues with the install, so will create issues in that repo (push me back here if that makes more sense).

**Comment by glebm** [comment]
All blocking issues are now fixed, ready to release as soon with Thredded v0.8.0.

**Comment by timdiggins** [comment]
This is a really great idea and the readme page sample screenshots look really good.

**Comment by glebm** [comment]
Ready to release
