### ISSUE TITLE
Describe best way to override methods on `Thredded::NullUser`

### ISSUE THREAD

**Issue by jayroh** [thredded/thredded#251]
In going through the process of overriding some of the permissions for thredded.com I started to think of the several ways I could monkey-patch `Thredded::NullUser` ... and as we all know, there are several different ways to monkey-patch a class.

For anyone needing some semi-to-very private or hidden messageboards this class will definitely need to be overridden.

Therefore - what's the *best* and *easiest* way we could make this class's methods overridden?

1. Rely on people to monkey-patch it however they want?
2. Allow a perscribed module with instance and class methods to be defined by the user in the parent app (say ... implement `Thredded::NullUserPermissions` in `app/models`?)

If there's an easy way to do this currently - we should offer some further documentation in the README detailing the best approach for this outside of "override these methods".

I'm apt to go with option number 2 because it feels easy enough .. "Create this module in this location and implement whatever methods you want to override, etc etc"

**Comment by glebm** [comment]
Automatically including a specific name is perhaps too much magic (e.g. thing like Find Usages in the IDE won't work).

I'd lean towards monkeypatching and guidelines for the best way to do this:

1. Create a ThreddedNullUserPermissions module in app/models/concern/thredded_null_user_permissions.rb that defines any of the following methods: ...
2. Include the module in the initializer:

  ```ruby
  Rails.application.config.to_prepare do
    Thredded::NullUser.send :include, ThreddedNullUserPermissions
  end
  ```

The module name should not be in the `Thredded::` namespace to avoid possible conflicts with plugins and Thredded's own code.

**Comment by jayroh** [comment]
Yup - that works! I'll get to putting a sample implementation together, documenting in the wiki, and linking to it from the README.
