### ISSUE TITLE
Feature Request: Sub Forum/Category for grouping message board

### ISSUE THREAD

**Issue by hisea** [thredded/thredded#261]
I'm just wondering if this is a feature that might be in the road map.

basically a mechanism to group message board, ie: 

Games (Sub-Forum/Category)
  - Diablo 3 (Message Board) 
  - Dota (Message Board)

Development (Sub-Forum/Category)
  - Rails
  - Node.js

**Comment by jayroh** [comment]
Never really thought about this. I have some questions though :)

Would this just be a top level categorization? Just group them together
under a name? Or would this be a functional messageboard with
sun-messageboards?

**Comment by hisea** [comment]
I would just be a top level categorization, like this:

https://www.ratemds.com/forum/

where RateMDs General Information and Diseases & Conditions are the top level categories, which just a container holding the messageboards.

**Comment by glebm** [comment]
This sounds simple enough (no new URLs on the user-side, just a "visual" grouping, with admin-level editing UI). @hisea If you'd like to implement it, I'd be OK with reviewing the PR. @jayroh, what do you think?

**Comment by jayroh** [comment]
I'd be totally game for this being pulled in. Absolutely 👍

**Comment by TheDudeWithTheThing** [comment]
you'd go with category implementation or messageboards having a parent_id ?

**Comment by jayroh** [comment]
thredded_messageboard belongs to thredded_messageboard_group
thredded_messageboard_group has many thredded_messageboards

instead of thredded_messageboards has and belongs to thredded_messageboards

**Comment by hisea** [comment]
I can definitely take a stab at this, do we want to make this group setting optional or mandatory.

if optional, what happens to the message boards that are without a group?

**Comment by jayroh** [comment]
I'd say probably render the group-less messageboards first, then loop
through the groups and their sub-messageboards.

**Comment by hisea** [comment]
Opened PR #263,  if this is the right direction I can add some specs.

Also I'm not sure where to put the migration, so I just left it in a separate file.

Thanks
