### ISSUE TITLE
Consolidate topic-level actions in one place

### ISSUE THREAD

**Issue by jayroh** [thredded/thredded#266]
Currently "edit topic" and "delete topic" are located in two different locations - respectively one is a link at the top, and one is a button at the bottom. I have a strong feeling that group of actions will be growing over time.

**Comment by glebm** [comment]
Since there is no way to undo a deletion, I was motivated by this iamge when placing the "Delete topic" button far away:

![needles](https://user-images.githubusercontent.com/216339/46987785-90cd4b80-d0ed-11e8-83fe-acd6e8de05ab.png)

**Comment by jayroh** [comment]
Hahaha great point!

Counterpoint - does that box of poison-tipped needles have a confirmation dialog of some sort? 

"Are you SURE you want to open this up? "

**Comment by glebm** [comment]
Good counter-point :)

**Comment by timdiggins** [comment]
I love that image. 

I agree that the things you might want to do to a topic are multiple: `Edit`, `Delete`, `Follow` / Unfollow, `Mark (all posts) as read`, and also "View". But it doesn't follow necessarily that all those things belong together! 

I think this issue should close till we have a concrete proposal of a change or a specific need. Feel free to reopen @jayroh
