### ISSUE TITLE
Post contents could use some text-overflow: ellipsis

### ISSUE THREAD

**Issue by jayroh** [thredded/thredded#267]
Relevant css class - `.thredded--post--content`

Example issue:

![](https://www.evernote.com/l/AUr5b44dLzxGMoCNx6QCSVZAJf40NLhZkKIB/image.png)

The post content div is dotted in red for context / emphasis

**Comment by glebm** [comment]
Or, alternatively `word-break: break-all` to avoid hiding any content.

**Comment by jayroh** [comment]
That's a nicer solution Gleb - thanks for the heads up. Just pushed up a fix.
