### ISSUE TITLE
Allow some way to return to the messageboard from the bottom of a post

### ISSUE THREAD

**Issue by jayroh** [thredded/thredded#268]
Currently when you reach the bottom of a thread's posts there is no way to return back to the messageboard outside of hitting the back button (sub-optimal because your read state is not updated at that point) or scrolling to the top and clicking the link up there.

Would the breadcrumbs be sufficient if they are included down at the bottom?

The challenge here would be with both design _and_ user experience I think.

**Comment by TheDudeWithTheThing** [comment]
breadcrumbs might be overkill, but at least it'd be a quick win. I'd imagine that 1% of the time people would actually want to switch messageboards so a link to "back to topics" or something would suffice.

Keyboard shortcuts being brought back would help. Could we have a UI element that follows the user to provide that same functionality?  Floaty header maybe?  Not sure if that's still an acceptable design thing.

**Comment by jayroh** [comment]
> Could we have a UI element that follows the user to provide that same
functionality? Floaty header maybe? Not sure if that's still an acceptable
design thing.

I think in the context of the parent app - this would be what I would do.
But putting something like this in place within an engine would often step
on the toes of a parent app's design.

I do like the idea of "back to topics" down at the bottom, though, Shaun. I
think that'd be great.

**Comment by jayroh** [comment]
This sort of UX enhancement can be handled by anyone implementing thredded within their app, so I'm closing this for now.
