### ISSUE TITLE
NameError: uninitialized constant Thredded::Errors::TopicReadDenied

### ISSUE THREAD

**Issue by jayroh** [thredded/thredded#269]

**Comment by glebm** [comment]
Same with PrivateTopicReadDenied. Need to either create these classes or switch from `authorize_reading` to `authorize obj, :read?`. I think perhaps custom classes are an overkill here, especially since the relevant information (object, failed permission name) is passed in the Pundit error.

**Comment by glebm** [comment]
Fixed for now by avoiding custom classes for these permissions
