### ISSUE TITLE
seems to depend on devise-like logout path -- needs doc or config

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded#271]
When installing it seems to depend on the logout path destroy_user_session_path -- I'm assuming this is part of an implicit expectation of using Devise, which is actually fine, but think this expectation needs a doc, or if not, needs an explicit config in the thredded.rb initializer

**Comment by jayroh** [comment]
Hey @timdiggins thanks for reporting this. This is most likely a remnant from its previous life as a full rails app and just never bubbled it's way up until now.

I'm not at my computer currently so I can't search - could you let us know where in particular you're encountering this issue?

**Comment by glebm** [comment]
It's in the standalone nav partial. We need to document that this partial needs to be overriden if not using devise

**Comment by glebm** [comment]
Now documented.

**Comment by zapnap** [comment]
As an alternative... I simply added a route to comply with the required devise route names (e.g. destroy_user_session_path) and this initially appears to work.

However, after some time it began triggering an undefined method error for ActionDispatch. I wasn't sure why this was happening at first and was scratching my head for several days but now it appears that it happens *only* after the RailsAdmin engine mount point is hit. Very strange. Looks like this is doc'd here also https://github.com/thredded/thredded/issues/280

**Comment by timdiggins** [comment]
@zapnap think it's simpler just to override the partial -- there are instructions in the README: https://github.com/thredded/thredded#standalone-layout

@glebm maybe the devise view (the inside of the `li. thredded--user-navigation--standalone`) should be in a separate partial, and not be referenced directly from _standalone, instead just come in as via a view_hook in the initializer (maybe by default) maybe?

**Comment by zapnap** [comment]
Same issue with overriding the partial. Something to do with RA clobbering the referenced routes? Strange. Will need to dig in further.

**Comment by glebm** [comment]
A few diagnostic questions:
1. Are you using thredded v0.8.2?
2. Have you considered using Thredded [with your application layout](https://github.com/thredded/thredded#application-layout) instead of standalone?
3. What is the exact error message?

Also, when referencing main_app routes, they must be referenced via <code><b>main_app.</b>my_path</code>.

**Comment by zapnap** [comment]
Yep, I am using my own application layout. I just tried the above for the sake of scoping the problem. Actual stack trace here: https://gist.github.com/zapnap/7b54fa2c33ddcb4c1d055bfd80bbe229 Thredded version is v0.8.2. Thanks for your help. Might be best to move this discussion to the RailsAdmin thread as this seems more relevant to that discussion?

**Comment by glebm** [comment]
@zapnap The other thread seems to have a very different issue with Rails admin.

Just a thought, what does your `routes.rb` look like (auth routes, thredded, and rails admin routes)?

**Comment by zapnap** [comment]
mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    mount Thredded::Engine => '/forum'

    # ...

    get '/login', to: 'sessions#new', as: :login
    get '/login', to: 'sessions#new', as: :new_user_session_path
    post '/login', to: 'sessions#create'

    get '/logout', to: 'sessions#destroy', as: :logout
    delete '/logout', to: 'sessions#destroy', as: :destroy_user_session_path

**Comment by glebm** [comment]
Are you using rails_admin v1.1.0 (latest)? If not, upgrading rails_admin might fix it.

Otherwise, a few ideas for diagnostics are:

* Move the mounted engines to the bottom of the file.
* print out `main_app.inspect` so we can have a look at what is going on with `@helpers` there.

**Comment by glebm** [comment]
(looks like this happened to somebody in 2012 https://github.com/sferik/rails_admin/issues/1248 with nothing but rails_admin and devise).

**Comment by zapnap** [comment]
Got it. If you look at the routes above, the :new_user_session_path route really should be :new_user_session. Derp. For some reason, this was all working absolutely fine on first load but failing on subsequent loads. Still don't understand that at all. Hmm.

**Comment by zapnap** [comment]
Thanks for your help @glebm and for the insanely fast response times ;-)

**Comment by zapnap** [comment]
(I still don't understand why this was working fine on first load, but in any case, it's resolved now... so perhaps a mystery for another time)

**Comment by glebm** [comment]
Awesome! :tada: 
You will probably also need to exclude all the Thredded models from rails_admin as per #280. Would appreciate if you could post a working config here or to the wiki then! Cheers!

**Comment by zapnap** [comment]
Actually, I no longer get an error, but it seems like the Thredded config still isn't reloading after RailsAdmin is initialized. After the first RailsAdmin load, I reload the thredded route and it's now using the stock layout, rather than my application layout. Very strange. But no more routing errors in any case ;-).

**Comment by glebm** [comment]
The initializer issue seems to be the one described in #280:

> the Thredded initializer settings get reset whenever you open rails_admin. The only fix I've found for that is making sure that every single model that Thredded uses is being ignored by RailsAdmin. Not the cleanest option.

Rails Admin is magic. Somehow it manages to reload the Thredded class. Explicitly requiring Thredded in the initializer might prevent this (`require 'thredded'`).

**Comment by zapnap** [comment]
Yeah no dice on the explicit require, unfortunately. Bah.

**Comment by jayroh** [comment]
Unrelated and unhelpful but I'm filing this issue in my bookmarks as
"reason #2142351235 to not use RA again"

Again - unhelpful, and tongue firmly in cheek - but ... well. Had to say it.
