### ISSUE TITLE
Empty before/after partials

### ISSUE THREAD

**Issue by jayroh** [thredded/thredded#276]
As mentioned in the discussion over at #273 

> Tangentially, since Thredded does not have a view hooks system (e.g. [like this one](https://github.com/glebm/rails_email_preview#hooks)) and the only way to extend the views is by overriding partials, perhaps we should additionally provide empty shared/nav/before and shared/nav/after partials that would allow adding more links before/after the navigation.

I was just thinking about this over the weekend, actually. There's another spot (I'm sure there are several) that I would personally benefit from having an available empty partial or two - and that's before and after the post textarea.  I'd like to tie in what I'm working on at [shubox](https://shubox.io) to the textarea to allow file uploads for [thredded.com](https://www.thredded.com).

I don't think we've reached the threshold where we would need the solution that [rails_email_preview](https://github.com/glebm/rails_email_preview#hooks) employs but I would certainly be open to discussing that in the future. Empty partials are a quick, easy, and unobtrusive solution for a handful of spots.

**Comment by glebm** [comment]
Empty partials aren't really suitable for plugins though because they are not composable. So, two plugins (or a plugin and the app) cannot override the same partial.

**Comment by jayroh** [comment]
TRUE!

However, we haven't really sketched out much of what a plugin system would look like so I'm apt to incrementally improve where it need be instead of jumping too far into engineering what we might need. For now I think some empty partials would be just fine until we can have a more open talk about a plugin API.

**Comment by timdiggins** [comment]
Similar thoughts about hooks in https://github.com/thredded/thredded/issues/357

**Comment by glebm** [comment]
Closing to consolidate discussion in the other issue.
