### ISSUE TITLE
Thredded doesn't work alongside rails_admin

### ISSUE THREAD

**Issue by StefanDorresteijn** [thredded/thredded#280]
Hey guys,

I'm using Thredded alongside [Rails_admin](https://github.com/sferik/rails_admin) and there are a couple issues.

First of all, the thredded policies don't have a rails_admin? function so you can't manage the forum's data from the admin panel. It's pretty easy to copy over the policies and overwrite them but it'd be easier for the policies to already have this functionality.

Then if you've decided to simply exclude the policies from rails_admin, the Thredded initializer settings get reset whenever you open rails_admin. The only fix I've found for that is making sure that every single model that Thredded uses is being ignored by RailsAdmin. Not the cleanest option.

Thanks,
Stefan

**Comment by jayroh** [comment]
@StefanDorresteijn I think we could probably justify adding that method. What is it that `rails_admin?` is checking for in the policies? I don't use rails_admin much these days, and have never with previously alongside `pundit`, so I'm unfamiliar with what the relationship is there.

And that's really weird regarding the Thredded class being reset upon visiting rails_admin. I can't imagine what in the thredded codebase would cause that to happen. Have you investigated any further with regards to when and where this is happening? Maybe raise an exception in one of the Thredded class's attr_readers/accessors, etc?

**Comment by glebm** [comment]
> the Thredded initializer settings get reset whenever you open rails_admin

If you are monkey-patching any Thredded classes, you might need to wrap that in `Rails.application.config.to_prepare do .. end` due to how Rails autoloading works.

**Comment by StefanDorresteijn** [comment]
@jayroh rails_admin?'s method would look something like this:

```
def rails_admin?(action)
    case action
      when :dashboard
        user.is_admin?
      when :index
        user.is_admin?
      when :show
        user.is_admin?
      when :new
        user.is_admin?
      when :edit
        user.is_admin?
      when :destroy
        user.is_admin?
      when :export
        user.is_admin?
      when :history
        user.is_admin?
      when :show_in_app
        user.is_admin?
      when :import
        user.is_admin?
      else
        raise ::Pundit::NotDefinedError, "unable to find policy #{action} for #{record}."
    end
  end
```

I have not continued testing why Rails Admin messes with the Thredded settings yet but I'll give it another look.

**Comment by glebm** [comment]
This should live in a separate gem. If someone makes a gem, we can link to it from Readme and move it into the thredded org for discoverability.

**Comment by zapnap** [comment]
I'm having trouble with this as well.

Still spelunking and I'm not sure where the config is getting clobbered yet. But I've noticed that if I define the config vars as methods they're not getting whacked. i.e.

    module Thredded # ghetto
      def self.layout; 'application'; end
    end

**Comment by jayroh** [comment]
jesus that is friggin weird :/

**Comment by glebm** [comment]
I've added a vanilla Rails Admin to an app generated with `thredded_create_app`, and added a breakpoint on one of the assignments to a `Thredded` module attribute.

Here is what I found:

```console
> RailsAdmin::Config.models_pool
["ApplicationRecord", "Generators::Thredded::Install::InstallGenerator", "Generators::Thredded::Install::Templates::Initializer", "Thredded", "Thredded::ActivityUpdaterJob", "Thredded::AllViewHooks", "Thredded::AtNotificationExtractor", "Thredded::AutoFollowAndNotifyJob", "Thredded::AutofollowMentionedUsers", "Thredded::BaseTopicView", "Thredded::Category", "Thredded::ContentFormatter", "Thredded::CreateMessageboard", "Thredded::DatabaseSeeder", "Thredded::Engine", "Thredded::Errors", "Thredded::HtmlPipeline::AtMentionFilter", "Thredded::HtmlPipeline::AutolinkFilter", "Thredded::HtmlPipeline::KramdownFilter", "Thredded::MarkAllRead", "Thredded::MembersMarkedNotified", "Thredded::Messageboard", "Thredded::MessageboardGroup", "Thredded::MessageboardGroupView", "Thredded::MessageboardUser", "Thredded::ModeratePost", "Thredded::NotifyFollowingUsers", "Thredded::NotifyPrivateTopicUsers", "Thredded::NotifyPrivateTopicUsersJob", "Thredded::NullPreference", "Thredded::NullUser", "Thredded::NullUserTopicReadState", "Thredded::Post", "Thredded::PostModerationRecord", "Thredded::PostNotification", "Thredded::PostView", "Thredded::PostsPageView", "Thredded::PrivatePost", "Thredded::PrivateTopic", "Thredded::PrivateTopicForm", "Thredded::PrivateTopicView", "Thredded::PrivateTopicsPageView", "Thredded::PrivateUser", "Thredded::SearchParser", "Thredded::Stats", "Thredded::Topic", "Thredded::TopicCategory", "Thredded::TopicEmailView", "Thredded::TopicForm", "Thredded::TopicPostsPageView", "Thredded::TopicView", "Thredded::TopicsPageView", "Thredded::TopicsSearch", "Thredded::UserDetail", "Thredded::UserExtender", "Thredded::UserMessageboardPreference", "Thredded::UserPermissions::Admin::IfAdminColumnTrue", "Thredded::UserPermissions::Admin::None", "Thredded::UserPermissions::Message::ReadersOfWriteableBoards", "Thredded::UserPermissions::Moderate::IfModeratorColumnTrue", "Thredded::UserPermissions::Moderate::None", "Thredded::UserPermissions::Read::All", "Thredded::UserPermissions::Write::All", "Thredded::UserPermissions::Write::None", "Thredded::UserPreference", "Thredded::UserPreferencesForm", "Thredded::UserPrivateTopicReadState", "Thredded::UserTopicFollow", "Thredded::UserTopicReadState", "Thredded::Version", "Thredded::ViewHooks::Config", "Thredded::ViewHooks::Renderer", "User"]
```

Looks like the bug is that Rails Admin considers all Thredded classes a "model". Looking into it.

**Comment by glebm** [comment]
OK, so looks like rails_admin is using `Thredded::Engine.config.autoload_paths`, which is great.
The thing about `config.autoload_paths` is that it's not the same as `Thredded::Engine.paths`.

`config.autoload_paths` only contains the configuration, not the default paths added by Rails to every engine in https://github.com/rails/rails/blob/cdb307294a43eec489f0ea6ffdc6f0a07b16ff5c/railties/lib/rails/engine/configuration.rb.

Luckily, `lib` is already in the default paths. Actually, so is everything else we use. This means we can just remove the explicit setting of `autoload_paths` from `lib/thredded/engine.rb` and we're all set.

Fuck. Magic.

**Comment by glebm** [comment]
Ah, bummer, the commit above does not resolve it, because marking `lib` as autoload will make it appear in autoload_paths. We need to either stop autoloading `lib`, or move all the files we don't want to be "eager" rails_admin-loaded out of it. I'll try the latter.

Magic is now officially a swear word.  :sweat_smile:

**Comment by glebm** [comment]
@zapnap It should work now, please give master a go!

**Comment by glebm** [comment]
Sent a PR to rails_admin that makes the madness slightly less mad also. God knows how many hours were lost to this RA bug worldwide.

**Comment by jayroh** [comment]
Gleb, have you considered running for president (of anything) in a few
years? I'd vote for you

**Comment by StefanDorresteijn** [comment]
I second that @jayroh

**Comment by zapnap** [comment]
Still seeing some problems unfortunately. Pulled latest master and tried again. Following stack trace occurs on thredded load after hitting RA endpoint

https://gist.github.com/zapnap/5ce33a363d1a1f8a483fc5bc52c14976

**Comment by zapnap** [comment]
... and now I can't reproduce it.

/me scratches head

**Comment by zapnap** [comment]
https://gist.github.com/zapnap/a8be2b23ed36134aced57c0a7ba69149

**Comment by glebm** [comment]
This seems like you didn't copy the [upgrade migration](https://github.com/thredded/thredded/blob/181dfa1a9ef3e62018d6385fa7f6ad013ad8085c/db/upgrade_migrations/20161019150201_upgrade_v0_7_to_v0_8.rb) when upgrading from thredded v0.7 to v0.8

**Comment by zapnap** [comment]
or I just didn't run it when I pushed to my staging server :( :( :(

Thanks and sorry to bother.

**Comment by zapnap** [comment]
I think this is closed? Thanks @glebm

**Comment by StefanDorresteijn** [comment]
Aye, fixed for me now too

**Comment by glebm** [comment]
Release v0.8.3 so that you don't have to depend on master!
