### ISSUE TITLE
Forem is no longer maintained

### ISSUE THREAD

**Issue by radar** [thredded/thredded#282]
[See notice on README](https://github.com/rubysherpas/forem)

Please remove mentions of this from your README (apart from the migration guide, of course).

Congratulations on building a successful community. Good luck for the future.

**Comment by jayroh** [comment]
Hey @radar - well this is a little ... bittersweet? I suppose? I always looked up to what you and @parndt were doing with Forem. So while I understand (completely understand) it's still a little bummer to get this issue.

Thanks for the good words, and thanks for pointing people over here. We'll update the README shortly.

p.s. wish you guys were at RailsConf

**Comment by parndt** [comment]
:heart: it's been too long, @jayroh !

**Comment by jayroh** [comment]
I knoooooooow 😩
