### ISSUE TITLE
thredded not able to shwo users name

### ISSUE THREAD

**Issue by atussec** [thredded/thredded#289]
on site wide am able to see the username but on thredded it returns as 
`#<USER:0X007FBA6BE86638>` am using rails 5rc1

**Comment by jayroh** [comment]
Hey @atussec - What does the `to_s` method look like on your `User` model?

**Comment by atussec** [comment]
i only have to_s in the initializer of thredded not in my user model. my user model works fine

**Comment by jayroh** [comment]
There are several methods Thredded expects to have implemented in your user
model and this is one of them.

**Comment by atussec** [comment]
so how will i fix this?

**Comment by jayroh** [comment]
In your `User` model define the `to_s` method.  Like here in the dummy app - https://github.com/thredded/thredded/blob/master/spec/dummy/app/models/user.rb#L5-L7

We have a `name` column in the `users` table so we delegate `to_s` to point to that.

**Comment by atussec** [comment]
thanks, its working now

**Comment by jayroh** [comment]
Great. Thanks @atussec 

We'll take note and make sure this is documented better in the README
