### ISSUE TITLE
Username being rendered as Object's address in memory

### ISSUE THREAD

**Issue by Capt-Obviouse** [thredded/thredded#290]
I installed Thredded on my website, everything went well. The forums load I can log in and out, however, every user is shown as the user object instead of the name, email, or anything at all in the User db. I am using Devise for my authentication and user management. I created a new rails app, installed devise, added a user, installed Thredded and I end with the same result.

**Comment by jayroh** [comment]
@Capt-Obviouse we'll do what we can to make sure this is more clear in the README (see #291).  Thanks for reporting the issue :)
