### ISSUE TITLE
where to get the forem data

### ISSUE THREAD

**Issue by atussec** [thredded/thredded#295]
i am running forem in production but planning to migrate to thredded. the only issue is how will i retrieve the data in forem table and migrate it to thredded column

**Comment by glebm** [comment]
See https://github.com/thredded/thredded/wiki/Migrate-from-Forem

**Comment by atussec** [comment]
it runs the migration but i cannot see previous post made using forem

**Comment by jayroh** [comment]
Since we don't have access to your forem data, or any forem data for that
matter, it's difficult for us to help you diagnose this.

If I were you I would recommend rolling back, and re-running the migration
with some pry debuggers thrown into the migration to see what, and where,
data is being moved over (if at all).

**Comment by atussec** [comment]
how will i  be able to throw in pry debugger? i am relatively not very good with rails. am learning by experience

**Comment by atussec** [comment]
ok this what i do. i run the forem migration and also the thredded migration on one branch. then i swtich back to the main branch and i can still see the forem content on the master branch and on the thereded branch i could not see the forem data on thredded message board

**Comment by jayroh** [comment]
I'm not sure what's going on between branches but once the data is transferred into the database it should be showing the data you've moved over from forem to thredded.

As for pry

1. add pry to your Gemfile

```ruby
gem 'pry-rails'
```

2. bundle install
3. Add pry to the migration

```ruby
require 'pry' # at the top

# ...
# migration stuff
# ... 
binding.pry  # where you want to stop the code and inspect what's going on
```

You should watch this for a nice comprehensive overview: http://railscasts.com/episodes/280-pry-with-rails

**Comment by glebm** [comment]
If you're used to more traditional debuggers, you can use byebug:

1. Add `gem 'byebug'` to Gemfile, then run `bundle`.
2. Put this where you want a breakpoint:

```
byebug
```

The Rails guide on debugging with byebug: http://edgeguides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-byebug-gem

**Comment by glebm** [comment]
I've updated the Forem to Thredded migration for Thredded v0.5.0, does it work for you now?

**Comment by atussec** [comment]
yes its working fine now
