### ISSUE TITLE
Remove MainAppDelegator and update docs

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded#296]
One usage of non-standalone thredded is to have a shared navigation bar. However currently any paths are looked up in the engine router first and fallback to the mainapp only if there is no such thredded route.

However if there is a link to, e.g. a search_path in the mainapp's navbar, then the thredded search path is used instead. Those paths are necessary to the thredded views.

Is the best thing for the main_app developers to prefix conflicting *(or indeed all)* routes with `main_app.` in any shared views? Or is there some better way (this must be a generic issue with other engines, but haven't run into it before).

**Comment by glebm** [comment]
It is indeed better to call the main app routes via `main_app`. I hadn't thought of this kind of conflict when I added https://github.com/thredded/thredded/blob/master/lib/thredded/main_app_route_delegator.rb.

Most other engines don't do this delegation and always require main_app developers to prefix everything with main_app.

**Comment by timdiggins** [comment]
@glebm So do you think we should remove the main app delegator and increase the OOB burden for new implementors? 

Or leave as it is.

Or (my preference I think) change the path helpers to be more weird/specific (especially for seach_path which is a more likely crossover  -- could change the helper to thredded_search_path?)

**Comment by glebm** [comment]
I'd lean towards the `main_app` approach as it is more correct.

**Comment by jayroh** [comment]
I would agree with Gleb on this. 👍🏼
