### ISSUE TITLE
HABTM Links between topics and main_app resources...

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded#298]
As mentioned in https://github.com/thredded/thredded/issues/297 I'm embedding thredded in another app which has a `Job` model which may have many topics which mention the job (by linking to it).

I'm planning on parsing every post for such links, and when found add a link (a HABTM link between main_app `Job` and thredded `Topic`) to the owning topic. I don't see a good abstraction for adding this to thredded so will probably attempt to do this with an `after_action` monkey patch of the topic controller from within the main_app. 

Alternatively if you have a conception of a (future) feature within Thredded itself that might help this, do let me know. Otherwise feel free to just close.

**Comment by glebm** [comment]
@jayroh mentioned something like this [here](https://github.com/thredded/thredded/issues/65).

However, this sounds like should be done on the model level (not the controller), so monkey-patching `Thredded::Topic` is the way to go.

**Comment by timdiggins** [comment]
ok, great thanks @glebm for your points. I'm going with model-level callbacks (even though I know there are so many problems with them, it just seems the right balance at the moment -- probably will live to eat these words).
