### ISSUE TITLE
Architectural question

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded#299]
Why does Post have a messageboard_id which is mandatory and yet a Topic (in fact a postable_id polymorphic, but always a Topic it seems) is non mandatory. The UI seems to indicate that Topic is actually mandatory for a Post, and thus it should link to messageboard only through the Topic. 

Some kind of hidden complexity or future planning I haven't understood here.

**Comment by glebm** [comment]
I think it should be mandatory.
`postable_id` is not polymorphic. It used to be, but then we split up topics and private topics into separate models without renaming the field to something like `topic_id`.

**Comment by timdiggins** [comment]
@glebm ah ok, in which case messageboard_id should be removed altogether as it can be retrieved via the topic.

**Comment by glebm** [comment]
@timdiggins I think it's used for `cache_counter` of the posts in a messageboard. Perhaps we can remove the column and replace the `cache_counter` with [counter_culture](https://github.com/magnusvk/counter_culture).

**Comment by jayroh** [comment]
Never heard of counter_culture until now and dang that looks awesome

**Comment by glebm** [comment]
Off-topic: We'll actually need counter_culture (or something like it) once the moderation (#45) is in place, because pending/blocked posts will skew the counters.

**Comment by timdiggins** [comment]
@glebm I use counter culture a lot now (since this issue!) but have never brought into Thredded. Still up for integrating it in a PR and then removing messageboard_id from posts (if still possible)?

And FYI also would be nice to rename `postable_id` into `topic_id`.

**Comment by glebm** [comment]
> Still up for integrating it in a PR

If it helps us solve a particular issue, I don't mind, though so far we haven't needed it.

> And FYI also would be nice to rename postable_id into topic_id.

Yes, it would be nice!

> removing messageboard_id from posts

IIRC this column helps with performance on a few queries, so I'd prefer we keep it.
