### ISSUE TITLE
Upgrading an installed version / 'upgrade_migrations'

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded#306]
I was just trying to test out the PR and how it would look embedded within the main_app I'm building, and realized I didn't really understand how to upgrade.

I think it might be useful to start sketching out how to do this, even in rudimentary form.

I haven't encountered the pattern of `upgrade_migrations` before and haven't been successful in googling this (TBH I'm not very knowledgeable about engines, so maybe this is the gap in my knowledge, but the rails guide on engines doesn't mention  `upgrade_migrations`). How is this meant to work? Should `rake thredded:install:migrations` install the relevant version upgrades? (but in fact this seems to only installing the base one).

Additionally, how do you build these files when developing on thredded? 

some pointers would be helpful, then maybe can just start drafting some changes for the README.rb

The best I can do for now:

---------

### Upgrading an existing install

1) To upgrade the initializer:

```console
rails g thredded:install
```

But then compare this with the previous version to decide what to keep. 

2) To upgrade the database (in this example from v0.4 to the latest):

```console
cp `bundle show thredded`/db/upgrade_migrations/20160501151908_upgrade_v0_4_to_v0_5.rb db/migrate
rake db:migrate
```

**Comment by glebm** [comment]
The base migration is always at the latest version. We maintain this manually.

There is no command to copy over the appropriate upgrade migration (because we don't know the previous version that was installed), so just copy over the migration like in the command above and run it. You may want to modify the timestamp (file name prefix) as well.

What you posted above looks good for the Readme :+1:

**Comment by timdiggins** [comment]
and presumably if upgrading several versions, it's recommended to run the v0.3->v0.4 migration for example at v0.4 of the code (to ensure it actually runs).
