### ISSUE TITLE
NoMethodError - undefined method `starts_with?' for nil:NilClass when adding anchor tag without 'href' attribute

### ISSUE THREAD

**Issue by tomczakdominik** [thredded/thredded#313]
It looks like adding `anchor` tag without `href` attribute in post content causes this line https://github.com/thredded/thredded/blob/master/app/models/concerns/thredded/post_common.rb#L12 to raise `NoMethodError - undefined method 'starts_with?' for nil:NilClass`. I added `<a` at the end of my post here and crashed the app -> https://thredded.org/thredded/off-topic/no-reward-is-worth-this

**Comment by glebm** [comment]
Thanks, should be fixed by the commit above

**Comment by tomczakdominik** [comment]
I forked the repo in the meantime and fixed this also (in slightly different way though) + updated factories - please take a look at my PR https://github.com/thredded/thredded/pull/319
