### ISSUE TITLE
YouTube embeds blocked by iframe sandbox

### ISSUE THREAD

**Issue by lawso017** [thredded/thredded#314]
The 'sandbox' => 'allow-forms allow-scripts' attributes added to iframes result in YouTube embeds not playing.

www-embed-player.js:292Uncaught SecurityError: Failed to read the 'cookie' property from 'Document': The document is sandboxed and lacks the 'allow-same-origin' flag.

within YouTube's www-embed-player.js

**Comment by lawso017** [comment]
Example in demo:

https://thredded.org/thredded/help-bugs-and-suggestions/suggestionss#post_48735

**Comment by glebm** [comment]
I believe this has already been addressed by https://github.com/thredded/thredded/commit/995bafe25784e5cb2eca3d558d0cc1e3aceea5c0

**Comment by glebm** [comment]
Just deployed a new version, and the video now works.

**Comment by jayroh** [comment]
Yup! It's all fixed. Ran into that issue last week as well.
