### ISSUE TITLE
UI tweak to include follow status and modified unread status

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded#317]
Following on from https://github.com/thredded/thredded/pull/310, @EllaNancyFay and I have tweaked the styles in our main_app as follows -- this could be kept in our main_app, or pulled into thredded as a default if you like it:

**How the topics#index looks, with unread/read and followed/unfollowed:**
In this the bells indicate following, and the bold represents unread. It seems fairly intuitive when you use it (could make a PR so you can try out). I think it could do with adding the total number of posts as just a textual annotation (would want to change thredded DOM for this)
![local](https://cloud.githubusercontent.com/assets/18395/15775097/f0296084-2977-11e6-839b-2dc278b0acda.png)

**The header for a topic which you are following:**
![local](https://cloud.githubusercontent.com/assets/18395/15775060/c0b8df00-2977-11e6-89c8-d38cbab9c600.png)

**The header for a topic which you are not following:**
![local](https://cloud.githubusercontent.com/assets/18395/15775068/cf58d042-2977-11e6-8d53-70eb705b5579.png)

What do you think @glebm @jayroh for inclusion in Thredded (once the main PR is merged)

**Comment by glebm** [comment]
Nice!

**Comment by jayroh** [comment]
I LOVE IT

I have only a couple of comments!

The treatment on topics#index - what do you think about applying an opacity of, say, 70-80% to the bell by default and 100% on :hover/:focus? On a page where there are many follows it might get a little noisy. If possible, take a look and see how it looks with ... 40% of the topics on any given topics#index marked as "following" to see how it looks? Just as an exercise in max edge-cases.

What would it look like if the bell was abutted to the right of the topics header(s)? Both on index and show? I do like seeing the # of posts in a topic on #index and feel like the bell being set to the right might keep the vertical visual weight a little more balanced. With a bell to the left on both cases you keep some additional proximity for the messaging. For example:

![](https://www.evernote.com/l/AUqDZeh2blxPbYeiFMgmuesU0HntTYS4ieAB/image.png)

These two things are closely (if not wholly) related but the proximity doesn't represent this fact.

**Comment by timdiggins** [comment]
Although we've done the change to add Follow status icon in #394 in the lists and headers, there is still the question (in this issue) about whether to change the way that total counts of posts in a topic are represented, but separating out into a different issue: #402
