### ISSUE TITLE
simple_form

### ISSUE THREAD

**Issue by glebm** [thredded/thredded#32]
What do you think about using simple_form for forms?
- Easier to style: both layout and classes can be changed by the application hosting the engine.
- Come with better error messages (the forms we have currently don't show any on rails4).

I can implement it once my other pull request is merged.

**Comment by jayroh** [comment]
@glebm @timdiggins thoughts on simple form? Do either of you think it’s worth the added footprint to the  dependencies?

(Context: was looking through some of the old issues and reasoning about which should stay and which could go)

**Comment by timdiggins** [comment]
I love simple-form and am a happy user on several projects. I agree it might give a mechanism for host application to override styling (though I've not worked through exactly how to make DOM-changes *easy* -- configuring the wrappers can be quite tricky to get right I recall). I'd 100% support a PR (or a series of PRs) that would introduce it, but I'm happy with a 1.1+ release target (or closing the ticket until someone comes along with an offer / PR)

**Comment by jayroh** [comment]
Yeah, Tim. The wrappers, and the associated html, would definitely need to match up with the current markup as much as possible. Outside of the additional dependency that was the other concern I'd have related to this -- making sure that there is no breakage for people who've heavily, or even slightly, customized their forums.

**Comment by jayroh** [comment]
For the record - I, too, love simple_form :).

**Comment by glebm** [comment]
Closing for now to de-clutter the tracker but still open to a PR.
