### ISSUE TITLE
v5 to v6 migration missing moderation_state additions

### ISSUE THREAD

**Issue by lawso017** [thredded/thredded#330]
Trying to upgrade to v0.6, it appears the v0.5 to v0.6 migration has not added the moderation_state fields.

**Comment by glebm** [comment]
Hi, the moderation_state fields are added in the v0.4 to v0.5 migration: https://github.com/thredded/thredded/blob/master/db/upgrade_migrations/20160501151908_upgrade_v0_4_to_v0_5.rb

**Comment by lawso017** [comment]
Thanks... thought I started with 0.5 but I could be mistaken.
