### ISSUE TITLE
Use cached rendered post HTML

### ISSUE THREAD

**Issue by jayroh** [thredded/thredded#331]
The weekly Skylight report for thredded.com shows that the controller causing the most "agony" is `topics#show`. Looking through the event sequence shows that it's in the view layer. See here:

![](https://www.evernote.com/l/AUoF1_UEuH5A8qWO5pcU2dvTa3zX1Ax6t1oB/image.png)

I'm thinking that using the html pipeline on each post, for every request, strikes me as unnecessary and probably a bit of a bottleneck we can pass off after the first render.

**Comment by glebm** [comment]
We're actually caching the posts already: https://github.com/thredded/thredded/blob/master/app/views/thredded/posts/_post.html.erb.

**Comment by glebm** [comment]
Is Thredded.com using Rails 5? Because on Rails 4 it will make 1 request to memcached for each post, but on Rails 5 it will use memcached multi_get.

**Comment by jayroh** [comment]
Yes sir, it's using rails 5 currently.

Even if we're caching w/memcache - it's curious why that post partial is taking up so much time in the stack.

**Comment by glebm** [comment]
Do you have the log available for that request? It should show how many posts were fetched from cache (like "cache hits: 20 / 30").

**Comment by jayroh** [comment]
I don't have it handy but I can dig them up when I investigate this further.

On Mon, Jun 13, 2016 at 11:17 AM, Gleb Mazovetskiy <notifications@github.com
