### ISSUE TITLE
ExecJS::ProgramError: Unexpected token: name (ThreddedCurrentlyOnline)

### ISSUE THREAD

**Issue by lanrewajub** [thredded/thredded#334]
Hello, 
the gem is fantastic! Working well on my nitrous.io development environment but rejected the deployment to Heroku with the error above.
Kindly help.
Regards

**Comment by jayroh** [comment]
Hey @lanrewajub! Could you post a more comprehensive stack-trace with that error? It'd help give some further  context

**Comment by lanrewajub** [comment]
Thanks for the quick response jayroh! However, I was able to deploy to heroku after removing all the .js files uploaded while trying use my application layout but failed and had to revert to thredded/application. 
But now i have a problem with the email system. I create a private message and expected an email but never got one. Do I have to configure anythins for email on heroku. Presently I have one used by devise on Heroku (sendgrid)
Kindly assist.

Regards

**Comment by jayroh** [comment]
Yup, not a problem!

As far as emails - you should have something like sendgrid or mailgun set
up for your parent app so there's a service that'll send the emails.

*And* you should have your parent app configured to use the appropriate
ActiveJob queue adapter. These are the adapters available through the
current released version of Rails 4:
http://edgeapi.rubyonrails.org/classes/ActiveJob/QueueAdapters.html

If you're using sidekiq, select that, for example. More info on ActiveJob
here - http://edgeguides.rubyonrails.org/active_job_basics.html

**Comment by lanrewajub** [comment]
Thanks a lot. Got the email after a while. But a small issue i have now is that when i opened the link in the body of the mail...the Title on the browser included (Thredded...........)

is there no way to customize that?

regards,

**Comment by jayroh** [comment]
Something in your layout must have "Thredded" in it.  I understand you're
using Nitrous.io for your development but if you have access to a shell
anywhere with your code you can search through your view files' contents
with something like:

`find ./app/views -name *.html.erb | xargs grep Thredded`

That should help track down any layouts or views that have "Thredded"
hard-coded

**Comment by lanrewajub** [comment]
Than you. 
I searched but the instances are not unusual. Meanwhile, the full text of the title is "Thredded  Please sign in first". the sign in first came from the i18n. I also override 2 views (_nav and standalone). I am not sure i hard-coded the word anywhere. I am using the thredded/application for my layout. Any assistance will be appreciated.
Reards,

**Comment by lanrewajub** [comment]
I tried to sign out and perform an action and when the Please sign in first message is displayed on the page, the Title on the browser reads...."Thredded Please sign in first".

**Comment by jayroh** [comment]
```
$ ag "Thredded" app/views
app/views/layouts/thredded/application.html.erb
4:    <title>Thredded | <%= yield :thredded_page_title %></title>
```

I can only guess that maybe you're using the stock thredded application
layout?

My best advice is to look in your logs to see what views are being rendered
and when.

best,

Joel

**Comment by lanrewajub** [comment]
Thank you jayroh.....i have done justice to it by overriding the application.html.erb.

Thanks a lot for your time.

**Comment by jayroh** [comment]
No problem! Happy to help :)
