### ISSUE TITLE
Thredded slower the more topics it gets?

### ISSUE THREAD

**Issue by c2169000** [thredded/thredded#338]
Have you guys tested Thredded's response time when it gets 1000+ topics? Or maybe know of a nice way of doing it?

Ref. [rubysherpas/forem: Forem slower the more topics it gets #697](https://github.com/rubysherpas/forem/issues/697)

**Comment by glebm** [comment]
@c2169000 Hi! You can easily test it out locally by following the [development instructions](https://github.com/thredded/thredded#development) and changing the number of topics generated in seeds.rb (https://github.com/thredded/thredded/blob/master/db/seeds.rb#L22).

rack-mini-profiler is already set up so if it's slow you can see why by clicking the tiny XXXms number in the top left corner.

If it's slow, then it's a legitimate bug. If we're not missing any indices, Thredded should easily support hundreds of thousands of topics.

**Comment by avitus** [comment]
I have migrated about 500k posts over ~1k topics and the performance is dramatically faster than Forem. Load times according to New Relic are now ~600ms vs almost 6 seconds on Forem.

**Comment by jayroh** [comment]
now there's an endorsement if I've ever seen one. Thanks @avitus :)

**Comment by glebm** [comment]
@avitus Awesome, thanks! Would love to know where you are using Thredded if you can share
