### ISSUE TITLE
Bug: Search empty forum exception

### ISSUE THREAD

**Issue by izbor** [thredded/thredded#339]
When you don't have any posts and tries to search topics and posts you get next exception:

NoMethodError in Thredded::TopicsController#search
undefined method `visitor' for #<ActiveRecord::Relation []>

activerecord (5.0.0.rc1) lib/active_record/relation/delegation.rb:123:in `method_missing'
activerecord (5.0.0.rc1) lib/active_record/relation/delegation.rb:93:in `method_missing'
active_record_union (1.1.1) lib/active_record_union/active_record/relation/union.rb:31:in `set_operation'
active_record_union (1.1.1) lib/active_record_union/active_record/relation/union.rb:11:in `union'
thredded (0.6.1) lib/thredded/topics_search.rb:18:in `each'
thredded (0.6.1) lib/thredded/topics_search.rb:18:in `reduce'
thredded (0.6.1) lib/thredded/topics_search.rb:18:in `search'
thredded (0.6.1) app/models/thredded/topic.rb:14:in `block in <class:Topic>'

I was not logged in as well.

**Comment by glebm** [comment]
@izbor This has been fixed in Thredded v0.6.2 (by bumping the active_record_union dependency), please update.
