### ISSUE TITLE
Cannot Send Private Msg on first installation?

### ISSUE THREAD

**Issue by wanqizhu** [thredded/thredded#340]
Hi,

I followed all the installation instructions for Thredded, and everything seems up and running. However, I don't seem to be able to send any private msgs from any user to any user, admin or not. When I submit a new private topic, the page just refreshes and nothing happens. This is what terminal logs:

```
Started POST "/forum/private-topics" for ::1 at 2016-07-13 21:31:06 -0500
Processing by Thredded::PrivateTopicsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"wmKTBN00OsvpwrYDQS8/lxaySBGPVh3gl3TjwVS55hO6WcMiE77iDrA4xW+64+njEc73AtDmR8XKsxBpw4ro0A==", "private_topic"=>{"title"=>"1", "user_ids"=>"3", "content"=>"3"}}
  User Load (0.1ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ?  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
  User Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" IN (3, 1)
  Thredded::PrivateTopic Exists (25.9ms)  SELECT  1 AS one FROM "thredded_private_topics" INNER JOIN "friendly_id_slugs" ON "friendly_id_slugs"."sluggable_id" = "thredded_private_topics"."id" AND "friendly_id_slugs"."sluggable_type" = ? WHERE ("thredded_private_topics"."id" IS NOT NULL) AND "thredded_private_topics"."slug" = '1' LIMIT 1  [["sluggable_type", "Thredded::PrivateTopic"]]
  Thredded::PrivateTopic Exists (1.4ms)  SELECT  1 AS one FROM "thredded_private_topics" INNER JOIN "friendly_id_slugs" ON "friendly_id_slugs"."sluggable_id" = "thredded_private_topics"."id" AND "friendly_id_slugs"."sluggable_type" = ? WHERE ("thredded_private_topics"."id" IS NOT NULL) AND ("friendly_id_slugs"."sluggable_type" = 'Thredded::PrivateTopic' AND "friendly_id_slugs"."slug" = '1') LIMIT 1  [["sluggable_type", "Thredded::PrivateTopic"]]
  Thredded::PrivateTopic Exists (2.9ms)  SELECT  1 AS one FROM "thredded_private_topics" WHERE "thredded_private_topics"."hash_id" = '7412719578e72fd9be9e' LIMIT 1
  User Exists (0.2ms)  SELECT  1 AS one FROM "users" WHERE ("users"."username" = 'iqiq' AND "users"."id" != 1) LIMIT 1
  User Exists (0.2ms)  SELECT  1 AS one FROM "users" WHERE ("users"."username" = 'tmp' AND "users"."id" != 3) LIMIT 1
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/thredded-0.6.2/app/views/thredded/private_topics/_breadcrumbs.html.erb (0.7ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/thredded-0.6.2/app/views/thredded/posts_common/form/_before_content.html.erb (0.0ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/thredded-0.6.2/app/views/thredded/posts_common/form/_after_content.html.erb (0.0ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/thredded-0.6.2/app/views/thredded/posts_common/form/_content_field.html.erb (3.1ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/thredded-0.6.2/app/views/thredded/private_topics/_form.html.erb (5.9ms)
   (0.2ms)  SELECT "thredded_messageboards"."id" FROM "thredded_messageboards" WHERE "thredded_messageboards"."closed" = 'f'  ORDER BY "thredded_messageboards"."topics_count" DESC
   (0.1ms)  SELECT COUNT(*) FROM "thredded_posts" WHERE "thredded_posts"."messageboard_id" IN (1, 2) AND "thredded_posts"."moderation_state" = ?  [["moderation_state", 0]]
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/thredded-0.6.2/app/views/thredded/shared/nav/_moderation.html.erb (4.3ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/thredded-0.6.2/app/views/thredded/shared/nav/_notification_preferences.html.erb (3.6ms)
   (0.2ms)  SELECT COUNT(DISTINCT "thredded_private_topics"."id") FROM "thredded_private_topics" INNER JOIN "thredded_private_users" ON "thredded_private_users"."private_topic_id" = "thredded_private_topics"."id" LEFT OUTER JOIN "thredded_user_private_topic_read_states" ON "thredded_private_topics"."id" = "thredded_user_private_topic_read_states"."postable_id" AND "thredded_user_private_topic_read_states"."user_id" = 1 WHERE "thredded_private_users"."user_id" = ? AND ("thredded_user_private_topic_read_states"."id" IS NULL OR "thredded_user_private_topic_read_states"."read_at" < "thredded_private_topics"."updated_at")  [["user_id", 1]]
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/thredded-0.6.2/app/views/thredded/shared/nav/_private_topics.html.erb (5.3ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/thredded-0.6.2/app/views/thredded/shared/nav/_standalone.html.erb (2.8ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/thredded-0.6.2/app/views/thredded/search/_form.html.erb (0.6ms)
  Rendered thredded/shared/_nav.html.erb (23.1ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/thredded-0.6.2/app/views/thredded/shared/_header.html.erb (23.7ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/thredded-0.6.2/app/views/thredded/shared/_flash_messages.html.erb (0.5ms)
  User Load (0.3ms)  SELECT "users".* FROM "users" INNER JOIN "thredded_user_details" ON "thredded_user_details"."user_id" = "users"."id" WHERE ("thredded_user_details"."last_seen_at" > '2016-07-14 02:26:06.293672')
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/thredded-0.6.2/app/views/thredded/shared/_currently_online.html.erb (1.7ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/thredded-0.6.2/app/views/thredded/shared/_page.html.erb (31.3ms)
  Rendered /usr/local/lib/ruby/gems/2.1.0/gems/thredded-0.6.2/app/views/thredded/private_topics/new.html.erb within layouts/thredded/application (42.5ms)
Completed 200 OK in 165ms (Views: 108.4ms | ActiveRecord: 32.0ms)


Started GET "/forum/autocomplete-users?ids=3" for ::1 at 2016-07-13 21:31:06 -0500
Processing by Thredded::AutocompleteUsersController#index as JSON
  Parameters: {"ids"=>"3"}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ?  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
  User Load (0.3ms)  SELECT "users".* FROM "users" WHERE "users"."id" = 1
  Thredded::UserDetail Load (0.4ms)  SELECT  "thredded_user_details".* FROM "thredded_user_details" WHERE "thredded_user_details"."user_id" = ? LIMIT 1  [["user_id", 1]]
  User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."id" = 3
Completed 200 OK in 12ms (Views: 0.4ms | ActiveRecord: 1.1ms)
```

I'm new to ruby on rails, so I don't really understand what is going on behind the scene. I tried looking at the source code, and presumably it's failing the create function in private_topics_controller.rb.

`def create
      @private_topic = PrivateTopicForm.new(new_private_topic_params)
      if @private_topic.save
        redirect_to @private_topic.private_topic
      else
        render :new
      end
    end`

I tried poking around in the rails console as well. Does it has anything to do with private users, and if so, how can I get private messaging to work? Any help would be greatly appreciated! 

- Wanqi

**Comment by wanqizhu** [comment]
I actually think the issue is with the mailer. I have my own mailer which I'm using with device -- can I configure Thredded to use my mailer? Alternatively, can I remove all mailing functionality from Thredded?

Thanks!

**Comment by timdiggins** [comment]
@wanqizhu the actual mails are sent in an "ActiveJob" so that the response can go back to the user before doing the possibly slow work of sending the mail -- do you have an active job backend (like Sidekiq, Resque, Delayed Job ) set up in your rails app? see http://guides.rubyonrails.org/active_job_basics.html#backends

**Comment by wanqizhu** [comment]
I'm not using any active job backends. When I deployed the code without customization to a test server in production, private msg works, but I can't test it in development. In development, the log never seem to call the mailer.

Additionally, as soon as I customize the thredded_admin? function in my user.rb, private msg breaks again in production. The same with trying to use my own mailer -- is there a similar setting to 

config.mailer = 'MyMailer' in devise.rb?

**Comment by jayroh** [comment]
Hi @wanqizhu!

>  I have my own mailer which I'm using with device -- can I configure Thredded to use my mailer?

As of right now, no, I don't think that's something that's doable. If you'd like to customize the view, however, I think that's a good first approach. Is it the view itself that needs customizing or is there something more that needs to happen? If you let us know, we can think about it and possibly take that sort of thing into consideration for future releases. 

And @timdiggins makes a good point, there are several points in the mail lifecycle that require some configuration - 

1. Making sure there's a queue set up for active job. In addition to sidekiq, resque, et al - there's an in-memory async adapter you can use. For more info on that - http://guides.rubyonrails.org/active_job_basics.html#backends

2. Is there an email service configured? Sendgrid, mailgun, etc.

**Comment by jayroh** [comment]
> In development, the log never seem to call the mailer.

With rails, at least in most of the environments I've worked in, sending email is turned off. 

Example in the rails guides here: http://guides.rubyonrails.org/action_mailer_basics.html#example-action-mailer-configuration

I believe that in development mode, this is usually set to false - 

```ruby
config.action_mailer.perform_deliveries = false
```

**Comment by jayroh** [comment]
> Additionally, as soon as I customize the thredded_admin? function in my user.rb, private msg breaks again in production.

This is probably another, unrelated, issue. Could you start another issue with the contents of your changes to user.rb? And the error you see when you test it out in production?

**Comment by wanqizhu** [comment]
Actually, it's now delivering mail in development but not in production. I think I don't really understand the mailer lifecycle. I haven't set up any mailer specifics except through devise:

  config.action_mailer.delivery_method = :smtp
  config.action_mailer.perform_deliveries = true
  config.action_mailer.default :charset => "utf-8"

  config.action_mailer.smtp_settings = {
    address: "smtp.gmail.com",
    port: 587,
    domain: ENV["GMAIL_DOMAIN"],
    authentication: "plain",
    enable_starttls_auto: true,
    user_name: ENV["GMAIL_USERNAME"],
    password: ENV["GMAIL_PASSWORD"]
  }


for both development.rb and production.rb.


I'm getting this error in production.log:

`----==_mimepart_578d08f5b5cfe_378a2b0230996ee0637c6--

I, [2016-07-18T16:51:01.852747 #14218]  INFO -- : [ActiveJob] [Thredded::NotifyPrivateTopicUsersJob] [f7458b2d-c50f-414f-bbc4-983aec3e322a] [ActionMailer::DeliveryJob] [9d31b5dc-400d-45da-8627-c81f93c92fb9] Performed ActionMailer::DeliveryJob from Inline(mailers) in 902.47ms
I, [2016-07-18T16:51:01.852850 #14218]  INFO -- : [ActiveJob] [Thredded::NotifyPrivateTopicUsersJob] [f7458b2d-c50f-414f-bbc4-983aec3e322a] Performed Thredded::NotifyPrivateTopicUsersJob from Inline(default) in 941.17ms
I, [2016-07-18T16:51:01.853091 #14218]  INFO -- : Completed 500 Internal Server Error in 1533ms
F, [2016-07-18T16:51:01.856631 #14218] FATAL -- : 
EOFError (end of file reached):
  /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/net/protocol.rb:153:in `read_nonblock'
  /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/net/protocol.rb:153:in `rbuf_fill'
  /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/net/protocol.rb:134:in `readuntil'
  /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/net/protocol.rb:144:in `readline'
  /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/net/smtp.rb:938:in `recv_response'
  /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/net/smtp.rb:924:in `block in getok'
  /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/net/smtp.rb:948:in `critical'
  /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/net/smtp.rb:922:in `getok'
  /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/net/smtp.rb:830:in `helo'
  /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/net/smtp.rb:604:in `do_helo'
  /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/net/smtp.rb:556:in `do_start'
  /opt/rubies/ruby-2.1.8/lib/ruby/2.1.0/net/smtp.rb:520:in `start'
  mail (2.6.4) lib/mail/network/delivery_methods/smtp.rb:113:in `deliver!'
  mail (2.6.4) lib/mail/message.rb:2149:in `do_delivery'
  mail (2.6.4) lib/mail/message.rb:237:in `block in deliver'
`


What exactly does config.action_mailer.default_url_options  mean? I deployed my code to a test server on AWS -- I wonder if it's because the servers are different from my live server, where I can send mail normally in production.


> As of right now, no, I don't think that's something that's doable. If you'd like to customize the view, however, I think that's a good first approach. Is it the view itself that needs customizing or is there something more that needs to happen? If you let us know, we can think about it and possibly take that sort of thing into consideration for future releases.

I guess I don't really need to use my own mailer. I just set up one to send out custom emails:

`class MyMailer < Devise::Mailer   
  helper :application # gives access to all helpers defined within `application_helper`.
  include Devise::Controllers::UrlHelpers # Optional. eg. `confirmation_url`
  default template_path: 'devise/mailer' # to make sure that your mailer uses the devise views

  default from: '****'

  def store_redeem_email(user, item, country)
  	@user = user
  	@item = item
  	if Rails.env.development? | Rails.env.test?
  		mail(to: "****", subject: "[TEST] Store redemption by " + @user.email + " for " + Rails.application.config.STORE_ITEM_DESCRIPTION[@item] + ", " + country)
  	else
		  mail(to: "****", cc: Rails.application.config.admins, subject: "Store redemption by " + @user.email + " for " + Rails.application.config.STORE_ITEM_DESCRIPTION[@item] + ", " + country)
  	end
  end 
end`


What's the easiest way to customize how the Thredded emails look, provided I can actually get them to work in both dev and production?

Sorry for throwing all these questions; I'm just learning everything so I probably have a lot of misunderstanding in terms of how everything works. Thanks for all the help!

**Comment by wanqizhu** [comment]
Nevermind, I just messed up a configuration setting in the environment variables. The mailer is working now.

What's the easiest way to customize how the Thredded emails look?

**Comment by jayroh** [comment]
@wanqizhu In your parent application you would want to create the following paths/files to the ones you would like to override:

```
app/views/thredded/post_mailer/post_notification.html.erb
app/views/thredded/post_mailer/post_notification.text.erb
app/views/thredded/private_topic_mailer/message_notification.html.erb
app/views/thredded/private_topic_mailer/message_notification.text.erb
```

**Comment by wanqizhu** [comment]
@jayroh Thanks! One final question: what's the easiest way to disable automatic following on topics one posts in? As in, when I create/post a topic, I don't want to automatically follow it (and thus get constant email notifications).

**Comment by jayroh** [comment]
Great question. @timdiggins would be able to shed some light on that?

I'm not at my computer right now to check but it might be something you can set in your own personal preferences.

/forum_name/preferences maybe?

**Comment by timdiggins** [comment]
@wanqizhu @jayroh IIRC there is a way to stop automatic following on topics you post in, you automatically get added when you engage with the post. The current workaround is that you can immediately unfollow after posting / creating.

The longer term* fix is that we add a preference to change the frequency of notifications (including no notifications). I'm not sure it does make sense to have a setting "don't autofollow when I post" -- this feels like an antisocial setting, encouraging dumping and running. But I do think people are getting too many notifications, so need to have an option to only get notifications, say every hour or every 24 hours when they have followed topics with unread posts -- this would also allow multiple notifications to be grouped in a single email. 

*longer term: might have some time to work on this in the next week or so (fingers crossed)

**Comment by wanqizhu** [comment]
@timdiggins That's exactly what I was envisioning! Do you know if there's a quick setting in the backend to default everything to "no notifications" while you guys figure out the preference settings? Thanks!

**Comment by timdiggins** [comment]
@wanqizhu you could try just monkey patching something... 

You could both stop follows from being created and prevent the email by monkeypatching   `Thredded::Post#autofollow_and_notify` with an empty method.

Monkey patching is a little tricky: you need to make sure the class is loaded first, then override the method. To make sure this works well in development with class reloading, do this in app/models/thredded/post.rb

```
require_dependency File.expand_path('../../app/models/thredded/post', Thredded::Engine.called_from)

module Thredded
  class Post # reopen
    def autofollow_and_notify
      #no-op
    end
  end
end
```

There might be a cleverer / better way to do this, but this style has worked for me reliably in both development and production

**Comment by wanqizhu** [comment]
Got it, thanks everyone for the help!
