### ISSUE TITLE
Error when trying to post

### ISSUE THREAD

**Issue by avitus** [thredded/thredded#341]
I'm using version 0.6.1 and Rails 4.2.6. 

In my development environment I'm seeing the following error when trying to create a new post:

> topic_form.: Uncaught TypeError: $nodes.find(...).autosize is not a function

It seems to be coming from topic_form: 32

`$nodes.find(this.textareaSelector).autosize();`

As far as I can tell, all the Thredded JS libraries are being loaded correctly but I might be mistaken. 

Has anyone else run into this?

**Comment by jayroh** [comment]
If you view the html source on the page that's exhibiting this error (in development env) does the autoresize plugin show up in the list of scripts being loaded?

**Comment by avitus** [comment]
@jayroh Yes, the script is definitely loading.

**Comment by avitus** [comment]
@jayroh I move the inclusion of Thredded earlier in the Javascript manifest and it solved the problem. My guess is that there is a missing semicolon somewhere in the Javascript tangle and the problem is not within Thredded.

**Comment by jayroh** [comment]
Ahhh ok well that's good to know, Andy.

Thanks for letting us know everything's all good :)
