### ISSUE TITLE
Search box cannot be use on main app

### ISSUE THREAD

**Issue by atussec** [thredded/thredded#346]
i wanted to use the thredded search function from the main app. after adding it am getting this error
undefined local variable or method `messageboard_or_nil'
how can i make it work?

**Comment by jayroh** [comment]
The absolute quickest hack is to just copy the rendered search html from
the thredded part of your app.

The more correct way is to create that method in your main
application_controller and return whatever messageboard it is you would
like to make the default for the search.

As an addendum to that last recommendation - there's a strong caveat there:
it depends on how many messageboards you have and if you're ok with picking
one and making it the default to search against.

**Comment by glebm** [comment]
You can just pass `messageboard: nil` to search in all messageboards.
So the code from your `main_app` would look like this:

```erb
<%= Thredded::ApplicationController.render(
      partial: 'thredded/search/form', locals: { messageboard: nil }) %>
```
