### ISSUE TITLE
Personalized home page/navigation for 'me' in Thredded

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded#347]
In the project we're working on with Thredded we need a personalized set of topic-list pages as an alternative to a listing of messageboards.

So for example a homepage with a top-level nav menu consisting of: 

* **Unread**: a list of unread topics (ordered by last post) across all messageboards
* **Following**: a list of followed topics (ordered by last post) across all messageboards
* **Posted**: a list of topics you've posted to (ordered by your last post) across all messageboards
* **All messageboards**: a list of messageboards (as present)
* **All topics**: a list of all topics (ordered by last post) across all messageboards

The first item in the list would be the home page.

I think this could be configurable, so to get the current presentation you'd just do:

```Thredded.top_level_navs = [:all_messageboards]```

But to get the full set you'd do:

```Thredded.top_level_navs = [:unread, :following, :posted, :all_topics, :all_messageboards]```

Which is the default configuration we can work out, depending on the answer to the next:

We are thinking that we could implement this as either a separate repo/plugin to Thredded (er, not sure what this might look like exactly, but am assuming something a new engine + sub namespace which you need to add as well as thredded. Maybe therefore the config above might be `Thredded::PersonalizedNavigation.navs = [:all_messageboards]`

Alternatively we could adopt within Thredded itself (given that the default configuration could be to have no change), but gut feel is that this is enough of a side-track from the main core of Thredded that it would be better separate.

Any thoughts @glebm @jayroh? Any pre-existing separate plugin repos which might indicate some testing / mounting / configuration options (would https://github.com/thredded/thredded-read_tracking indicate some "best practice"? even though I think that is destined for merger into thredded itself)

**Comment by jayroh** [comment]
Interesting, @timdiggins. I wonder if there's an even easier solution? I'm riffing here but ... what if we have a main/home "content" view partial that called out to the corners of Thredded that pulled the data and rendered as it saw fit. Something like

hypothetical `app/views/thredded/_home_content.html.erb`

```erb
<h1>Unread Topics</h1>
<%= render partial: 'home/topics',
  collection: Thredded:Scopes.unread_topics(thredded_current_user) %>

<h1>Followed Topics</h1>
<%= render partial: 'home/topics',
  collection: Thredded:Scopes.followed_topics(thredded_current_user) %>

<h1>All Messageboards</h1>
<%= render partial: 'home/messageboards',
  collection: Thredded:Scopes.messageboards(thredded_current_user) %>
```

**Comment by jayroh** [comment]
With those scopes I may also be abstracting prematurely too - They *could* just be the main model classes with their scopes

**Comment by timdiggins** [comment]
@jayroh cool for the implementation tips. But was also (primarily) interested in whether you thought this belongs in Thredded or a separate repo... (or indeed just in the main_app)

**Comment by jayroh** [comment]
I think if we went the composable path and structured everything
right(-ish) - it could be a la carte and more than happy living within the
main repo. :)

**Comment by timdiggins** [comment]
@jayroh excellent.

BTW I didn't pick up initially on your demo view. The idea was more for four new routes (in addition to the messageboards), each of which were showing just one of these options, and each to include the navigation.

The navigation can be the composable item however:

hypothetical app/views/thredded/home/_nav.html.erb
```
<ul id="home_nav">
  <li>
    <%= link_to "Unread Topics", Thredded.my_unread_topics_path %>
   </li>
  <li>
    <%= link_to "Posted Topics", Thredded.my_posted_topics_path %>
   </li>
... etc
</ul> 
```

The `Thredded.my_unread_topics_path` is pseudocode... not yet sure how to do that part

**Comment by jayroh** [comment]
AH! Ok - so that part was lost initially. I misunderstood!

I'll have to come back here after I've had a bit to digest it

**Comment by timdiggins** [comment]
FYI, I have started a fairly cronky implementation of this at https://github.com/red56/thredded-personalized-navigation.

**Comment by timdiggins** [comment]
Will repost separately about this when `Thredded Workgroup` (potential new name for thredded-personalized-navigation) is ready for prime time
