### ISSUE TITLE
PostGIS adapter support

### ISSUE THREAD

**Issue by paulmwatson** [thredded/thredded#349]
```Unsupported adapter PostGIS```

Are there any plans to support PostGIS? I will look into it but don't want to reinvent the wheel.

**Comment by jayroh** [comment]
Hmm. Curious what the use case would be. What are you thinking with regards to integrating PostGIS?

**Comment by paulmwatson** [comment]
Nothing interesting I'm afraid. We use the activerecord-postgis-adapter gem which means our entire Rails app thinks the db adapter is postgis rather than postgresql. So when thredded (or db_text_search) checks the adapter it sees postgis.

**Comment by glebm** [comment]
Closing here, as the work would need to be done in thredded/db_text_search.
