### ISSUE TITLE
How to provide mechanism for plugins/mainapps to override views

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded#357]
Wondering how best to provide a mechanism to customise views more effectively (it's an issue for both plugins and mainapps).

Was thinking about liquid as an option (but seems too un-railsy). However then saw: https://github.com/rwz/nestive.

Would be quite a large change. And perhaps a big abstraction barrier for users.
Thoughts / known best practices @glebm @jayroh

**Comment by glebm** [comment]
Also to consider: [Cells](https://github.com/apotonick/cells). Might solve this issue. Also provides a cleaner way to include bits of Thredded into the main app.

**Comment by timdiggins** [comment]
@glebm Cells looks interesting -- and in fact the whole of trailblazer looks good (hadn't seen this before now -- seems worth exploring). Have you ever used cells in production? trailblazer?

Just while I'm reflecting on this, Cells looks good for plugin authors. Seems like (possibly) a high bar for main-app users/customizers. But that's ok. What we need for main-app users is a gradient of customization: 
 1. drop in  as is 
 2. customize with initializer / layout
 3. override using view overrides / class overrides  (guided by readme docs)
 4. more complex / quasi plugin use (guided by some as yet unwritten plugin docs)

**Comment by glebm** [comment]
I haven't used Cells before nor Trailblazers.

So I read this Cells tutorial: https://www.sitepoint.com/introduction-to-cells-a-better-view-layer-for-rails/ and https://www.sitepoint.com/cells-a-deeper-look-into-dependency-injection-and-testing/ and it seems like there is a fair bit of magic in Cells as well. Unsure what the multi-get caching story is (which we currently benefit from in Rails 5). It is also not quite clear how hooks would be implemented.

Perhaps for v1 we could provide a zero-magic API like this:

```ruby
# Thredded code
class Thredded::ViewHooks
  def initialize(view_context)
    @view_context = view_context
  end

  module Default
    def post_form_content_area(&block)
      # no-op hook by default
      @view_context.capture(&block)
    end
  end
  include Default
  
  def self.configure(modules)
     # called once at setup
     modules.each(include module)
  end
end

# Expose a new configuration option of an array of view hook modules
Thredded.view_hooks = [Thredded::ViewHooks::Default]
```

```ruby
module Thredded::ApplicationHelpers
  def view_hooks
    @view_hooks ||= Thredded::ViewHooks.new(self)
  end
end
```

```ruby
# Thredded view
<%= view_hooks.post_form_content_area do %>
  <%= f.textarea '...' %>
<% end %>
```

In the plugin:

```ruby
module Thredded::MyPlugin::ViewHooks
  def post_form_content_area(&block)
    @view_context.safe_join([
      # e.g. render a partial before a hook
      @view_context.capture { render partial: 'my_partial', locals: {form: form} }
      super
    ], '')
  end
end

Thredded.view_hooks << Thredded::MyPlugin::ViewHooks
```

So the hooks can just run any ruby code and can run their rendering code within the context of Thredded if they want to (having access to all the view locals and instance variables). They can prepend, append, or replace the view entirely. 

The order in which hooks are applied is configurable via `Thredded.view_hooks`, so gems can do things like "insert this view hook before this other view hook if present", or even override the `Thredded.view_hook` method to ensure the hook is always applied first / last, e.g.:

```ruby
Thredded.send :include, Module.new do
  def self.view_hooks
    super + [ViewHooksThatMustBeLast]
  end
end
```

@timdiggins @jayroh What do you think?

**Comment by jayroh** [comment]
When I think about something like this I care less about the implementation than I do the interface. In this case I really like how this looks

```ruby
# Thredded view
<%= view_hooks.post_form_content_area do %>
  <%= f.textarea '...' %>
<% end %>
```

With regards to configuration, however, I would prefer seeing a run-down of plugins being catalogued in the initializer itself. Let the plugins implement the API, and let people order the view hook "middleware" in one place. Maybe something in `config/thredded.rb` like:

```ruby
Thredded.view_hooks = [
  Thredded::ViewHook::MarkdownHeader,
  Thredded::ViewHook::FileUploadBar,
  MyOwnApp::ViewHook::EmojiSelector,
  MyOwnApp::ViewHook::ImageLibrary,
]
```

We'd probably have to account for prepending / appending / surrounding the sections too, right?

**Comment by timdiggins** [comment]
I think either one (defined in plugin, defined in initializer) may work -- but I actually think that the implementation really matters and issues like load / execution order may become important in non trivial cases.

One more thought: There is often more to plugins than simple view hook additions (routing, controllers, models, assets) which may well involve some other kinds of overriding and monkey patching till we find a better way of enabling this. As we enable new hooks (in the future, not yet), we don't want to have to push on main_app implementors the work of configuring each of the component parts for each of the plugins in Thredded.

With this in mind, maybe it would be good to discourage the model where the main_app implementor writes `Thredded.view_hooks = [...]` as this would then totally preclude plugin implementation. It might be better to have `Thredded.view_hooks <<`. Would it be possible for view_hooks to be a custom object which exposes `append(*hook_classes)` and  `prepend(*hook_classes)` and `replace(*hook_classes)`. Everything is possible then... 

As a side note it would be useful for main_app implementors to be able to determine the load order of plugins.  Could this just be the order of require statements in the thredded initializer? Or something more complex?

**Comment by timdiggins** [comment]
I realize I didn't really reply to the intial proposal @glebm : I think the explicitness in your proposal is good. The drawback is that it's harder work for main_app implementors. Does your proposal avoid the caching caveats that both nestive and cells have? (that's a major bonus). I can see the benefit of allowing "any ruby code" but this does mean that plugins are less likely to play nicely with each other. I wonder if we provide and encourage the use of ContentArea#before / #after / #replace (without precluding use of any ruby) it might be cleaner in the future.

More questions -- about the implementation:

1) about
```
    def post_form_content_area(&block)
      # no-op hook by default
      @view_context.capture(&block)
    end
``` I'm assuming that by "post_form_content_area" we're talking about the  content area for the Post form? (not pre-form / post-form). 

I'm wondering if there's a possibility for naming / namespacing slightly more elegantly -- aren't these all content_areas? in which case they could be ...Default.post_form, or maybe ...Default::PostForm#content_area, meaning that you'd need a ...Default#configure command to set up all the content areas.

2)

```
# Expose a new configuration option of an array of view hook modules
Thredded.view_hooks = [Thredded::ViewHooks::Default]
```

 I find it a bit confusing that you can override the default behaviour by either removing it from the view_hook list or just not calling super. I'm assuming it would be very unusualto remove the Default from the view_hook list.

3) thinking about ContentArea#before above -- I'd rewrite your simple example as:

```
  module Default
    def post_form_content_area(content_area, &block)
      # no-op hook by default
      content_area.capture(&block) # content_area is a wrapper for view_context, which is passed in to make it cleaner to implement
    end
    # all the other hooks here with no-op impls
  end
```

```
module Thredded::MyPlugin::ViewHooks
  def post_form_content_area(content_area, &block)
    content_area.before{ render partial: 'my_partial', locals: {form: form} }
    # automatically calls the previous one in the chain
  end
end
```
I recognize this is a bit more complex. (it might then mean that we need to move from using Modules to instantiating classes and calling each of them in a chain) -- but I think making it easier to do the default action is much less likely to get plugin writer errors. Additionally an explicit order that is independent of method-resolution order seems more flexible for the future and more robust. Plus I think it's easier to test independently and trace plugin conflict problems.

**Comment by jayroh** [comment]
> but I actually think that the implementation really matters and issues like load / execution order may become important in non trivial cases.

Completely agree that implementation matters. Of course it does. My statement was more along the lines of - "let's think about how we want people to use this, and then we'll go down the road of figuring out how it will work". In any case - I don't want to split hairs on that.

**Comment by jayroh** [comment]
> One more thought: There is often more to plugins than simple view hook additions (routing, controllers, models, assets) which may well involve some other kinds of overriding and monkey patching till we find a better way of enabling this. As we enable new hooks (in the future, not yet), we don't want to have to push on main_app implementors the work of configuring each of the component parts for each of the plugins in Thredded.
> 
> With this in mind, maybe it would be good to discourage the model where the main_app implementor writes Thredded.view_hooks = [...] as this would then totally preclude plugin implementation. It might be better to have Thredded.view_hooks <<. Would it be possible for view_hooks to be a custom object which exposes append(*hook_classes) and prepend(*hook_classes) and replace(*hook_classes).

I don't think I understand what you mean by `Thredded.view_hooks = [...]` would preclude plugin implementation. Could you give an example?

My thought is that allowing the explicit definition of (for now - just) the view plugin "middleware" would give people the explicit control over what they include in their app.  EG:

> Add the `thredded-markdown_posts` gem and place `Thredded::ViewHook::MarkdownPosts` into the `Thredded.view_hooks` array in the initializer.

I, personally, prefer knowing what's in there up front, instead of that being something defined in an external gem I pull in. I understand that would be easier (probably), but at the same time would be hiding some valuable information.

Conversely, at that point a rake task like `rake thredded:plugins:views` to list them out, a la `rake middleware` would be useful.

I could be convinced either way, for sure, but I would love to further understand your reasoning behind it, Tim.

**Comment by timdiggins** [comment]
I think our difference comes from weighing control/power against convenience  (for main app implementator).

But on reflection I don't really have that strong a point of view on any of this and think it's good to let things get started and see how it pans out.
