### ISSUE TITLE
when a post is added to a topic should update messageboard_last_topic

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded#358]
Currently messageboards' updated_at only reflect topics that have been added or deleted. So if you're looking at a list of messageboards then they are in order of most recent topic addition, rather than most recent activity. The "last updated at"  is quite confusing for users in some apps.

I'd propose that when a post is added to a topic we call `Topic update_messageboard_last_topic` as well as calling update_parent_last_user_and_timestamp.

Is there a strong argument for the current behaviour, for existing mainapps for example?

In terms of implementation, could do this in an after_commit, or in an after_action in the posts_contoller.

**Comment by glebm** [comment]
I believe this was fixed by https://github.com/thredded/thredded/commit/9938daae8294f1617516c524f6897210b9458c7e

**Comment by timdiggins** [comment]
@glebm I'm pretty sure that commit won't do it, because it uses `update_column` rather than `update_attribute`, so goes straight to db and skips callbacks and updated_at.

I can write a model test for `messageboard.update_last_topic!` and then just change from update_column to update_attribute unless you had a strong reason for using `update_column`

**Comment by timdiggins** [comment]
PS: elsewhere in the code `update_columns` is used with an explicit update to updated_at, but this is mostly to cater for the fact that updated_at in topics and posts is used as a proxy for time written / readed-ness (side note: I'm not very keen on this, and would prefer an explicit field (`last_written_at` ?)for this, and keep updated_at to mean... updated at, so a topic which has a post deleted changes last_written_at to go back to the final post, but the updated_at is when the post was removed). 

However we have no use for this "written at" check in messageboards, and instead people really want to know... when was this messageboard last updated, whatever kind of change it was, I think.

**Comment by timdiggins** [comment]
In order for the messageboard index view to make sense in the case where a post has been deleted, I think the messageboard's updated_at should be the same as the topic's updated_at 

(and if we were going to have a `written_at` or `last_written_at` it should apply to messageboards too)
