### ISSUE TITLE
Posts and PrivatePosts should be ordered by created_at not by id

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded#360]
Currently posts & private posts when `order_oldest_first` / `order_newest_first` are actually (under the hood) ordered by id.

This seems appealing in some ways, but it is a bit of a nightmare. In particular if the creation order is screwed up (e.g. by importing) then you have problems. It also just feels wrong to me -- and it was deeply surprising when I found out.

I have started changing this behaviour to be ordered by `created_at`

Of course changing this is quite a bit of work, as much test data currently relies on this, and some untested behaviours (e.g. `Post` / `PrivatePost` `#page()`) 

However, I've also discovered that there are one or two places where some desired behaviours rely on a natural id-ordering (rather than explicit call to `order_oldest_first`) which is not dependable (at least in postgres).

- [x] change ordering
- [x] deal with spec failures (including the read-state spec mentioned in #352)
- [x] add in default `order_oldest_first` for the associations in `Topic` and `PrivateTopic`
- [x] write spec for and change `#page` for both `Post` and `PrivatePost`
- [x] dry up `#page` by extracting to either PostCommon or PageCalculable

**Comment by timdiggins** [comment]
FYI: Having looked through the usages of `.posts`, none are actually reordering the posts, and many are relying on the id-order. I think we should change the default order of the `associations` (not the model) to be `order_oldest_first`. this can be overridden with `.reorder()`. This may be a controversial choice!

**Comment by glebm** [comment]
:+1: 

Default order on associations is probably OK, though I'd prefer no default order on them at all.

**Comment by timdiggins** [comment]
@glebm I get your reluctance for lack of default order, but it seemed a bit repititive to add the order to every single place we are using .posts...
