### ISSUE TITLE
Disable Automatic Subscription When Posting

### ISSUE THREAD

**Issue by avitus** [thredded/thredded#372]
Is it possible to disable the automatic subscription (auto-follow) when posting to a topic? I would prefer users to have to opt-in to following a topic via email.

**Comment by glebm** [comment]
There is currently no way to do this, but a PR adding this as a configuration option is welcome.

The following on posting to a topic happens here: https://github.com/thredded/thredded/blob/master/app/models/thredded/post.rb#L59

**Comment by midhunkrishna** [comment]
Anyone working on this?

**Comment by jayroh** [comment]
As of right now, no. I don't believe so.

**Comment by timdiggins** [comment]
@avitus @midhunkrishna Just to clarify a little:

"Follow a topic"  is separate from "Notify with an email when I'm following".

There **IS** a per-user preference to turn off "auto follow when I'm mentioned" but no preference for "auto follow when I post" (nor auto-follow when I create topic), and there is no Engine/Application-level way of turning this off (nor a way to default users' preferences to false).

@EllaNancyFay and I are working on a scheme for configurable notification (notify me by email / slack / pushover / whatever) via plugins, and this may well include the option to turn off notification being on by default (at the Engine/application level)

But no one is working on the Follow preferences/configurations.

**Comment by glebm** [comment]
@avitus Until this becomes a configuration option, you can monkeypatch [Thredded::Post#auto_follow_and_notify](https://github.com/thredded/thredded/blob/cdb9f4537716929b3f66624338ca42ccf4f0f0d2/app/models/thredded/post.rb#L54-L60) like this in the Thredded initializer:

```ruby
Rails.application.config.to_prepare do
  Thredded::Post.class_eval do
    def auto_follow_and_notify
      return unless user
      AutoFollowAndNotifyJob.perform_later(id)
    end
  end
end
```
