### ISSUE TITLE
PG::DuplicateTable: ERROR:  relation "thredded_categories_name_ci" already exists

### ISSUE THREAD

**Issue by PirunSeng** [thredded/thredded#376]
I am unable to rollback the migration because of this error.
I think it happens because of the indexing columns.
`DbTextSearch::CaseInsensitive.add_index connection, :thredded_categories, :name, name: :thredded_categories_name_ci`

All other indexing column cause its own error like this issue.
`DbTextSearch::FullText.add_index connection, :thredded_posts, :content, name: :thredded_posts_content_fts`
`DbTextSearch::FullText.add_index connection, :thredded_topics, :title, name: :thredded_topics_title_fts`
`DbTextSearch::CaseInsensitive.add_index connection, Thredded.user_class.table_name, Thredded.user_name_column, unique: true`

Any idea would be helpful.
Thanks,

**Comment by glebm** [comment]
Unfortunately, these cannot be rolled back yet. You can try commenting out these lines before running the rollback. This should work because the indices will be deleted because the tables they reference get deleted.

**Comment by PirunSeng** [comment]
Oh, I see.
Rollback successfully by commenting out those indexing column.
Thanks,

**Comment by lulalala** [comment]
`friendly_id_slugs` table is not rolled back, due to the if condition. When rolling back, comment out the if statement as well.
