### ISSUE TITLE
Question about a feature

### ISSUE THREAD

**Issue by ecroow** [thredded/thredded#380]
Hello!

I have a question about a feature I want to build for my forum, but I have no idea how I'd do it.

Here's what I'd like to do.

When a user signs up, he's automatically assigned Messageboard Group.
 a) If the group has less than 5 people in it, he'll join it.
 b) if it has more than 5 people, a Message Group 2 is created, and he joins it.

Thanks in advance.

**Comment by jayroh** [comment]
Since you have the ultimate control of the user objects' creation, you can do all of this within a dedicated "service", "command", or background job that does the work.

You practically have all the code written already in your comment :). That's already your pseudo-code, right?

In your parent app you have access to all `Thredded` namespaced classes and objects so there's no restriction with what you can or want to do.

**Comment by ecroow** [comment]
Okay, so I've started working on it, but I can't find one thing that I need.

I decided that I was going to use an "after action :assigning" in User model.

But I can't find where it says anything about the size of the group. (https://github.com/thredded/thredded/blob/master/app/controllers/thredded/messageboard_groups_controller.rb)

How would I get how many members are in the group.

Also, I have to get that number from that previous group.

Would I use the ".last" method?

**Comment by glebm** [comment]
Thredded doesn't have a concept of group members. A MessageboardGroup is a group of messageboards. So if you want messageboard groups to have members, you would need to write that yourself.

**Comment by ecroow** [comment]
Okay, I decided to go with private threads instead of Groups. 

The question is how do I count the users in a private thread?

And also, how do I tell it to create that private thread in the messageboard I want it to?

Thank you!

**Comment by timdiggins** [comment]
The two options in Thredded are PrivateTopic (which is a linear thread of private posts visible only to the PrivateTopic's users) and Topic (which is a linear thread of posts -- there is no concept of having users, but users can follow/unfollow topics) 

Both PrivateTopic and Topic have the concept of the creator (`belongs_to :user`) user, the user who started the PrivateTopic/Topic. You might want to make that a system user of some kind.

Topics are owned by a (by default public, but you could customize this in your app) messageboard, but PrivateTopics do not (they are private to the users who are included in it).

**Comment by ecroow** [comment]
Thank you Timdiggins!

My questions was how to count the users who are included in that private topic, and how to make it so that I create it in a specific messageboard. (For an example, I have Messageboard 1 and Messageboard 2. I want the new private threads to be created in Messageboard 1)

**Comment by glebm** [comment]
@ecroow Such questions are best suited to StackOverflow, though a beginner-level ActiveRecord tutorial should clear things up for you.

* http://guides.rubyonrails.org/active_record_basics.html
* http://guides.rubyonrails.org/association_basics.html
* http://guides.rubyonrails.org/active_record_querying.html
