### ISSUE TITLE
Docker installation problem

### ISSUE THREAD

**Issue by Seaborg** [thredded/thredded#388]
Checked on MacOS and Ubuntu 14.04, the same issue

fatal: Not a git repository (or any of the parent directories): .git

[!] There was an error parsing `Gemfile`:
[!] There was an error parsing `shared.gemfile`: No such file or directory @ rb_sysopen - /tmp/shared.gemfile. Bundler cannot continue.
. Bundler cannot continue.

 #  from /tmp/Gemfile:13
 #  -------------------------------------------
 #
 >  eval_gemfile File.expand_path('shared.gemfile', File.dirname(__FILE__))
 #  -------------------------------------------
ERROR: Service 'web' failed to build: The command '/bin/sh -c bundle install' returned a non-zero code: 4

**Comment by jayroh** [comment]
What command did you run to get this error to happen, and from what
directory?

Want to make sure we can replicate the issue as closely as possible

**Comment by Seaborg** [comment]
dockers-compose build

**Comment by glebm** [comment]
@Seaborg Does it work if you add `ADD shared.gemfile /tmp/` to the Dockerfile?

**Comment by Seaborg** [comment]
Yeah, bundler is running now.
BTW got this one on the way:
Step 9 : RUN bundle install
 ---> Running in 97fada48f39d
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
**fatal: Not a git repository (or any of the parent directories): .git**
