### ISSUE TITLE
Docker installation problem

### ISSUE THREAD

**Issue by Seaborg** [thredded/thredded#389]
I get this error when trying:
docker-compose up -d

WARNING: The THREDDED_DB_1_PORT_5432_TCP_ADDR variable is not set. Defaulting to a blank string.
WARNING: The THREDDED_DB_1_PORT_5432_TCP_PORT variable is not set. Defaulting to a blank string.
Attaching to thredded_web_1, thredded_db_1
web_1  | Usage: script/wait-for-tcp ADDRESS PORT
web_1  | Wait for TCP connection at ADDRESS:PORT, retrying every 3 seconds, maximum 20 times.
web_1  | fatal: Not a git repository (or any of the parent directories): .git
web_1  | rake aborted!
web_1  | LoadError: cannot load such file -- thredded
web_1  | /thredded/spec/dummy/config/application.rb:13:in `require'
web_1  | /thredded/spec/dummy/config/application.rb:13:in `<top (required)>'
web_1  | /thredded/spec/dummy/Rakefile:5:in `require'
web_1  | /thredded/spec/dummy/Rakefile:5:in `<top (required)>'
web_1  | /usr/local/bundle/gems/railties-5.0.0.1/lib/rails/tasks/engine.rake:3:in `load'
web_1  | /usr/local/bundle/gems/railties-5.0.0.1/lib/rails/tasks/engine.rake:3:in `block (2 levels) in <top (required)>'
web_1  | /usr/local/bundle/gems/railties-5.0.0.1/lib/rails/tasks/engine.rake:2:in `block in <top (required)>'
web_1  | /usr/local/bundle/gems/railties-5.0.0.1/lib/rails/tasks/engine.rake:72:in `<top (required)>'
web_1  | /thredded/rakefile:25:in `load'
web_1  | /thredded/rakefile:25:in `<top (required)>'
web_1  | /usr/local/bundle/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
web_1  | Tasks: TOP => load_app
web_1  | (See full trace by running task with --trace)
db_1   | The files belonging to this database system will be owned by user "postgres".
db_1   | This user must also own the server process.
db_1   |
db_1   | The database cluster will be initialized with locale "en_US.utf8".
db_1   | The default database encoding has accordingly been set to "UTF8".
db_1   | The default text search configuration will be set to "english".
db_1   |
db_1   | Data page checksums are disabled.
db_1   |
db_1   | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db_1   | creating subdirectories ... ok
db_1   | selecting default max_connections ... 100
db_1   | selecting default shared_buffers ... 128MB
db_1   | selecting dynamic shared memory implementation ... posix
db_1   | creating configuration files ... ok
db_1   | creating template1 database in /var/lib/postgresql/data/base/1 ... ok
db_1   | initializing pg_authid ... ok
db_1   | initializing dependencies ... ok
db_1   | creating system views ... ok
db_1   | loading system objects' descriptions ... ok
db_1   | creating collations ... ok
db_1   | creating conversions ... ok
db_1   | creating dictionaries ... ok
db_1   | setting privileges on built-in objects ... ok
db_1   | creating information schema ... ok
db_1   | loading PL/pgSQL server-side language ... ok
db_1   | vacuuming database template1 ... ok
db_1   | copying template1 to template0 ... ok
db_1   | copying template1 to postgres ... ok
db_1   | syncing data to disk ... ok
db_1   |
db_1   | Success. You can now start the database server using:
db_1   |
db_1   |     postgres -D /var/lib/postgresql/data
db_1   | or
db_1   |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db_1   |
db_1   |
db_1   | WARNING: enabling "trust" authentication for local connections
db_1   | You can change this by editing pg_hba.conf or using the option -A, or
db_1   | --auth-local and --auth-host, the next time you run initdb.
db_1   | ****************************************************
db_1   | WARNING: No password has been set for the database.
db_1   |          This will allow anyone with access to the
db_1   |          Postgres port to access your database. In
db_1   |          Docker's default configuration, this is
db_1   |          effectively any other container on the same
db_1   |          system.
db_1   |
db_1   |          Use "-e POSTGRES_PASSWORD=password" to set
db_1   |          it in "docker run".
db_1   | ****************************************************
db_1   | waiting for server to start....LOG:  database system was shut down at 2016-08-24 18:23:36 UTC
db_1   | LOG:  MultiXact member wraparound protections are now enabled
db_1   | LOG:  database system is ready to accept connections
db_1   | LOG:  autovacuum launcher started
db_1   |  done
db_1   | server started
db_1   | CREATE DATABASE
db_1   |
db_1   | CREATE ROLE
db_1   |
db_1   |
db_1   | /docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db_1   |
db_1   | LOG:  received fast shutdown request
db_1   | LOG:  aborting any active transactions
db_1   | LOG:  autovacuum launcher shutting down
db_1   | LOG:  shutting down
db_1   | waiting for server to shut down....LOG:  database system is shut down
db_1   |  done
db_1   | server stopped
db_1   |
db_1   | PostgreSQL init process complete; ready for start up.
db_1   |
db_1   | LOG:  database system was shut down at 2016-08-24 18:23:38 UTC
db_1   | LOG:  MultiXact member wraparound protections are now enabled
db_1   | LOG:  database system is ready to accept connections
db_1   | LOG:  autovacuum launcher started
db_1   | LOG:  database system was interrupted; last known up at 2016-08-24 18:23:39 UTC
db_1   | LOG:  database system was not properly shut down; automatic recovery in progress
db_1   | LOG:  record with zero length at 0/16A8A98
db_1   | LOG:  redo is not required
db_1   | LOG:  MultiXact member wraparound protections are now enabled
db_1   | LOG:  database system is ready to accept connections
db_1   | LOG:  autovacuum launcher started

**Comment by glebm** [comment]
@Seaborg this should be fixed by https://github.com/thredded/thredded/commit/31867ccddd72ed438257611ec2c8f1f9a3c00508
