### ISSUE TITLE
Add user_id to messageboards

### ISSUE THREAD

**Issue by jaxn** [thredded/thredded#396]
If `thredded_messageboards` included the `user_id` of the user who created the message board, it would easily allow much more powerful user permissions in `User.thredded_can_read_messageboards` and `User.thredded_can_write_messageboards`.

An example would be only showing message boards that were created by someone in the same company as the user.

```ruby
class User < ActiveRecord::Base

  belongs_to :company

  # @return [ActiveRecord::Relation<Thredded::Messageboard>] created by co-workers
  def thredded_can_read_messageboards
    Thredded::Messageboard.find_by( user_id: self.company.user_ids )
  end
end
```

**Comment by glebm** [comment]
This seems to belong in your code / a plugin, not in the core.
