### ISSUE TITLE
UserTopicReadState.touch! should only update to the mentioned post's created_at

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded#408]
`UserTopicReadState.touch!` updates the read at of the read state to equal `Post#updated_at`. However this could result in some posts being erroneously overlooked because  posts are sorted (and paginated) by created_at, then this will make it look like a later post is read (when looking at pages and pages of posts, some of which have been edited more recently).

This is clearly an edge case, but easy to fix (once #405 is done)

**Comment by glebm** [comment]
@timdiggins Looks like this was fixed in v0.7.0?

**Comment by timdiggins** [comment]
@glebm no I don't think so:

```state.update!(read_at: post.updated_at, page: post_page)```
should become 
```state.update!(read_at: post.created_at, page: post_page)```

Have created PR to fix, will merge later unless negative feedback
