### ISSUE TITLE
Adding links to nav bar

### ISSUE THREAD

**Issue by balakarthik** [thredded/thredded#414]
I have implemented a forum as a separate feature to my application, when i  get into the forum there are not link to get back to my application, i need to provide a additional link to redirect to some other features of my application. Is there any way to overwrite the current navigation bar to add some other links.

**Comment by jayroh** [comment]
@balakarthik sure - you can override this view in your own application's view path: `https://github.com/thredded/thredded/blob/master/app/views/thredded/shared/_nav.html.erb`

Another solution might be to provide the link(s) you need in your application layout and leave the thredded navigation alone?

Up to you how you want to proceed.
