### ISSUE TITLE
Can we embed the thredded gem within the existing application?

### ISSUE THREAD

**Issue by kumaraswins** [thredded/thredded#424]
Currently is opening as separate page,  is there any method to open within the same application ? Any other workaround for changing the css of the thredded gem

**Comment by jayroh** [comment]
It CAN be embedded within your application, of course. And the CSS can be
overridden in several ways

If you'd like to keep the general layout and structure, define and override
the SCSS variables before you include the Thredded partial in your
application css file

Or do not include all of the Thredded scans partials and define everything
yourself on your own

**Comment by glebm** [comment]
@kumaraswins Perhaps the Application Layout section of the Readme is what you're looking for?

https://github.com/thredded/thredded/blob/master/README.md#application-layout

**Comment by FumbleBe** [comment]
Hi guys, I would like to do the same think, but I don't understand the layout thinks in the documentation :/

I have a application, working well, in this application, I have a link to /forum. This, load Thredded, and this is nice, but I would like thredded to be "frame" in my main application. Is there a way to achieve that "easily" ? Do you need more informations? like my routes.rb file or something ?

Thank you !
