### ISSUE TITLE
Encourage people to share they're using thredded

### ISSUE THREAD

**Issue by jayroh** [thredded/thredded#428]
I find this is something the project has had very little luck with - and that's nudging people towards sharing that they're using thredded for their websites. I have a feeling there are more than several production deployments out there but ... we hear nothing about them.

One of the first things people do when they seed the database, or create a new messageboard, is see the first sample topic. What about updating that copy to link to the twitter account, link to the thredded team email ("let us know how you're using thredded"), maybe link to the issue tracker, etc.

What do you think?

**Comment by glebm** [comment]
I've added some text there that can be improved in the future. Getting ready to release v0.8.0!
