### ISSUE TITLE
root_path in apps navbar changed to /forum/

### ISSUE THREAD

**Issue by ryanbelke** [thredded/thredded#430]
When I visit myapp.com/forum, using my applications layout which renders a navbar at the top of all the pages the root_path links in the navbar have all changed to messageboard_path effectively myapp.com/forum not letting me navigate back to the apps root path (/). Any idea how to correct this? When first launching the app, the navbar routes are correct in being root_path, only after I visit /forum do they change.

**Comment by glebm** [comment]
@ryanbelke Please use `main_app.root_path` instead. 

Related: https://github.com/thredded/thredded/issues/296

**Comment by ryanbelke** [comment]
thank you that worked
