### ISSUE TITLE
Customizable Notifiers

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded#441]
* as an app owner, be able to add and customize extra notifiers for immediate notification (e.g. Slack, Pushover, your own app) 
* as a user, be able to opt out of given notifiers (see below)
* as a developer, be able to write a gem for new notification channel

<img width="743" alt="notification_settings___thredded_demo" src="https://cloud.githubusercontent.com/assets/18395/19848551/0ed506e8-9f46-11e6-9fbe-9be8c4a32fd7.png">

**Comment by timdiggins** [comment]
@glebm @jayroh I have a PR which I'll push for comment 1 & 2 , working on a plugin to allow push notifications via https://pushover.net/ -- will work on this at https://github.com/red56/thredded-pushover-notifier (unless / until you create a thredded/thredded-pushover-notifier)

**Comment by glebm** [comment]
@timdiggins I've added you to the owners group of the Thredded org, so you should be able to create repos now :+1:

**Comment by timdiggins** [comment]
@glebm Fab thanks. Just have to find the energy to extract the plugin, which is about 50 lines of code -- it's how to test it reliably against changing varieties of thredded that is the problem. Do you have any opinions on how thredded could provide testing support for plugins -- would be nice to reuse factories and even the dummy app. But I can't quite work out how it's possible. 

(It would also be great if one could run all the thredded tests on your embedded thredded in your main_app, but I think that might be over-ambitious)

**Comment by jayroh** [comment]
I think it's relatively possible to require and include the factories.
Probably needs a little ingenuity - but we can figure that out.

As for the dummy app - that's a great question. The plugin would need to
customise it though, correct? Hrmm. Generating a new dummy app in the
plugin would defeat the purpose of testing against <version of choice>.
This might end up calling for using something like the appraisal gem to
test across several versions and branches, generating and customising
thredded dummies per version
