### ISSUE TITLE
Mention Autocompletion styles should play nice with Bootstrap

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded#453]
When main app uses application layout, and this includes bootstrap (e.g. for global navbar), then the autocomplete has extra I think padding and active-blue colour clashes:

In Thredded:
![it_s_not_impossible__i_used_to_bullseye_womp_rats_in_my_t-16_back_home__they_re_not_much_bigger_than_two_meters____thredded_demo](https://cloud.githubusercontent.com/assets/18395/20003822/6b5ab1dc-a280-11e6-861e-ce6b81dc4492.png)

With Bootrap:

![local___general](https://cloud.githubusercontent.com/assets/18395/20003784/370bafd0-a280-11e6-8822-db165f62bf1c.png)

This is because the (unconfigurable AFAICT) classes in jquery-textcomplete are set up to work OOTB with bootstrap. 
https://github.com/yuku-t/jquery-textcomplete/blob/56cc8fc30c1d1189b33f499a973fd3c314c2492c/doc/style.md

**Comment by glebm** [comment]
Hopefully the commit above fixed it!

**Comment by timdiggins** [comment]
@glebm OMG how did I not spot that (I wrote that myself this week). Anyway needs one more thing to get the cascade right for bootstrap. will add in a PR
