### ISSUE TITLE
Remove BBcode?

### ISSUE THREAD

**Issue by jayroh** [thredded/thredded#460]
Thoughts on removing bbcode support? ➕ / ➖ ?

Markdown has won that front and BBcode something I rare, if ever actually, see.

Plus, there are tools that help migrate [from bbcode to markdown]. What do you think?

[from bbcode to markdown]: https://github.com/rikkit/ruby-bbcode-to-md

**Comment by glebm** [comment]
Perhaps we can move it to a plugin!

**Comment by glebm** [comment]
Extracted BBCode into a plugin! https://github.com/thredded/thredded-bbcode

**Comment by jayroh** [comment]
GLEB GO TO SLEEP, YOU ANIMAL

😝

**Comment by glebm** [comment]
@jayroh I have a temporary buff, DOUBLE JETLAG. Of the last 30 days, I was in Japan for two weeks, then in London for a week, and in San Francisco for a week. Just got back to London last night :)

**Comment by jayroh** [comment]
Jeeez man you probably need a few days to catch up (with sleep). I hope
you're feeling back to normal soon :)
