### ISSUE TITLE
do we need to check compat on  jQuery2->3?

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded#465]
Just want to check that we're ok with main_apps that are using jquery 2 even with application layout that is (necessarily or inadvertently) loading jquery2 with thredded

**Comment by timdiggins** [comment]
REF: https://github.com/thredded/thredded/commit/8e7e1d399a35006b03630ff18e484fd66620f9f9#commitcomment-19721231

**Comment by glebm** [comment]
Checking whether two different jQuery versions are loaded would be great but I don't know how it can be done.

Perhaps we can add a `thredded/dependencies/jquery.js` file with a single require:

```js
//= require jquery3
```

Then the user would be able to change the jQuery version that Thredded requires by overriding that file in their main_app. This way they won't have to fiddle with a custom thredded/dependencies file.

**Comment by timdiggins** [comment]
@glebm yes much easier to understand and explain:

To use thredded with application layout, you need to ensure that your layout and thredded don't load different jquery versions. By default jquery loads jquery3, but if you want to use jquery v2, then you just need to create a file `app/assets/thredded/dependencies/jquery.js` which contains just ```//= require jquery```. If you are not loading jquery in your main_app, then you don't need to worry.

**Comment by glebm** [comment]
@timdiggins Thanks, docs change merged! 

I have not figured out a way to auto-detect and warn about two different versions being loaded, so closing this for now.
