### ISSUE TITLE
Preventing all access to anonymous users?

### ISSUE THREAD

**Issue by zapnap** [thredded/thredded#470]
Doesn't seem like an uncommon situation for a wholly private installation but isn't addressed in the README. I can think of several hacky ways to accomplish this but I'm trying to determine the 'right' way to do it in thredded. Will overriding methods on NullUser cover all of the bases? For example, preventing access to the messageboards index? Thanks for the great work and appreciate any advice.

**Comment by glebm** [comment]
You could add a `before_action` to `Thredded::ApplicationController`, e.g., in `config/initializers/thredded.rb`:

```ruby
Rails.application.config.to_prepare do
  Thredded::ApplicationController.module_eval do
    before_action :thredded_require_login!
  end
end

**Comment by zapnap** [comment]
Perfect. Thanks!

**Comment by jayroh** [comment]
@zapnap nice to see you giving this a shot, dude. :)

**Comment by zapnap** [comment]
Looks awesome @jayroh nice work!

**Comment by ciel** [comment]
I'm having a lot of trouble getting this to work. It seems that `:thredded_require_login!` doesn't really do anything.

**Comment by glebm** [comment]
Yes, that should work. Did you restart the server after adding that code? Do you have any other modifications related to authentication?

**Comment by FumbleBe** [comment]
Mmmh doesn't work either... didn't do anything special with authentication expect that it is handle by my main application...

**Comment by mewth** [comment]
I also added the same code and doesn't do anything...

**Comment by timdiggins** [comment]
Anyone encountering a problem getting thredded_require_login! to work as expected, please note that if you are on Rails 4.2 there is a necessary workaround:  (see https://github.com/thredded/thredded/pull/743/files or https://github.com/thredded/thredded/blob/master/README.md#requiring-authentication-to-access-thredded)

**Comment by sachaandre** [comment]
Hi !
I'm on Rails 5.2.3 and tried the code in the README.
It appears I still can access the forum without being logged...

The code I put came from here : https://github.com/thredded/thredded/blob/master/README.md#requiring-authentication-to-access-thredded
And I put it in my Initializers. What have I done wrong ?
