### ISSUE TITLE
uninitialized constant Thredded

### ISSUE THREAD

**Issue by mezzodrinker** [thredded/thredded#472]
Greetings Thredded team,

I recently decided to check out Thredded on my webserver. I did all the installation steps that have been provided [here](http://www.rubydoc.info/gems/thredded#Installation). In particular, I did:

* add the gem `thredded` to the Gemfile
* generate the Thredded initializer
* copy the Emoji to `public/emoji`
* generate an User model and adjust `config/initializers/thredded.rb` accordingly
* copy the migrations and run them
* mount the engine in `config/routes.rb`

Now, whenever I try to access the forum page, the website shows me the error message "uninitialized constant Thredded" and lists the line in which I added Thredded to `config/routes.rb` as the source of the error. What is the cause of this and how can I get rid of it?

I am running an nginx server with Phusion Passenger, Ruby 2.3.0 and Ruby on Rails 5.0.0.1. If you need any further information, I'll gladly provide it.

Kind regards.

**Comment by glebm** [comment]
Hi, sounds like you need to restart the web server!

**Comment by mezzodrinker** [comment]
@glebm Sure does. And it helped. Thanks for the heads up.

Now I'm just running into an error because I apparently didn't configure Thredded completely. But I should be able to cope with that :)

**Comment by glebm** [comment]
@mezzodrinker Heads up, I'm about to release Thredded v0.8.0 which has a number of cool new features but also some minor backwards-incompatible changes. You might want to wait until it's released.

Also, if you're adding Thredded to a new Rails app (and not adding it to the existing one), you'll be able to use the new app generator once v0.8.0 is out.

**Comment by glebm** [comment]
Released!

**Comment by mezzodrinker** [comment]
Thank you!
