### ISSUE TITLE
Participant display in private topics

### ISSUE THREAD

**Issue by zapnap** [thredded/thredded#477]
When initially creating a new private topic, the `last_user` is always the current user, so when viewing the private topics list, you see your name next to the new topic rather than the recipient name. This makes sense for the normal public boards, but is confusing UX on the private topics. In fact, there's no way to even see who you sent a private message to when clicking through (unless they respond).

I suppose the easiest way to sort this would be to switch the updated-by link text to be a comma-separated list of all the users associated with the topic (sans the current user), but without any differences in visual styling this would break from the familiar styling used elsewhere... It may be worth presenting a different style here, or maybe two-stepping it so at least it isn't confusing in the short term. The looking at a specific private topic item there should also be some indication of participants.

Happy to make these changes but wanted to discuss before sending a PR. Thoughts?

**Comment by zapnap** [comment]
See https://github.com/zapnap/thredded/tree/private-message-participants for a quick pass at this. Look good?

**Comment by glebm** [comment]
:+1: 

> I suppose the easiest way to sort this would be to switch the updated-by link text to be a comma-separated list of all the users associated with the topic (sans the current user)

This makes it impossible to see who replied last. Perhaps the solution is to put the `last_user` first in this list and use "You" if `last_user == current_user`?

**Comment by zapnap** [comment]
Good point about consistency around last-replier-first. Updated the branch here https://github.com/zapnap/thredded/tree/private-message-participants

Since "You" isn't used anywhere else my gut says just keep it as current user name for consistency's sake.

I won't have a chance to dig into how the preloaded associations work until later (probably not today, unfortunately). Looks like that'll be a bigger change. But let me know if you have more feedback in the interim.

**Comment by zapnap** [comment]
@glebm updated branch. Will send a proper PR. Let me know if you have additional feedbakc.
