### ISSUE TITLE
Auto-follow new topics in specific messageboards?

### ISSUE THREAD

**Issue by zapnap** [thredded/thredded#488]
I'm looking for a way to have all my users automatically follow (and be notified of) new topics in a given messageboard, ala Google Groups. This would need to be something they could opt out of, of course. Looks like this would need to be added as a auto_follow preference in thredded_user_messageboard_preferences and then exposed as a preference in preferences/edit, but thought I'd toss it out there for discussion before taking a stab at implementation. Any thoughts?

I could also see use cases for a similar feature at the meta level like "auto-follow new messageboards"...

**Comment by glebm** [comment]
I can definitely see use cases for this, like a private company messageboard.
IMO the most-common use case would be `false` by default though (can be changed with `change_column_default` for a given installation though).

**Comment by zapnap** [comment]
Agree 100%. I'll work up a PR.

**Comment by zapnap** [comment]
@glebm how do you prefer db migrations in a PR? Just dumped into db/migrate for ultimate merging into an upgrade_migrations script at release?

**Comment by glebm** [comment]
@zapnap Well, we usually just modify the "create" and "upgrade" migrations directly in the PR (although I'm not sure if it's the best approach).

**Comment by glebm** [comment]
We may need to release v0.9.0 soon because it fixes a lot of minor bugs, so let's punt this to v0.10.0.

**Comment by zapnap** [comment]
👍 I'll probably try to make some time to take a look this weekend. v0.10 seems like a good target. Thanks @glebm

**Comment by glebm** [comment]
@zapnap Looks good!
