### ISSUE TITLE
Display pagination before the post form?

### ISSUE THREAD

**Issue by glebm** [thredded/thredded#491]
Currently the pagination is displayed after the post form, so if the user doesn't scroll down far enough then it may not be immediately obvious that there are more posts.

How about we move the pagination above the post form?

E.g. like this:

![thredded-pagination](https://cloud.githubusercontent.com/assets/216339/20548515/f5fc1ac0-b11b-11e6-96c3-77df48e42e43.png)

**Comment by jayroh** [comment]
Yeah I think that would work out great. That's a pretty great treatment - much more communicative.
