### ISSUE TITLE
app-header glitching

### ISSUE THREAD

**Issue by Ch4mp-The** [thredded/thredded#503]
I noticed this on my desktop 1920x1080, doesn't happen on laptop - 1600x900.

Not sure if this has been fixed yet and pushed to master.

**Comment by glebm** [comment]
This seems to be caused by how Turbolinks handles 4xx and 5xx response codes: https://github.com/turbolinks/turbolinks/issues/179.

**Comment by realCh4mp** [comment]
I turned off turbolinks, it causes only problems and didn't notice any huge speed advantage.

**Comment by glebm** [comment]
`thredded_create_app` now bundles [a monkey-patch](https://github.com/thredded/thredded_create_app/blob/0e580bc24e2de51374796d8416ea30d55df5d00b/lib/thredded_create_app/tasks/setup_app_skeleton/javascripts/app/monkey-patch-turbolinks.js) for this.
