### ISSUE TITLE
Permission for non-admin users to delete their own topics?

### ISSUE THREAD

**Issue by samirph** [thredded/thredded#504]
So far I haven't seen any way to allow a non-admin user to delete his own topics.
Is there a turnaround for this?

**Comment by glebm** [comment]
Permissions for topics are defined in [topic_policy.rb](https://github.com/thredded/thredded/blob/05089b034f24e5efea30f71fef04c46cf9067e30/app/policies/thredded/topic_policy.rb#L41). You can monkey-patch the policy in the initializer, e.g.:

```ruby
Rails.application.config.to_prepare do
  Thredded::TopicPolicy.class_eval do
    def destroy?
      @user.thredded_admin? || @topic.user_id == @user.id
    end
  end
end
```

**Comment by samirph** [comment]
Thanks!
Seems so obvious after looking at your code and at [topic_policy.rb](https://github.com/thredded/thredded/blob/05089b034f24e5efea30f71fef04c46cf9067e30/app/policies/thredded/topic_policy.rb#L41).
