### ISSUE TITLE
Disable delete post 

### ISSUE THREAD

**Issue by arkakun9** [thredded/thredded#505]
I was wondering.
How can I disable delete post for any user except user that create post?
without override views.
 and lastly using windows when run

`mkdir -p app/views/thredded/shared/nav && cp "$(bundle show thredded)/$_/_standalone.html.erb" "$_"`

and

`rake thredded:install:emoji`

will give you error.

thanks

**Comment by glebm** [comment]
On Windows you should run this command and `rake thredded:install:emoji` from Git Bash.

> How can I disable delete post for any user except user that create post?

By default, only moderators and the user that created the post can delete it.
Do you want to also prevent moderators from deleting posts?
