### ISSUE TITLE
Is there a way to programmatically add posts and threads?

### ISSUE THREAD

**Issue by chintanparikh** [thredded/thredded#506]
I have a bunch of old posts and threads from an old forum system in JSON format that I'd like to import into Thredded.

The threads look like this:

```json
{"thread_id":"1405","title":"Bhangra in the Burgh Official Line up!","forum_name":"Bhangra Competitions/Showcases/Teams","forum_id":"1"}
```

And posts look like:

```json
{"username":"Bhangra in the Burgh 2008","readable_time":"Sat Sep 27, 2008 3:50 pm    ","timestamp":1222501800,"content":"<span class=\"postbody\">The Bhangra in the Burgh 08 Executive committee is very proud to announce our competition's line up :\r\n<br>\n\r\n<br>\n\r\n<br>\nNYU Bhangra\r\n<br>\nCornell Bhangra\r\n<br>\nColumbia Bhangra\r\n<br>\nVCU Bhangra\r\n<br>\nRU Bhangra\r\n<br>\nNorthwestern Bhangra\r\n<br>\nUVA di Shaan\r\n<br>\nDrexel Bhangra\r\n<br>\n\r\n<br>\nThanks so much for everyone else who applied this year. It was an extremely selective and rigorous process, especially narrowing it down to 8 teams. We hope to see you all at Bhangra in the Burgh 08 on November 8th 2008 in Pittsburgh Pennsylvania. For more information, please check out our website at <a href=\"/web/20081002150721/http://www.bhangraintheburgh.com/\" target=\"_blank\">www.bhangraintheburgh.com.</a>\r\n<br>\n\r\n<br>\n\r\n<br>\nBhangra in the Burgh 08 : Experience it.\r\n<br>\n\r\n<br>\n\r\n<br>\nSincerely,\r\n<br>\n\r\n<br>\n\r\n<br>\nthe Bhangra in the Burgh 08 Executive Board</span>","signature":null}
```

**Comment by glebm** [comment]
Have a look at the [Forem -> Thredded migration](https://github.com/thredded/thredded/wiki/Migrate-from-Forem) to see how this can be done.

**Comment by jayroh** [comment]
If your legacy project is a rails app:

Add thredded to your app. Set it up. Get it working. You'll have access to all the Thredded models at this point so you'll be able to loop through your old data and create new records in the thredded tables.

If your legacy project is NOT a rails app:

Connect to your old database using `PG::Connection` ... eg: `connection = PG::Connection.new(LEGACY_DATABASE_URL)` ... `connection.exec(sql)` to get rows, etc. then loop through those.

I just did this sort of thing for a client project and wrote a few command-object classes that did this sort of work.

**Comment by chintanparikh** [comment]
Gotcha, thanks y'all. I'm going to close this for now. I'll re-open if I need any more help!

**Comment by jayroh** [comment]
Right on, man! Good luck!
