### ISSUE TITLE
Exception when migrating from forem

### ISSUE THREAD

**Issue by allaud** [thredded/thredded#510]
I was trying to migrate from existing forem install, but got the following exception:

    == 20170105201551 ForemToThredded: migrating ==================================
    -- transaction()
    -- Creating UserDetails...
    -- Created 7 UserDetails
    -- Copying Forem Categories to Messageboard Groups
    -- Copying Messageboards...
    -- Created 7 Messageboards
    -- Copying Topics...

    rake aborted!
    StandardError: An error has occurred, this and all later migrations canceled:

    PG::NotNullViolation: ERROR:  null value in column "created_at" violates not-null constraint
    DETAIL:  Failing row contains (7, topic, 7, Thredded::Topic, messageboard_id:42, null).
    : INSERT INTO "friendly_id_slugs" ("sluggable_id", "sluggable_type", "slug", "scope") VALUES ($1, $2, $3, $4) RETURNING "id"
    /Users/allaud/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:602:i

Any thoughts?

**Comment by jayroh** [comment]
Looking at the script in the wiki, it expects `t['created_at']` to contain the DateTime (I *think* it's a DateTime?) that the previous topic was created. In order to maintain the integrity of the NEW data I would find a way to update the source data (at Forem) to have a valid created_at value. Otherwise you could say "to hell with it" and give it a default of *"now"*? Like below:

```ruby
h.update(
          t['id'] => Thredded::Topic.create!(
              messageboard_id:  boards[t['forum_id']].id,
              user_id:          t['user_id'],
              title:            t['subject'],
              slug:             t['slug'],
              sticky:           t['pinned'],
              locked:           t['locked'],
              # 👇  like here
              created_at:       t.fetch('created_at', DateTime.now),
              # 👇 or this?
              # created_at:     t.fetch('created_at', last_post.fetch('created_at', DateTime.now)),
              updated_at:       last_post['created_at'],
              last_user_id:     last_post['user_id'],
              moderation_state: thredded_moderation_state(t['state'])
          )
      )
```

**Comment by allaud** [comment]
@jayroh for some reason it does not help. This is the full stacktrace (just in case): https://gist.github.com/allaud/d56f54cff91c2586cb5ee8d631b8c167

One more thing, first I got the error message `Validation failed: User has already been taken` and added the following line:

    next if Thredded::UserDetail.find_by_user_id(user_id)

after the line 53

**Comment by jayroh** [comment]
Have you tried putting in a `binding.pry` just before that `PG::NotNullViolation` exception is hit? That would allow you to play with the data to see what is causing the problem. Once you find that issue you can update the source data to a point where it won't die while migrating.

As for `Validation failed: User has already been taken` you could do, instead:

```ruby
Thredded::UserDetail.where(user_id: user_id).first_or_create!.update(
  latest_activity_at: user_posts.max_by { |p| p['created_at'] }['created_at'],
  created_at:         now,
  updated_at:         now,
  moderation_state:   thredded_moderation_state(moderation_states[user_id])
)
```

That will skirt the issue where a UserDetail has been created already and use the existing one on subsequent runs of the script.

**Comment by allaud** [comment]
This is what I see when using `binding.pry` 

    [1] pry(#<ForemToThredded>)> t
    => {"id"=>"4",
    "forum_id"=>"2",
    "user_id"=>"2",
    "subject"=>"test",
    "created_at"=>"2016-01-16 10:19:05.705083",
    "updated_at"=>"2016-02-03 21:15:11.600521",
    "locked"=>"f",
    "pinned"=>"f",
    "hidden"=>"f",
    "last_post_at"=>"2016-02-02 09:23:17.974102",
    "state"=>"approved",
    "views_count"=>"48",
    "slug"=>"5ac12c39-1ba3-4b25-84b5-9a1bb0174ac2"}

    [2] pry(#<ForemToThredded>)> last_post
    => {"id"=>"26",
    "topic_id"=>"4",
    "text"=>"Checking sing in",
    "user_id"=>"2",
    "created_at"=>"2016-02-02 09:23:17.974102",
    "updated_at"=>"2016-02-02 09:23:17.974102",
    "reply_to_id"=>nil,
    "state"=>"approved",
    "notified"=>"t"}

But anyway I got the exception. I also tried executing the command without migration context (which opens transaction for example), and it goes well:

    Thredded::Topic.create!(
    messageboard_id:  134,
    user_id:          "2",
    title:            "test",
    slug:             "5ac12c39-1ba3-4b25-84b5-9a1bb0174ac2",
    sticky:           "f",
    locked:           "f",
    created_at:       "2016-01-16 10:19:05.705083",
    updated_at:       "2016-02-03 21:15:11.600521",
    last_user_id:     "2",
    moderation_state: :approved
    )

I think the problem can be related to some internal implementation of db or transaction support. The few examples that I found:

https://github.com/rails/rails/issues/24219
http://stackoverflow.com/questions/23543349/how-do-i-interpret-this-rails-postgresql-error

**Comment by glebm** [comment]
@allaud Perhaps your thredded tables happen to contain invalid data from previous (failed) runs / debugging?

**Comment by allaud** [comment]
@glebm just taken a fresh dump from production (which uses forem), re-applied migration that creates thredded tables and then tried to migrate data from forem to thredded, but again caught the error

**Comment by allaud** [comment]
FYI: Just tried to execute all migration commands from rails console and everything goes well, so I think it can be related to some bug in rails migration/transaction system.

One thing to note: for some topics `last_post_at` appears to be empty after first opening, so that second opening causes an exception in `UserTopicReadStateCommon` module. This is what helped me (not sure if it is related to manual migration):

    def read?
      (postable.last_post_at || postable.updated_at) <= read_at
    end

**Comment by jayroh** [comment]
I completely glossed over the fact this said to do this all inside a
migration. We'll make the change to the wiki to move this over to something
like a rake task. I think that's probably a better approach than putting
rails-specific code in a migration, which is generally recommended against.

Thanks for the help with this!

**Comment by allaud** [comment]
@jayroh Thanks for confirmation, just in case, I've prepared the rake task for that (contains several other small fixes):

https://gist.github.com/allaud/b48ba3a55473c0ad765e580e0de75475

**Comment by timdiggins** [comment]
@allaud in reference to `last_post_at` -- I think we would be better off ensuring every topic/private topic has a non nil last_post_at as part of the forem migration script (IIRC we didn't touch the forem migration script when we added last_post_at -- which is often but not always the same as updated_at and updated_at is an excellent fallback value).

**Comment by allaud** [comment]
@timdiggins then i think I've done it right, adding this line to the script above:

https://gist.github.com/allaud/b48ba3a55473c0ad765e580e0de75475#file-transition-rake-L83

**Comment by timdiggins** [comment]
@allaud looks good to me

**Comment by glebm** [comment]
I've updated the wiki page, removing the nested transaction and adding `last_post_at`.
