### ISSUE TITLE
Unable to create Post for Guest/NullUser

### ISSUE THREAD

**Issue by lulalala** [thredded/thredded#511]
From the readme it seems to imply that guest user can be configured to be able to post by overriding the `thredded_messageboards_writers` and `thredded_can_write_messageboards`.

However in reality, when I did that, when the user hits the Post create action, the before_action `thredded_require_login?` will err out.

What is intended here? Thanks~

**Comment by glebm** [comment]
Hi @lulalala. The guest post creation is not supported by Thredded currently.

This cannot be implemented through the permissions system alone.

First, the data model would need to distinguish between topics/posts made by anonymous users and those made by users that are now deleted.

Then, the post creation logic would need to be modified for anonymous users, e.g.:

1. Do not auto-follow the topic after posting in it.
2. Do not go through the moderation system.
3. If anonymous posting is enabled, do not `thredded_require_login!` before certain actions, such as posting.

**Comment by lulalala** [comment]
Cool, thanks for the detailed analysis! :)
