### ISSUE TITLE
Private message e-mail notification

### ISSUE THREAD

**Issue by soanvig** [thredded/thredded#512]
Hi! During testing e-mail notification for new private message I noticed strange bug - the message which comes by the e-mail is always the first message of the whole conversation. No matter who sends message, the notification always contains the first message of conversation.

**Comment by timdiggins** [comment]
@soanvig Ah yes -- I think historically this email was used to notify "that you've been added to the private topic" but now it's being sent on every update. So it should really contain the latest post in the conversation.

**Comment by soanvig** [comment]
I have never modified a rails gem before. What can I do to make it sent the newest msg In conversation?

-----Wiadomość oryginalna-----
Od: "Tim Diggins" <notifications@github.com>
Wysłano: ‎2017-‎01-‎11 15:21
Do: "thredded/thredded" <thredded@noreply.github.com>
DW: "Schizohatter" <soanvig@gmail.com>; "Mention" <mention@noreply.github.com>
Temat: Re: [thredded/thredded] Private message e-mail notification (#512)

@soanvig Ah yes -- I think historically this email was used to notify "that you've been added to the private topic" but now it's being sent on every update. So it should really contain the latest post in the conversation.

**Comment by soanvig** [comment]
What can I do to change it so It sends latest msg in conversation? Never edited rails gem before.

**Comment by timdiggins** [comment]
@soanvig 
If you're comfortable with rails apps in general, then it's really just a mini rails app. 

The actual view is in  https://github.com/thredded/thredded/blob/master/app/views/thredded/private_topic_mailer/message_notification.html.erb and https://github.com/thredded/thredded/blob/master/app/views/thredded/private_topic_mailer/message_notification.text.erb (you can see a bogus comment in this file that dates from when this was only sent on the private topic creation, not on each post).

You can get the latest content with: @topic.posts.order_newest_first.first

**Comment by glebm** [comment]
It's best to pass the post ID to the mailer instead of looking it up within the mailer.

**Comment by soanvig** [comment]
By the way, are you going to fix this on master, or should I make fork and PR (soon or later I will do it anyway, because I see the need for a lot of improvements).

**Comment by timdiggins** [comment]
@soanvig PRs are always welcome! As Gleb says, this mailer view could do with some improvement but ultimately a fix would be great.
