### ISSUE TITLE
Better handling of `ActiveRecord::RecordNotFound` exceptions

### ISSUE THREAD

**Issue by jayroh** [thredded/thredded#513]
![errors_-_thredded_demo_-_new_relic](https://cloud.githubusercontent.com/assets/28194/21865882/ecf2013a-d815-11e6-8905-6acad8a5e5e3.jpg)

Seeing this creep up on NewRelic pretty often. I think it'd be relatively easy to handle and react accordingly if/when records don't exist. One (or two) less blip(s) on the error/exception radar.

**Comment by timdiggins** [comment]
@jayroh what kind of fix are you thinking about? 

I think that letting the MainApp handle 404s seems correct -- ActiveRecord::RecordNotFound is just a 404 really. (and you could configure NewRelic or whatever to ignore 404s*).

*though you probably want to know about 404s which have a local referer... But again this is the mainapp's job I think.

But maybe I got wrong end of this stick?

**Comment by cbortz** [comment]
@jayroh Do you have anymore thoughts on this issue?

**Comment by jayroh** [comment]
@cbortz I think it's a case where those spots in the code should be a little more defensive.  As in maybe doing something like

```ruby
@user = User.where(id: params[:id]).first
redirect_to some_path, error: "User not found" if @user.nil?

# instead of
User.find(params[:id])
```

It's a little more work but worth it

**Comment by glebm** [comment]
A 404 should not be a redirect though

**Comment by jayroh** [comment]
I'm not saying it *should* be a 404. Just saying it could he handled that way.
