### ISSUE TITLE
Mark as unread

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded#524]
I have a need for a "mark this topic as unread" (so it stays on my list of things to read) -- not sure if this belongs in core thredded -- let me know if any thoughts @jayroh @glebm

**Comment by glebm** [comment]
Don't see why this shouldn't be in core as long as there is a view hook around it!

**Comment by EllaNancyFay** [comment]
@glebm have just created a PR https://github.com/thredded/thredded/pull/533

**Comment by timdiggins** [comment]
As #533 was merged in Feb, I'm closing this.
