### ISSUE TITLE
How to have private boards/board groups?

### ISSUE THREAD

**Issue by replicat0r** [thredded/thredded#528]
Lets say, there is different tiered user group(aka, attribute on my devise user model). I want to make access to certain board/board group off limits to some user groups but the others. 

how would I approach this? I tried to override the default thredded_can_read_messageboards on the user model, but i keep running into exceptions. Then i realize that I can't just monkey patch a part of my model, because it leaves holes in other parts of the forum, such as search or just plain url input. 

how can i do this the right way?

**Comment by glebm** [comment]
Override both `User#thredded_can_read_messageboards` and `User. thredded_messageboards_readers(messageboards)`.

See https://github.com/thredded/thredded#permission-methods
and https://github.com/thredded/thredded/blob/master/app/models/thredded/user_permissions/read/all.rb

**Comment by replicat0r** [comment]
I understand thats the part I need to override in my user model, but how can i search active record for list of the message boards?

How Do i specifically query activerecord to do that? I dont have access to the Thredded model inside my user model. If I define a method that overrides the default method, self.thredded_can_read_messageboards returns nil 


lets say i have a group of message board under the group 'private', and user group has a column 'vip' , can you show me an example of overridden thredded_can_read_messageboards method, in the user model that only allow these user to access that group of messageboards?

**Comment by glebm** [comment]
> I dont have access to the Thredded model inside my user model

Yes you do. E.g.:

```ruby
def thredded_can_read_messageboards
  if admin?
    Thredded::Messageboard.all
  else
    Thredded::Messageboard.where.not(id: 5)
  end
end

def self.thredded_messageboards_readers(messageboards)
  # must be consistent with the #thredded_can_read_messageboards method
end
```

> lets say i have a group of message board under the group 'private', and user group has a column 'vip' , can you show me an example of overridden thredded_can_read_messageboards method, in the user model that only allow these user to access that group of messageboards?

The class that represents a messageboard group is `Thredded::MessageboardGroup`.
You can learn how to construct your particular query by reading Rails documentation or asking on StackOverflow if you get stuck.
