### ISSUE TITLE
Postgres/UUID compatability

### ISSUE THREAD

**Issue by jvoss** [thredded/thredded#538]
There are several routes that enforce regex on the post ID, etc being a number 0-9. Can the routes be updated to allow UUIDs if someone is using that instead of integer IDs?

**Comment by glebm** [comment]
This seems to be the only block that currently does this, is that right?

```ruby
scope only: [:show], constraints: { id: positive_int } do
  resources :private_post_permalinks, path: 'private-posts'
  resources :post_permalinks, path: 'posts'
end
```

We can definitely consider a PR that adds a configuration option such as `Thredded.routes_id_constraint`.

**Comment by jvoss** [comment]
That appears to be the only blocking that I am running into at the moment, mostly having to deal with moderation which does use this route.

I'll see if I can create a PR for you soon. Thanks!

**Comment by glebm** [comment]
Thank you! All merged, will be out in the next release!
