### ISSUE TITLE
Behaviour with multiple notifiers. 

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded#540]
In a situation with multiple notifiers, only the first notifier will be used because of #529 

This means that the notifiers are (currently) effectively a choice.

However the UI (and previous behaviour) allowed users to choose multiple notifiers if they wanted. (it turns out some people actually want this).

Two easy options:

1) add notifier key to UserPostNotification (and add this to the uniqueness criterion)
2) change UI to only allow one Notifier to run (reducing functionality)

any other options?

**Comment by glebm** [comment]
Is that what it does? This was definitely not the intent.

The `already_notified_user_ids` is calculated once (`||=`), so it *should* notify via all the notifiers.

**Comment by timdiggins** [comment]
Hmmm. I'll double check. Maybe something else was stopping the notifications and I jumped to conclusions through hasty reading of the code

**Comment by Outasight** [comment]
Die you solve the problem? Because I am experiencing the same behaviour.

**Comment by timdiggins** [comment]
@Outasight I don't think this was ever a real problem (I got it wrong in fact). Can you describe the problem that you're having? Which notifiers are you using? (maybe post your  initializer with the multiple notifier setup?)

**Comment by Outasight** [comment]
I am trying to implement a custom notifier for push notifications. Maybe I missed something.
I added my notifier in the initializer:
`Thredded.notifiers = [Thredded::PushNotifier.new, Thredded::EmailNotifier.new]`

But now just the first one will work. The problem I see is that `UserPostNotification.create_from_post_and_user(@post, user)` doesn't differentiate the two notifiers. So the second notifier will not be called, because the users have already been notified by the first notifier.

**Comment by timdiggins** [comment]
@Outasight I agree with you -- the problem is there are two checks for `already notified` -- one the `already_notified_user_ids` (which are rejected as part of the `targeted_users` and which are only called once as @glebm mentioned) but also as you say the create_from_post_and_user prevents the completion on the second notification.

We first of all need a test that evidences this (think this through now, in case I have time to code up later: Given a user and post, Given two notifiers, and the user is following posts' topic and subscribed to notifications (messageboard and global) for  both notifiers. When the NotifyFollowingUsers is run, Then user should receive notifications via both notifiers.)

Then we need to decide how best to fix this:

1. either add the notifier key as an extra column (as part of the joint unique key) to the UserPostNotification  (harder, and why bother, as the notifications run separately)
2. or simpler, just do the creation and check separately to the notifiers loop, either before or after?

**Comment by Outasight** [comment]
@timdiggins Thank you for your reply.

Your first suggestion sounds like a clean solution. I don't completely understand when and where you want to do the check in your second suggestion?
Do we need the second check for `already notified` or is it enough to check with `already_notified_user_ids` and skip the `create_from_post_and_user` check? Or will there be problems with multi-threading (or any other problems)?

**Comment by timdiggins** [comment]
@Outasight The problem I have with the first option is that semantically I think the system only should care as to whether the user has been notified or not. Then when you decide which way you then notify them by the means they have subscribed to it that time. e.g. When you add new notifiers to the system -- it's doubtful people want to be notified by the second notifier and not the first. And also I  just shudder to add all those extra rows for such a slight feature (maybe I'm being too squeamish here).

With regard to second option, I don't think I was thinking straight about doing the creation and check going out of the loop -- seems a bit mad.

But I agree we probably only need one check and we could change the `select` to an `each` and discard the result (and just very occasionally when the system is misconfigured for some reason may end up  double-sending notifications -- but this seems fairly rare -- only when you have dualling job-runners). 

In which case option 2 sounds pretty easy -- the hard work (as ever) is writing the test.

Let me know if you are likely to have time to do this as a PR. If not I may be able to.

**Comment by Outasight** [comment]
@timdiggins Sounds good. Thanks for your help. I am sorry, but I don't think I will be able to do this as a PR.

**Comment by timdiggins** [comment]
FYI @Outasight, in case it helps I've published an early version of a Pushover notifier at https://github.com/red56/thredded-pushover-notifier. 

@glebm -- happy to move that to thredded org if/when you're happy with it.

**Comment by glebm** [comment]
@timdiggins Looks great!

**Comment by timdiggins** [comment]
@glebm @Outasight moved to https://github.com/thredded/thredded-pushover-notifier and v0.1.0 released as gem
