### ISSUE TITLE
Onebox support

### ISSUE THREAD

**Issue by glebm** [thredded/thredded#545]
Currently we have support for YouTube and Vimeo videos via a couple of html-pipeline gems. However, the support is somewhat limited and has issues, such as links in the middle of the sentence getting replaced with `<div>`s that don't work in markdown.

Discourse, on the other hand, has [Onebox](https://github.com/discourse/onebox), a ruby library that can turn [many](https://github.com/discourse/onebox/tree/master/lib/onebox/engine) types of URLs into an embed. Onebox is MIT-licensed, does not depend on Discourse, and has few external dependencies (that we do not already depend on).

Their approach to rendering oneboxes is:

1. Render the entire post without oneboxes. During rendering, [add](https://github.com/discourse/discourse/blob/5dbd6a304bed5400be481d71061d3e3ebb4d6785/app/assets/javascripts/pretty-text/engines/discourse-markdown/onebox.js.es6#L57) a `onebox` class to links that are on a single line in the source markdown.
2. Afterwards, [turn these links](https://github.com/discourse/discourse/blob/49a0f16ce488817bba89d57b0701a85e93b10752/lib/oneboxer.rb#L83) into oneboxes. Oneboxes are sanitized separately with their own config. This is great because it means not having to whitelist arbitrary iframes.

In our case the `onebox` class addition would have to happen in a Kramdown "parser" that tags the links as being on one line, and then a Kramdown "converter" to add the `onebox` class. This is not going to be fun to implement. We can start by simply oneboxing *all* the links, side-stepping this issue for now.

Some CSS is required to style these oneboxes. Here is how Discourse does it: [onebox.scss](https://github.com/discourse/discourse/blob/03bc6f70f9e329e5df44df67e9f73c8e548e788a/app/assets/stylesheets/common/base/onebox.scss).

In the future, a Onebox can also be used for linking to other forum posts and topics (see [Discourse onebox](https://github.com/discourse/discourse/blob/master/lib/onebox/engine/discourse_local_onebox.rb)).

**Comment by jayroh** [comment]
Wow that's super fancy!

**Comment by glebm** [comment]
Aand.. it's done! :sparkles:
