### ISSUE TITLE
Notifier 'From' address in 'To' address

### ISSUE THREAD

**Issue by pak9rabid** [thredded/thredded#548]
When testing email notifications, I noticed that the 'From' email address (set via the 'Thredded.email_from' option in the Thredded initializer) gets inserted as one of the 'To' addresses when notification emails get sent out.  See attached screenshot:

<img width="2032" alt="screen shot 2017-03-13 at 1 25 03 pm" src="https://cloud.githubusercontent.com/assets/3590282/23869352/ad7606ea-07f0-11e7-8297-a8a958232f6d.png">

**Comment by glebm** [comment]
Yes, this is because thredded sets all the recipients in the "BCC" field, but a "To" address is required so we have to set it to something.

We should probably stop using BCC though. @thredded/core Thoughts?

**Comment by pak9rabid** [comment]
It looks like the recipient is being set in the 'To' field above.

**Comment by glebm** [comment]
I think that might be mailcatcher being confused

**Comment by pak9rabid** [comment]
Ah, yeah I think you're right. Alrighty then, non-issue.  Thanks for the quick response.

**Comment by glebm** [comment]
@pak9rabid On a related note, I've just publish https://github.com/thredded/thredded/wiki/Styling-email-content

**Comment by timdiggins** [comment]
Agreed to moving  from `bcc` to individual `to` emails. Better personalization and better deliverability. But not super urgent. 

I thought thredded was exposing users email addresses  to at first, too. (Think there's a historical issue about that from me...)
