### ISSUE TITLE
Missing Template in the thredded controller for formats other than HTML

### ISSUE THREAD

**Issue by replicat0r** [thredded/thredded#557]
An ActionView::MissingTemplate occurred in topics#index:

Missing template thredded/error_pages/not_found with {:locale=>[:en], :formats=>[:json], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :jbuilder]}. Searched in:
* "/var/app/current/app/views"
* "/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/devise-4.2.0/app/views"
* "/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/thredded-0.10.0/app/views"
* "/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/kaminari-core-1.0.1/app/views"
* "/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/devise-i18n-1.1.1/app/views"
------------------------------- Request:

* URL        : https://www.myforumlink.com/forum/composer.json
* HTTP Method: GET
* IP address : *
* Parameters : {"controller"=>"thredded/topics", "action"=>"index", "messageboard_id"=>"composer", "format"=>"json"}
* Timestamp  : 2017-03-19 08:16:02 UTC
* Server : *
* Rails root : /var/app/current
* Process: 24539

Seems like there are some people trying to find out information about the core of the server and application. Looks like the error handler for thredded controllers can only deal with HTML format. I am seeing this on topic#show and topic#show, possibly others.

**Comment by jayroh** [comment]
This exception could be caught on the controller level and redirected to
the `html` version of the request.

Would make for a pretty sweet PR if anyone wanted to help us handle it :)

/wink wink

**Comment by glebm** [comment]
Perhaps rather than redirecting it should just return a 404

**Comment by abhinaykumar** [comment]
I agree to what @glebm is suggesting..404 should be the default fall back for missing pages

**Comment by glebm** [comment]
Looking a bit more into it, the correct response is 406:

> 406 NOT ACCEPTABLE
> The target resource does not have a current representation that would be acceptable to the user agent, according to the proactive negotiation header fields received in the request, and the server is unwilling to supply a default representation.

Returning 406 already is the default handling for the exception above:
https://thredded.org/thredded/main-board.json
