### ISSUE TITLE
Just can't get thredded to work with Turbolinks 5

### ISSUE THREAD

**Issue by jarvisjohnson** [thredded/thredded#559]
I've tried so many different ways, but no matter what I do, I can't get Thredded js to run and not break other js in my site.

I've tried the recommended 

`//= require thredded`

I've attempted to include (haml)

``` 
 - if params[:controller].include? "thredded"  
    = javascript_include_tag "thredded"
```

In `head`, in `body`

No matter where I put Thredded JS, I get `Uncaught TypeError: $(...).[some other js function] is not a function` console errors

All other external js libraries are working with `//require` method in `application.js`.

Has anyone come across and fixed this?

**Comment by glebm** [comment]
See https://github.com/thredded/thredded/blob/master/README.md#jquery-version

**Comment by jarvisjohnson** [comment]
yep that did the trick thanks @glebm.  I had read that a few times and assumed that my Rails 5 app would  default have included the most current jquery, not realising that 
`//= require jquery` in application.js is exactly what the readme is talking about.  

Thanks mate - hope that helps someone else too.
