### ISSUE TITLE
Make avatars larger on large screens

### ISSUE THREAD

**Issue by glebm** [thredded/thredded#565]
On desktop, the author of each posts is more obvious if the avatars are larger.

I'm thinking the sweet spot is somewhere between 3.25 and 4rem.
Should be configurable via a variable.

For comparison:

| size=3.25rem left=-4rem | size=2.25rem left=-3rem (current) |
|-|-|
| ![intaug org-forum-general-welcome-aboard 1](https://cloud.githubusercontent.com/assets/216339/24511263/76e0dfb2-1563-11e7-8d87-cd34603e7086.png) | ![intaug org-forum-general-welcome-aboard 2](https://cloud.githubusercontent.com/assets/216339/24511389/c9d59794-1563-11e7-9ef7-36cef58c4304.png) |

**Comment by glebm** [comment]
@xuliaP I think avatar uploading is out of scope for Thredded core.

**Comment by jayroh** [comment]
Since the parent app handles the User model it would be completely within
the realm of doing, hypothetically. Just - thredded wouldn't handle that as
a responsibility. I would agree with gleb that it's out of scope for a
forum project.
