### ISSUE TITLE
Undocumented  testing dependencies

### ISSUE THREAD

**Issue by cbortz** [thredded/thredded#567]
I encountered three issues when trying to run `rspec` for the first time...

1. ~~I needed to actually create and migrate my test database~~
2. I needed to create a missing log file that was expected
3. I needed to install phantomjs

~~The first one was simple: `RAILS_ENV=test rake db:create db:migrate`. **Perhaps this should be added to the README before instructing to run `rspec`?**~~

The second one was interesting. After running `rspec` I got this error message:

```
/thredded/spec/spec_helper.rb:19:in `initialize': No such file or directory @ rb_sysopen - log/test.sqlite3.log (Errno::ENOENT)
  from /thredded/spec/spec_helper.rb:19:in `open'
  from /thredded/spec/spec_helper.rb:19:in `<top (required)>'
  from /thredded/spec/commands/thredded/autofollow_users_spec.rb:2:in `require'
  from /thredded/spec/commands/thredded/autofollow_users_spec.rb:2:in `<top (required)>'
  from /.rvm/gems/ruby-2.3.3@thredded/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
  from /.rvm/gems/ruby-2.3.3@thredded/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
  from /.rvm/gems/ruby-2.3.3@thredded/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
  from /.rvm/gems/ruby-2.3.3@thredded/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
  from /.rvm/gems/ruby-2.3.3@thredded/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
  from /.rvm/gems/ruby-2.3.3@thredded/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
  from /.rvm/gems/ruby-2.3.3@thredded/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
  from /.rvm/gems/ruby-2.3.3@thredded/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
  from /.rvm/gems/ruby-2.3.3@thredded/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
  from /.rvm/gems/ruby-2.3.3@thredded/bin/rspec:22:in `load'
  from /.rvm/gems/ruby-2.3.3@thredded/bin/rspec:22:in `<main>'
  from /.rvm/gems/ruby-2.3.3@thredded/bin/ruby_executable_hooks:15:in `eval'
  from /.rvm/gems/ruby-2.3.3@thredded/bin/ruby_executable_hooks:15:in `<main>'
```

So, in brute force fashion, I just created an empty file at that location and then my tests began running. **_Can someone fill me in on this? Is there a command to generate this, or a way to gracefully/lazily generate it?_**

Then, lastly, I encountered the error (70x):

```
Cliver::Dependency::NotFound:
              Could not find an executable ["phantomjs"] on your path.
```

Of course, I then just used `brew install phantomjs` to get things working. I didn't see phantomjs mentioned in the README. **Should we add it?**

**Comment by glebm** [comment]
1. You shouldn't need to create and migrate the database manually. What made you think it's necessary?
2. We should create the log directory if it does not exist on rspec startup.
3. Yes, we should document the phantomjs dependency.

**Comment by cbortz** [comment]
@glebm Regarding # 1, that was an assumption on my part... my bad :) I'll submit a PR for the other two today.

**Comment by vcavallo** [comment]
I just ran into the same issue myself (well, #2 at least). Looking forward to #569 being merged.
