### ISSUE TITLE
thredded config

### ISSUE THREAD

**Issue by xuliaP** [thredded/thredded#571]
```
# If your forum is in a language other than English, you might want to use the babosa gem instead
 Thredded.slugifier = ->(input) { Babosa::Identifier.new(input).normalize.to_s }
```
i will be added that for correct work need add transliterator like this:
 Thredded.slugifier = ->(input) { Babosa::Identifier.new(input).normalize.transliterate(:your_language).to_s }

**Comment by glebm** [comment]
Thanks, fixed
