### ISSUE TITLE
Issue with Turbolinks5?

### ISSUE THREAD

**Issue by BobWalsh** [thredded/thredded#578]
I've integrated Thredded into our rails 5 app (which uses turbolinks 5), using our layout, but I'm seeing the following behavior on "start a new topic". After navigating from some other part of the app to /forum, clicking into the 'start a new topic' fld doesn't trigger revealing the rest of the form. Only after doing a refresh does the expected behavior happen:
<img width="722" alt="beatthread" src="https://cloud.githubusercontent.com/assets/5097/25292777/7d22f164-268c-11e7-9c84-66800f40dcff.png">

Suggestions?Workarounds?

**Comment by glebm** [comment]
Perhaps you've missed https://github.com/thredded/thredded#jquery-version?
