### ISSUE TITLE
_private_topic.html.erb causes private_topic controller to fail on heroku

### ISSUE THREAD

**Issue by trentlarge** [thredded/thredded#584]
<img width="1166" alt="screen shot 2017-05-02 at 12 33 20 pm" src="https://cloud.githubusercontent.com/assets/9291030/25628252/91b0982a-2f33-11e7-836f-c15d9c457928.png">

Though the Thredded apps perfectly normally on local machine, the 'private-topic' url will not load when pushed to heroku production server. Running rails 4.2.8 and ruby 2.3.0.

I looked through the codebase and couldn't find anywhere using the partial, so I used:
` mkdir -p app/views/thredded/private_topics && cp "$(bundle show thredded)/$_/_private_topic.html.erb" "$_"` to bring it into editable view and removed all contents. So far, it seems to be working perfectly!

**Comment by glebm** [comment]
What is the full stack trace?
