### ISSUE TITLE
undefined method `renderer' for Thredded::ApplicationController:Class

### ISSUE THREAD

**Issue by wandp** [thredded/thredded#590]
I'm attempting to render the preview shared template outside of the Mounted Thredded Engine.
I attempted to follow these instructions here:
https://github.com/thredded/thredded/wiki/Render-Thredded-partials-outside-of-Thredded
however I'm greeted with 
```
2.2.3 :004 > Thredded::ApplicationController.renderer
NoMethodError: undefined method `renderer' for Thredded::ApplicationController:Class
```

**Comment by glebm** [comment]
This requires Rails 5, are you by any chance using Rails 4?

**Comment by wandp** [comment]
indeed we are on rails 4, is there an alternative method for rendering outside the engine?

**Comment by glebm** [comment]
There seems to be a backport gem but I haven't used it: https://github.com/brainopia/backport_new_renderer

https://evilmartians.com/chronicles/new-feature-in-rails-5-render-views-outside-of-actions: 
> By the way, I’ve backported this feature to Rails 4. Just add the `backport_new_renderer` gem to your project Gemfile and you’ll have the same API available.

**Comment by wandp** [comment]
sweet, I'll give it a try ~
thank you for your prompt response ~,~
