### ISSUE TITLE
ActionView::Template::Error: undefined method `case_sensitive?' for nil:NilClass

### ISSUE THREAD

**Issue by avitus** [thredded/thredded#595]
I recently upgraded from Thredded 0.9 to 0.12.4. In a forum with 1000 topics, I'm seeing a handful of topics with the following error:

> ActionView::Template::Error: undefined method `case_sensitive?' for nil:NilClass

I can't for the life of me figure out why this is happening. I've looked through the db_text_search gem and it seems to be related to a column name (?) but I don't see anything irregular in my schema.

> /gems/db_text_search-0.2.1/lib/db_text_search/case_insensitive.rb:96 in block in column_case_sensitive?
> /gems/db_text_search-0.2.1/lib/db_text_search.rb:26 in match_adapter
> /gems/db_text_search-0.2.1/lib/db_text_search/case_insensitive.rb:94 in column_case_sensitive?
> /gems/db_text_search-0.2.1/lib/db_text_search/case_insensitive.rb:74 in block in adapter_class
> /gems/db_text_search-0.2.1/lib/db_text_search.rb:26 in match_adapter
> /gems/db_text_search-0.2.1/lib/db_text_search/case_insensitive.rb:76 in adapter_class
> /gems/db_text_search-0.2.1/lib/db_text_search/case_insensitive.rb:13 in initialize
> /gems/thredded-0.12.4/app/models/concerns/thredded/post_common.rb:46 in new
> /gems/thredded-0.12.4/app/models/concerns/thredded/post_common.rb:46 in readers_from_user_names
> /gems/thredded-0.12.4/app/models/concerns/thredded/post_common.rb:34 in block in filtered_content
> /gems/thredded-0.12.4/lib/thredded/html_pipeline/at_mention_filter.rb:47 in highlight!
> /gems/thredded-0.12.4/lib/thredded/html_pipeline/at_mention_filter.rb:21 in block in call
> /gems/thredded-0.12.4/lib/thredded/html_pipeline/at_mention_filter.rb:62 in block in process_text_nodes!
> /gems/nokogiri-1.8.0/lib/nokogiri/xml/node_set.rb:190 in block in each
> /gems/nokogiri-1.8.0/lib/nokogiri/xml/node_set.rb:189 in upto
> /gems/nokogiri-1.8.0/lib/nokogiri/xml/node_set.rb:189 in each
> /gems/thredded-0.12.4/lib/thredded/html_pipeline/at_mention_filter.rb:60 in process_text_nodes!
> /gems/thredded-0.12.4/lib/thredded/html_pipeline/at_mention_filter.rb:18 in call
> /gems/html-pipeline-2.6.0/lib/html/pipeline/filter.rb:130 in call
> /gems/html-pipeline-2.6.0/lib/html/pipeline.rb:125 in block in perform_filter
> /gems/html-pipeline-2.6.0/lib/html/pipeline.rb:163 in instrument
> /gems/html-pipeline-2.6.0/lib/html/pipeline.rb:124 in perform_filter
> /gems/html-pipeline-2.6.0/lib/html/pipeline.rb:110 in block (2 levels) in call
> /gems/html-pipeline-2.6.0/lib/html/pipeline.rb:109 in each
> /gems/html-pipeline-2.6.0/lib/html/pipeline.rb:109 in inject
> /gems/html-pipeline-2.6.0/lib/html/pipeline.rb:109 in block in call
> /gems/html-pipeline-2.6.0/lib/html/pipeline.rb:163 in instrument
> /gems/html-pipeline-2.6.0/lib/html/pipeline.rb:107 in call
> /gems/thredded-0.12.4/lib/thredded/content_formatter.rb:97 in format_content
> /gems/thredded-0.12.4/app/models/concerns/thredded/post_common.rb:35 in filtered_content
> /gems/thredded-0.12.4/app/view_models/thredded/post_view.rb:6 in filtered_content

**Comment by jayroh** [comment]
Sounds like this happens only with topics, or posts, that contain specific content. Maybe there's an issue with encoding of some sort?

If this were me I would:

1. replicate the production db in my development env
2. in my dev env, delete posts, one by one, from the offending topics to see if/what post it is.
3. if it's the topic then it's in the topic title - what's in the title.

If you can zero in on the problematic content it might be easier to debug

**Comment by glebm** [comment]
@avitus I've just released db_text_search v0.2.2 that will give you a more helpful error message. By the way, did you copy and run the [upgrade migrations] when upgrading?

https://github.com/thredded/thredded/tree/master/db/upgrade_migrations

**Comment by glebm** [comment]
@avitus Did you figure out what the issue was?

**Comment by avitus** [comment]
@glebm Yes, thanks, the updated error message was very helpful. It turns out I was using a class method rather than the column name.
