### ISSUE TITLE
MariaDB support?

### ISSUE THREAD

**Issue by mgmodell** [thredded/thredded#600]
I'm currently running my app on MariaDB and figured thredded out to work as it's supposed to be a drop-in replacement for MySQL (you know what's coming). I have generated the migrations and found that adding the following option to 2 tables gets past the FULLTEXT search issues:

`options: 'ENGINE=MyISAM'`

Now I've reached the last index and I'm receiving error 150:
```
 add_foreign_key :thredded_user_post_notifications,
                    :thredded_posts, column: :post_id, on_delete: :cascade
```
Mysql2::Error: Can't create table 'colab_dev.#sql-375_16b' (errno: 150): ALTER TABLE `thredded_user_post_notifications` ADD CONSTRAINT `fk_rails_364d7e370a`
FOREIGN KEY (`post_id`)
  REFERENCES `thredded_posts` (`id`)
 ON DELETE CASCADE

Is it possible to get past this and wind up with a functional thredded engine on MariaDB? Has anyone done any testing on MariaDB? Any assistance at all would be awesome!

Thanks!

**Comment by glebm** [comment]
Try upgrading to the latest version https://mariadb.com/kb/en/mariadb/mariadb-10031-release-notes/

**Comment by mgmodell** [comment]
Thank you. I guess Linux Mint is behind. I'll have to have a look into it and don't have time right now. Should I do the "Close and comment" thing?

**Comment by jayroh** [comment]
Hey Micah -

If you want to get around the dependency issue with Linux Mint - you
*could* stop the local mariadb instance and load up the latest version with
docker. If you want to get around that problem, that is. With a little
preliminary googling I found this:
https://mariadb.com/kb/en/mariadb/installing-and-using-mariadb-via-docker/

YMMV

Hope it works out, man :)

(And - you can close the issue that way, yeah. "close + comment")
