### ISSUE TITLE
User Profile Partial - NameError in Users#show

### ISSUE THREAD

**Issue by potatowave** [thredded/thredded#613]
I'm a bit Rusty on Rails so I could have done something incorrectly.

I'm trying to render user profile as detailed here: https://github.com/thredded/thredded#user-profile-page

I am getting:

`NameError in Users#show`
`undefined local variable or method 'user' for #<#<Class:0x007f9368d32db0>:0x007f9368eacf10>`

My account (admin) is currently logged in.  

Do I have to define user somewhere?

**Comment by potatowave** [comment]
I was able to get this working by adding to my controller:

`  def show
    @user = User.find(params[:id])
  end`

and modifying the following code with the instance variable.

`<%= Thredded::ApplicationController.render partial: 'thredded/users/posts', locals: { posts: Thredded.posts_page_view(scope: **@user**.thredded_posts.order_newest_first.limit(5), current_user: current_user) } %>`

Is this an adequate solution?  If so should it be updated in the Readme?

**Comment by jayroh** [comment]
Oh yeah! Totally the right approach with that :)

![](https://media.giphy.com/media/dykJfX4dbM0Vy/giphy.gif)
