### ISSUE TITLE
Application layout -  CSS Styles from Application override?

### ISSUE THREAD

**Issue by potatowave** [thredded/thredded#620]
I'm using Thredded in my existing app with Bootstrap.  I wish to use my Bootstrap navbar with Thredded rendering below. 

This is working great for me, however there is one issue I'm facing that I'm not sure how to solve. 

Thredded renders with very small fonts.  The offending font-size is inherited from html, setting everything to 10px. 

This is the default rendered view:

![screen shot 2017-09-09 at 19 53 45](https://user-images.githubusercontent.com/20651632/30245751-ac218c7a-9598-11e7-976b-68323c180bba.png)

After unchecking html font-size: 10px in devtools:

![screen shot 2017-09-09 at 19 53 22](https://user-images.githubusercontent.com/20651632/30245755-c1d0be10-9598-11e7-9840-dbf67a567926.png)

Any idea how I can get around this niggle?

**Comment by glebm** [comment]
That 10px style comes from `bootstrap/scaffolding`. Avoid importing `bootstrap/scaffolding` (you're likely not using any of it).

If you're actually using stuff from `bootstrap/scaffolding`, you can override the root font size after importing it:

```css
html {
  font-size: inherit;
}
```

This will not affect any bootstrap functionality. We should not have had that in Bootstrap to begin with, but now it's too late to remove it in v3. We did remove it in Boostrap 4.
