### ISSUE TITLE
use topic id instead of slug for default path?

### ISSUE THREAD

**Issue by moondcr** [thredded/thredded#624]
I want to use the topic id for my default path, how can i configure it? sorry i have less knowledges about ruby and rails, but i found @thredded was really awesome.

**Comment by glebm** [comment]
See the slugifier setting in the config

**Comment by glebm** [comment]
Ah, it's not that simple because the input to `Thredded.slugifier` is a string.

You can do it like this. In `config/initializers/thredded.rb`, add:

```ruby
Rails.application.config.to_prepare do
  module Thredded
    class Topic < ActiveRecord::Base
      private
      def slug_candidates
        [:id]
      end
    end
  end
end
```

**Comment by glebm** [comment]
I also see that your forum is in Chinese.
If you want, you can also have slugs in pinyin, using https://github.com/flyerhzm/chinese_pinyin, like this:

1. Add `gem 'chinese_pinyin'` to Gemfile and run `bundle`.
2. Add this to `config/initializers/thredded.rb`:

```ruby
Thredded.slugifier = -> (input) { Pinyin.t(input, splitter: '-') }
```

**Comment by moondcr** [comment]
@glebm Thanks so much for the help. I think **gem** `chinese_pinyin` works perfect. 👍
