### ISSUE TITLE
Is there a style option to inherit the parent application's bootstrap style?

### ISSUE THREAD

**Issue by walterdavis** [thredded/thredded#625]
I have a customized bootstrap layout, and I am having a lot of difficulty getting the thredded portion of the application to match. I am using the global application.html template, and have copied the thredded SCSS definitions into a file, and started fiddling with the base options to try to un-do the differences. But there are a lot of things I can't work out, like how the base font size trickles down to button fonts, and column widths, etc. Is there a different style option I can use that would do less, and render as vanilla Bootstrap as possible so my customizations would shine through?

**Comment by glebm** [comment]
My guess is you're using bootstrap 3 and are  importing bootstrap/scaffolding. Remove the bootstrap/scaffolding import, it sets the the html font-size to 10px braking all rem sizes.

**Comment by walterdavis** [comment]
That's an interesting idea, I will investigate. But my import only pulls in bootstrap, I don't have any line like bootstrap/scaffolding.

**Comment by glebm** [comment]
Are you using my bootstrap-sass gem?

**Comment by walterdavis** [comment]
Yes, Version 3.3.6.

Walter

**Comment by walterdavis** [comment]
I see what you’re talking about now, definitely coming from the bootstrap-sass gem. Is there a variable I can use to override that, or how do I keep the gem from loading it?

Walter

**Comment by walterdavis** [comment]
Okay, thanks for the tip, I added a rule to my overrides that resets <html> to 16px, and all looks really good not. Thanks again.

**Comment by glebm** [comment]
Replace `@import "bootstrap"` with an explicit list of imports from here https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/_bootstrap.scss but without `bootstrap/scaffolding`.

**Comment by walterdavis** [comment]
Excellent. Thanks so much.

Walter
