### ISSUE TITLE
timeago i18n doesn't work?

### ISSUE THREAD

**Issue by moondcr** [thredded/thredded#626]
In my `app/assets/javascripts/testapp_thredded.js`.

```
//= require thredded/dependencies/timeago
//= require timeago/locales/zh_CN
//= require thredded
```

in `config/application.rb`:

```
config.i18n.available_locales = %w(en zh-CN)
config.i18n.default_locale = :"zh-CN"
```

Are there something missed? I noticed `timeago.js` converted the date into English. 

Thanks a lot.

**Comment by glebm** [comment]
If run this in the inspector console, what does it return:

```javascript
document.querySelector('#thredded--container').dataset.threddedLocale
```

I'm thinking that maybe we need a `.replace('-', '_')` here:

https://github.com/thredded/thredded/blob/90c6f5fffd42ec1001c39dceb5ab5e875a71869d/app/assets/javascripts/thredded/components/time_stamps.es6#L11

**Comment by moondcr** [comment]
I am still not sure where should I place the file `components/time_stamps.es6` to.

**Comment by moondcr** [comment]
done!

**Comment by glebm** [comment]
Does the PR linked above fix the issue?

**Comment by moondcr** [comment]
@glebm yes, it did.
