### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by akashaggarwal7** [thredded/thredded#630]
How does an admin make a user a moderator/admin?
Also, if there is a moderator rank, what permissions does he have and can those permissions be set per user?

If there is a moderator rank but we can't have variable permissions for moderator, I might want to work on adding ACLs.

**Comment by glebm** [comment]
Please read https://github.com/thredded/thredded#permissions

**Comment by akashaggarwal7** [comment]
Sorry for the delay, I must have not seen that part before. Just to be clear, there is not existing panel where we can modify the permissions, right? Like making a user moderator/administrator or making a panel accessible only by certain users.

**Comment by glebm** [comment]
> Just to be clear, there is not existing panel where we can modify the permissions, right?

Right, this is out of scope for Thredded.
