### ISSUE TITLE
Question: Inbound / receive email posts?

### ISSUE THREAD

**Issue by chiptemm** [thredded/thredded#634]
Hi
Thredded looks great and a potential very useful addition to many apps as an engine.  Notifications are very useful- I wonder if responding to those emails and having them go back into the forum is on the roadmap?

**Comment by timdiggins** [comment]
@chiptemm we did have plans at one point (cf https://github.com/thredded/thredded/issues/371) but it's not on the agenda as far as I am aware. I can imagine it would be a great feature, but quite a big one to code up.

(a small point is that responding via email can lead to a very disjointed communication -- however in some cases may be very helpful)

**Comment by glebm** [comment]
Closing as it is not currently on the roadmap.
