### ISSUE TITLE
Per messageboard moderators and global moderators

### ISSUE THREAD

**Issue by akashaggarwal7** [thredded/thredded#636]
As suggested in the gitter chat, I would like to add per messageboard moderators and global moderators. We'd have two new tables, `messageboard_moderators` and `global_moderators`.

`global_moderators` would have 2 fields- 

1. `user_id`
2. `moderation_level`

`messageboard_moderators` would have the above 2 fields and an extra field `messageboard_id`.

The moderation permission can include multiple permissions like Create, Update, Delete, Archive, Sticky, Lock and Read. 
We could have the `moderation_level` field as a string of flags for each permission. The flag can then be queried and altered for its respective permission.

**Comment by glebm** [comment]
I think this is out of scope for Thredded core. Thredded should and does provide all the necessary "hooks" for you to implement this as a plugin, or in your own application.

**Comment by akashaggarwal7** [comment]
@glebm I don't see a problem having those features. In most cases medium to large sized(with respect to user base) have multiple moderators/roles. Plus we can always keep this optional. Or, if you think it can and should be done as a plugin instead, we could go with that approach too.

**Comment by glebm** [comment]
> @glebm I don't see a problem having those features.

Many sites have their own role management systems.

Instead of adding potentially unnecessary features to the core, put them in a plugin to keep the core focused and lightweight.

**Comment by akashaggarwal7** [comment]
Good point.
