### ISSUE TITLE
Trying to add new functionality on a fork

### ISSUE THREAD

**Issue by EthanBogart** [thredded/thredded#637]
Hey,

I am having a bit of trouble with adding a new table that expands on the thredded functionality. My goal is to have anonymized usernames per post, so I want to have a new table display_names that references the post and user, and contains a display_name attribute that can be looked up. My migration looks like this:

```
require 'thredded/base_migration'

class AddDisplayNames < ActiveRecord::Migration[5.1]
  def change
    create_table :display_names do |t|
      t.references :user, type: user_id_type, null: false, index: false
      t.references :post, null: false, index: false
      t.string :display_name, null: false
      
      t.index :post_id, name: :index_user_display_on_post_id
      t.index %i[user_id post_id], name: :index_user_display_on_user_id_post_id, unique: true
    end
  end
end
```

I get an error, though, on the user reference when I try to migrate:
```
StandardError: An error has occurred, this and all later migrations canceled:

undefined local variable or method `user_id_type' for #<AddDisplayNames:0x00000005f04470>
```

I can provide the full stack trace if it helps. Thank you!

**Comment by akashaggarwal7** [comment]
`t.references :user, type: user_id_type, null: false, index: false` Remove `type: user_id_type,` so it becomes `t.references :user, null: false, index: false`

**Comment by EthanBogart** [comment]
Thanks for the reply! Are you sure I can remove the user_id_type though? All the user references in the original thredded migration have that line in their code.

**Comment by EthanBogart** [comment]
That worked! Thank you!
