### ISSUE TITLE
Why shall I upgrade the database?

### ISSUE THREAD

**Issue by hopewise** [thredded/thredded#638]
I just installed fresh installation following instructions for pre-existing app, but I can see:

    To upgrade the database (in this example from v0.4 to the latest):

So, why shall I upgrade? isn't the db migrations for this gem already there and working properly?

Shall I run all db upgrades right after db migrate ?

**Comment by timdiggins** [comment]
@hopewise (sorry for slow response, responding in case still helpful for you or others). 

You say "I just installed fresh installation following instructions for pre-existing app"?
I take this to mean you have an existing rails app and you have added thredded to it following instructions https://github.com/thredded/thredded#adding-thredded-to-an-existing-rails-app.

In which case you don't need to do those upgrade instructions -- those are actually under a different section https://github.com/thredded/thredded#upgrading-an-existing-install.

But another note: the text "To upgrade the database (in this example from v0.4 to the latest)" only occurs in quite old versions of Thredded -- I hope you've installed the latest (v0.13.7 or https://github.com/thredded/thredded/blob/master/CHANGELOG.md#v0137)

BTW if you **are** upgrading from an old version, you are better off upgrading each point release separately (upgrade to v0.5 then to v0.6 etc -- tedious but safer -- also easier to catch if something stops working (e.g. css modifications) in your app), but I'm assuming that's not the case.

Please fire back if I've misunderstood.
