### ISSUE TITLE
Anonymized usernames

### ISSUE THREAD

**Issue by EthanBogart** [thredded/thredded#639]
Hey,

I'm working with an app that uses Thredded right now and one feature I have been trying to add is anonymized usernames, (ideally where we can insert a username that is linked to the post and user, so the username stays the same inside each post). I have a table already for this purpose. Does anyone have any suggestions on the easiest way to accomplish the anonymization?

Thank you!

**Comment by glebm** [comment]
One way to do this would be to override the partials where the username is rendered.

The post username is rendered in these two partials:

* Post header: [app/views/thredded/posts_common/_header.html.erb](https://github.com/thredded/thredded/blob/master/app/views/thredded/posts_common/_header.html.erb)
* Post header (used in the moderation UI): [app/views/thredded/posts_common/_header_with_user_and_topic.html.erb](https://github.com/thredded/thredded/blob/master/app/views/thredded/posts_common/_header_with_user_and_topic.html.erb)

The username is also rendered here:
* Messageboard list item: [app/views/thredded/messageboards/_messageboard.html.erb](https://github.com/thredded/thredded/blob/master/app/views/thredded/messageboards/_messageboard.html.erb#L15-L21)
* Topic list item: [app/views/thredded/topics/_topic.html.erb](https://github.com/thredded/thredded/blob/master/app/views/thredded/topics/_topic.html.erb#L27-L35)
* Topic header: [app/views/thredded/topics/_header.html.erb](https://github.com/thredded/thredded/blob/master/app/views/thredded/topics/_header.html.erb#L4)

**Comment by EthanBogart** [comment]
Thank you so much!

Right now I am working on the logic behind this feature, so I have a new display_name model and I've copied the `create_unless_exists` logic from the user_topic_follow model. In the code in app/helpers/thredded/application_helper.rb I'm trying to make use a new renderer function:

```
def user_anon_link(post)
  username = DisplayName.create_unless_exists(post.user, post.topic)
  render partial: 'thredded/users/anonlink', locals: { username: username }
end
```

Am I on the right track here? It's giving me an error that the post doesn't have a topic method, so I don't know how to get the topic id.

**Comment by glebm** [comment]
It's `post.postable` for historical reasons (posts and private posts used to be stored in the same table).

**Comment by EthanBogart** [comment]
I was able to get it running. Thank you so much for your help!
