### ISSUE TITLE
sitemap?

### ISSUE THREAD

**Issue by hopewise** [thredded/thredded#641]
I just installed thredded, but I am wondering if there is a sitemap generator ready to use for topics and message boards?

**Comment by glebm** [comment]
There isn't one, not that I know of

**Comment by jayroh** [comment]
Sitemap for the application that it's housed in? Could you define `sitemap` for us because I'm not entirely sure what the use case is.

**Comment by hopewise** [comment]
Sitemap for the forum topics, not for the application that it's hosted in, the application has its own sitemap, I asked about sitemap for thredded so that I can submit it to google besides my application sitemap..

**Comment by jayroh** [comment]
Ah, so a google sitemap. Got it. 

No, thredded does not have a generator for that. You _could_ use something like this: https://github.com/kjvarga/sitemap_generator

I've used that on other projects and it works great.
