### ISSUE TITLE
Custom name for queue?

### ISSUE THREAD

**Issue by hopewise** [thredded/thredded#642]
I've noticed that the name of queue is set to `default` as at:

https://github.com/thredded/thredded/blob/e2ebb1e418894c65f8b884821e2d7be085af3715/app/jobs/thredded/auto_follow_and_notify_job.rb#L5

so, how would I set the name for queue? 

also, I've noticed that the active job `AutoFollowAndNotifyJob` will iterate through all users to check their `thredded_user_preferences` thus, if there is a 100'000 user, it will check them all, the question is, would this create a pressure on the server that servers the app?

the scenario, is when adding thredded to a pre-existing app that has thousands of existing users, this would create un-required check for all of them each time we do a post, when having the default not to auto follow topic..

your thoughts please?

**Comment by timdiggins** [comment]
@hopewise the best route to change queue is to monkey-patch the file in your app. 

ie. 

create a file in your `app/jobs/thredded/auto_follow_and_notify_job.rb`

```ruby
require_dependency File.expand_path("../../app/jobs/thredded/auto_follow_and_notify_job.rb", Thredded::Engine.called_from)

# frozen_string_literal: true

module Thredded
  class AutoFollowAndNotifyJob < ::ActiveJob::Base
    queue_as :some_other_queue
  end
end
```

as for the iteration, I guess that AutoFollowUsers is iterating through all messageboard users -- if that is 100,000s of users that would need some performance testing before deployment. However there are instances of thredded with relatively large numbers of users (I don't personally manage any of those, so I can't comment on performance).

**Comment by glebm** [comment]
> would this create a pressure on the server that servers the app?

I have a Thredded install with ~60k users, it takes less than a second.
Note that this only happens in a background job, in a single thread.

**Comment by hopewise** [comment]
So, do I have to dedicate a worker server?

**Comment by glebm** [comment]
No. You do want your background jobs to run in a separate process.

**Comment by hopewise** [comment]
So, as for my existing app, what queue engine do you recommend that I can use on the same app server?

**Comment by glebm** [comment]
You can use any queue engine on the same server, none of them require a dedicated machine.
What do you mean by "server"?

If you use Redis, resque or sidekiq are good choices. Otherwise not sure which one is best right now but there are plenty of options: http://api.rubyonrails.org/v5.1/classes/ActiveJob/QueueAdapters.html.

**Comment by hopewise** [comment]
I am running my app in Elastic beanstalk env at AWS, by server I mean a dedicated machine, thanks for the list, I will check them.

**Comment by glebm** [comment]
Anything from that list will for you except `async` and `inline`.

**Comment by hopewise** [comment]
Yea, thank you.
