### ISSUE TITLE
Errors with @mention selector (users without spaces)

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded#643]
If you use the @ username selector and you select a username **without** a space (NB takes some work with the demo data to do this, as only Joe (default log in) has no spaces in his name -- so login as some other user, and then type `@Joe` in the post message), then:

* when you click the username or press return the drop down does not disappear.
* if you click or press return a second time, then the javascript hangs locking that page.

**Comment by glebm** [comment]
This has been fixed in https://github.com/thredded/thredded/commit/2bdb9cffd61954bd219a75f66665cd10991bdccb!

**Comment by timdiggins** [comment]
@glebm no, I don't think that did fix it -- I just reconfirmed this in master. I'll record a .mov to show the before / after.

**Comment by timdiggins** [comment]
Hey Gleb -- you can see the before 
https://www.dropbox.com/s/04agt1y5zdbqur2/master.mov?dl=0
and after https://www.dropbox.com/s/uxxnhf1wxs4cqku/fix-mention-bug%20.mov?dl=0

**Comment by glebm** [comment]
Ah, I get it now, thank you!
