### ISSUE TITLE
Confusion on how to move views outside of forums

### ISSUE THREAD

**Issue by dsdavis4** [thredded/thredded#647]
I am working on an community app that has a forum and private messaging features, as well as unrelated features. I started creating the app with discourse but quickly found out it was not as customizable or developer friendly as I hoped. Thredded seems to be exactly what I was looking for so I plan on using it as the base to build the rest of the app around. 

The only thing I am having trouble understanding is how to use the views else where in the app. The specific use case is that when the current_user is viewing another users profile, I want to be able to view all the private messages between the current_user and the the user of the profile being viewed (I plan on limiting private topics to just two users). I have been looking into the view hooks but from my understanding its not exactly what I am looking for because I am trying to display the view in a different part of the app, not within the engine. I have also looked into rendering the private messages partial in a similar manner to how a users posts can be displayed using the partial example in the docs but cant get it to work as I would expect. Of course I could use the Thredded models and generate my own views, but I would like to start developing the app with the 'correct' way of incorporating the views. Any guidance would be greatly appreciated!

**Comment by glebm** [comment]
Hi @dsdavis4! See https://github.com/thredded/thredded/wiki/Render-Thredded-partials-outside-of-Thredded

**Comment by dsdavis4** [comment]
Hey @glebm I have been using that Wiki as a guide but have not had success rendering private messages elsewhere in the app. It seems that I am still unable to use the render_posts method. I have tried the following.

Controller:
`@private_topic = Thredded::PrivateTopic.friendly_find!(1)
      @private_posts = Thredded::TopicPostsPageView.new(@user, @private_topic, @private_topic.posts.page(1).limit(3))`

Attempt 1: `<%= render_posts @private_posts,
                         partial: 'thredded/private_posts/private_post',
                         content_partial: 'thredded/private_posts/content',
                         locals: { actions: { quote: true } }  %>`

Attempt 2: `<%= Thredded::ApplicationHelper.render_posts @private_posts,
                         partial: 'thredded/private_posts/private_post',
                         content_partial: 'thredded/private_posts/content',
                         locals: { actions: { quote: true } }  %>`

Both of these methods give me undefined method render_posts

So then I thought I would try to use the renderer method described in the wiki by iterating over @private_posts.to_a
`<% @private_posts.each do |post| %>
            <%= Thredded::ApplicationController.renderer.new(request.env.slice('warden'))
                .render(partial: 'thredded/private_posts/private_post', locals: {private_post: post} ) %>
        <% end %>`

But this gives me an error that post is undefined. Even though `<% @private_posts.each do |post| %>
            <p><%= post %></p>
        <% end %>` prints out PostView objects. I could be wrong but it appears I need to use the render_posts method similar to how its done in thredded/app/views/thredded/private_topics/show.html.erb, but I cant figure out how to.

**Comment by dsdavis4** [comment]
So after a few hours I ended up getting to work with the following

```
<% @private_posts.each_with_index do |post, index| %>
            <%= Thredded::ApplicationController.renderer.new(request.env.slice('warden'))
                .render(partial: 'thredded/private_posts/private_post', locals: {private_post: post, post: @private_topic.posts[index]} ) %>
<% end %>
```

This seems messy to me, so if there is a better way of doing it please let me know!

**Comment by glebm** [comment]
`render_posts` is only available when rendering via `Thredded::ApplicationController.renderer`.
You can put the code in Attempt 1 into a partial, and render that partial with `Thredded::ApplicationController.renderer`.

**Comment by dsdavis4** [comment]
@glebm That was way cleaner then my solution and exactly what I was looking for. Thank you!
