### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by xamalekoum** [thredded/thredded#657]
Hello, my problem and the following, I did the first step of the installation of Thredded, but when I get to the stage "rake thredded: install: migrations db: migrate db: test: prepare" I do not really does not understand "the application of the application and the implementation of it."

Can you help me?
Thank you very much !

**Comment by jayroh** [comment]
Hey @xamalekoum - I'm not sure I understand your question. Could you re-phrase it?

Is the problem that you ran the rake tasks and they didn't work?

**Comment by xamalekoum** [comment]
Hey
this command is sending me this

[https://ibb.co/cVxhSm](url)

**Comment by jayroh** [comment]
Looks like you don't have a `User` model. Thredded needs some sort of `User` model to allow it to post _AS_ someone.

It's in the README here:

> Thredded needs to know the base application User model name and certain columns on it. Configure these in the initializer installed with the command above.

Do you have some sort of user or account model? When people sign up for your app/site where do you save their information?

**Comment by xamalekoum** [comment]
hello, I have nothing about the user and in the logic of things it should be registered in the database, if I add the gem Currency or Omniauth I would have this famous user class? Otherwise, I'll need a guide to set up the users

**Comment by xamalekoum** [comment]
hello, I have nothing about the user and in the logic of things it should be registered in the database, if I add the gem Currency or Omniauth I would have this famous user class? Otherwise, I'll need a guide to set up the users

**Comment by jayroh** [comment]
It sounds like you might need to start a little bit earlier down the line with Rails and set up your application with a User _first_

Check out devise for the auth library, maybe watch the Railscast about it: http://railscasts.com/episodes/209-devise-revised

Or the Gorails episode about it: https://gorails.com/episodes/user-authentication-with-devise
