### ISSUE TITLE
does not send email

### ISSUE THREAD

**Issue by hopewise** [thredded/thredded#658]
in the thredded initializer, I added:

    Thredded.notifiers = [Thredded::EmailNotifier.new]

however, there is no email sent for post notification, although I can see in the log:

```
Sent mail to  (20.4ms)
[ActiveJob] [Thredded::AutoFollowAndNotifyJob] [9a07c7b5-f6dc-4ee9-a8de-89771f9c4a6a] Date: Fri, 24 Nov 2017 08:58:42 +0200
Message-ID: <5a17c322e9ca4_176f73fd93f78b3f815990@iMac.local.mail>
Subject: =?UTF-8?Q?A_new_post_in_=E2=80=9Ctest=E2=80=9D?=
Mime-Version: 1.0
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: quoted-printable
X-SMTPAPI: {"category": ["thredded_Bugs Report","post_notification"]}
.
.
.
```
I am using sendgrid, and it's configured to send emails property, ex: forgot password emails by devise

any idea?

**Comment by jayroh** [comment]
Is that in your production environment that you see that in the logs?

If that shows up then it looks like it was successful. Can you send an
email manually from rails console in production? Does that succeed?

**Comment by hopewise** [comment]
No, it's in development, is there some setting I have to do?

**Comment by jayroh** [comment]
If it's in development then you have to set up whatever mail service you
want to use to actually send it.

Or use something like mailcatcher to view whatever would be sent outbound.

**Comment by hopewise** [comment]
I've tested it at production, I get this error:
`ArgumentError: SMTP From address may not be blank: nil`
with call stack:
```
ArgumentError: SMTP From address may not be blank: nil
  from mail/check_delivery_params.rb:13:in `check_from'
  from mail/check_delivery_params.rb:6:in `check'
  from mail/network/delivery_methods/smtp.rb:97:in `deliver!'
  from mail/message.rb:2149:in `do_delivery'
  from mail/message.rb:237:in `block in deliver'
  from action_mailer/base.rb:543:in `block in deliver_mail'
  from active_support/notifications.rb:164:in `block in instrument'
  from active_support/notifications/instrumenter.rb:20:in `instrument'
  from active_support/notifications.rb:164:in `instrument'
  from action_mailer/base.rb:541:in `deliver_mail'
  from mail/message.rb:237:in `deliver'
  from action_mailer/message_delivery.rb:85:in `deliver_now'
  from thredded/email_notifier.rb:14:in `new_post'
  from thredded/notify_following_users.rb:22:in `block in run'
  from thredded/notify_following_users.rb:19:in `each'
  from thredded/notify_following_users.rb:19:in `run'
  from thredded/auto_follow_and_notify_job.rb:11:in `perform'
```

then, I have tried to debug:
![screen shot 2017-11-25 at 4 27 11 pm](https://user-images.githubusercontent.com/1061157/33231396-8e9ccfc4-d1fd-11e7-844c-b7f2ba03a981.png)

    smtp_envelope_from result is nil:

![screen shot 2017-11-25 at 4 28 45 pm](https://user-images.githubusercontent.com/1061157/33231408-c3f3bb42-d1fd-11e7-81d6-ec5796a94728.png)

Only one user is notified as for my testing, and it has an email, but why I got from address nil as above??

**Comment by hopewise** [comment]
I tried to add `from` by overriding ApplicationMailer as here:
![screen shot 2017-11-25 at 6 15 10 pm](https://user-images.githubusercontent.com/1061157/33232314-ae50f840-d20c-11e7-807e-a7d97031a49e.png)
but it does not change anything..

**Comment by hopewise** [comment]
I found it, I have to define `Thredded.email_from` at the initializer! did not think that this will prevent sending the email .. should be added as a note at readme?

**Comment by jayroh** [comment]
It should probably raise an error upon instantiation of the notifier. Ill
make note of that bc it's a bit of a mysterious one.

Thank you Samir!

On Nov 25, 2017 11:57 AM, "Samir Sabri" <notifications@github.com> wrote:

I found it, I have to define Thredded.email_from at the initializer! did
not think that this will prevent sending the email .. should be added as a
note at readme?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/thredded/thredded/issues/658#issuecomment-346952571>,
or mute the thread

**Comment by hopewise** [comment]
You are welcome 👍
