### ISSUE TITLE
Issues with IE 11

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded#661]
Just a heads up that I seem to be getting some issues with IE 11:

One issue is "TypeError · Unable to get property 'replace' of undefined or null reference" during Thredded.onpageload (timeago replacement) -- looks like it might be a timing issue where IE differs from other browsers - https://stackoverflow.com/a/32526357/109175

Another issue is to do with Array.find (used in textcomplete) -- looks like we need a polyfill for this for IE (can't see we have one - not sure if babel polyfill will contain it)

I will start by seeing if I can replicate these automated error reports in vanilla dummy thredded in IE 11.

But might be worth setting up some of our tests on https://saucelabs.com/open-source ?

**Comment by glebm** [comment]
For reference, there is only one `Array#find` usage in textcomplete, here: https://github.com/yuku-t/textcomplete/blob/673a0ec1fcca13e6e0f434c28bc44cff8b962125/src/dropdown.js#L159

**Comment by glebm** [comment]
> One issue is "TypeError · Unable to get property 'replace' of undefined or null reference" during Thredded.onpageload (timeago replacement) -- looks like it might be a timing issue where IE differs from other browsers - stackoverflow.com/a/32526357/109175

Hmm I can't reproduce this one with IE11 on Windows 10

**Comment by glebm** [comment]
I've fixed the textcomplete issue, and I cannot replicate the timeago issue. A backtrace would help there.

**Comment by glebm** [comment]
Does it happen here?

https://github.com/thredded/thredded/blob/6abd3784d218399d0e2215551746908306f4cfff/app/assets/javascripts/thredded/components/time_stamps.es6#L11

Perhaps you have a custom `#thredded-container` without the locale attribute somewhere?

**Comment by timdiggins** [comment]
Gleb -- Yes, exactly, brilliant, So you reckon it will go away if I define the data-thredded-locale on the container? (It's only because I was hacking in the user show posts page and wanted posts to look roughly like they do in thredded rendered pages.)

I didn't notice (embarrassment) that this error report was only occurring on my user show posts page and not in thredded main.

Odd that it only seems to cause an error in IE. But I'm not an IE quirks expert by any means.

**Comment by glebm** [comment]
> So you reckon it will go away if I define the data-thredded-locale on the container?

Yes, it should!

> Odd that it only seems to cause an error in IE. But I'm not an IE quirks expert by any means.

Perhaps `Thredded.onPageLoad` doesn't get triggered at all in other browsers, because other browsers need this snippet as well:

https://github.com/thredded/thredded/blob/6abd3784d218399d0e2215551746908306f4cfff/app/views/thredded/shared/_page.html.erb#L11-L15

It may be best to actually render the user page via thredded.

`users/show.html.erb`:

```erb
<%= Thredded::ApplicationController.renderer.new(request.env.slice('warden'))
      .render(partial: 'users/thredded_user_page') %>
```

`users/_thredded_user_page.html.erb`:

```erb
<%= thredded_page do %>
  ...
  <%# Can render a partial from main_app here as well, using ::ApplicationController.renderer %>
<% end %>
```

https://github.com/thredded/thredded/wiki/Render-Thredded-partials-outside-of-Thredded

---

Alternatively, you could do it in the same way as https://github.com/thredded/thredded_create_app, which only renders the posts within thredded and has its own code for rendering timestamps.
