### ISSUE TITLE
Adding reCAPTCHA support to all the forms

### ISSUE THREAD

**Issue by akashaggarwal7** [thredded/thredded#667]
I wanted to add reCAPTCHA support to creating all kinds of posts. The devise part is easy, however I don't understand how to deal with forms from thredded. Any guidance would be much appreciated. Basically I don't know how can I edit the controllers from thredded in my app without having to override them totally.

**Comment by glebm** [comment]
Perhaps you can do this by monkey-patching the form objects'?

e.g.:

```ruby
module CheckRecaptchaOnSave
  def initialize(params = {})
    @recaptcha_param = params[:recaptcha]
    super(params)
  end
 
  def save
    return false if bad recaptcha
    super
  end
end

Thredded::TopicForm.prepend(CheckRecaptchaOnSave)

Thredded::NewTopicParams.prepend(Module.new do
  protected
  def new_topic_params
    super.permit(:recaptcha)
  end
end)
```

**Comment by glebm** [comment]
@akashaggarwal7 Step through with a debugger and you can figure out where the values comes from and how they are passed.

**Comment by akashaggarwal7** [comment]
Thanks!
