### ISSUE TITLE
Messageboard/group position

### ISSUE THREAD

**Issue by akashaggarwal7** [thredded/thredded#668]
How is the `position` calculated for a message board or a group?

**Comment by jayroh** [comment]
For groups: https://github.com/thredded/thredded/blob/master/app/view_models/thredded/messageboard_group_view.rb#L14

Messageboard:
https://github.com/thredded/thredded/blob/master/app/models/thredded/messageboard.rb#L64

**Comment by akashaggarwal7** [comment]
Fancy stuff, thanks!
