### ISSUE TITLE
Duplicate AJAX Requests Sent with Remote True if Thredded Assets and JQuery are imported

### ISSUE THREAD

**Issue by ishields** [thredded/thredded#672]
Hello
I've noticed an issuse in which if you attach "data-remote-true" to form elements, the ajax request on submit is being made twice.  I believe the issue is that multiple handlers for remote true are being initialized, one in JQuery UJS and the other in the thredded assets.
This is my appliction.js
```
....
// = require jquery
// = require jquery_ujs
//= require thredded
...
```
Here is a screen shot of my dev console showing two AJAX requests.  
![image](https://user-images.githubusercontent.com/3834864/34653753-97a0509a-f3be-11e7-82e3-6ace4b1708d5.png)

Removing either "jquery_ujs" or "thredded" removes the duplication of behavior.  As a result the form does not have two events listing for data-remote-true submits and as a result it works perfectly with only one ajax request.  

Digging into the thredded asset I see that it includes ujs in dependencies.js
//= require thredded/dependencies/ujs which then includes "rails_ujs".  I believe this is actually where the behavior duplication happens within the thredded engine.  

I'm wondering what the correct way forward is?  Should thredded have an option for include rails_ujs?  

Edit: It appears from this article https://gorails.com/forum/do-i-need-rails-ujs-and-jquery_ujs that rails ujs duplicates everything in jquery-ujs without jquery.  My guess is then I can just remove my own import of jquery ujs.  Still, does it make sense for this to be an optional dependency?  I can imagine situations where some people don't have an option and must use jquery-ujs.

**Comment by glebm** [comment]
Thredded uses Rails UJS by default, but you can tell it to use jQuery UJS instead.
This is already documented in the Readme: https://github.com/thredded/thredded#alternative-javascript-dependencies

> My guess is then I can just remove my own import of jquery ujs

I would recommend switching to Rails UJS in your app. jQuery UJS is deprecated. It's up to you though.
