### ISSUE TITLE
Undefined variable: "$thredded-small-spacing"

### ISSUE THREAD

**Issue by kennwilson** [thredded/thredded#677]
I'm setting up a test installation of Thredded as part of an existing Rails application. The installation seems to have gone smoothly, following the instructions in the README.

However, upon first page load, I'm running into this SASS exception:

    Sass::SyntaxError at /
    Undefined variable: "$thredded-small-spacing".

My installation is completely stock; I have not attempted to add new CSS styles or modified any of the SASS variables.

I'm running the latest version of Thredded with Ruby 2.3, Rails 4.2.8, and sass-rails 5.0.7. Based on the logs, the templates seem to be rendering fine; the error only comes up when the layout, and thus the CSS, are rendered.

Any thoughts on what the problem might be?

**Comment by glebm** [comment]
The variable is defined here: https://github.com/thredded/thredded/blob/d9d71c46b5cf33bc63f965dbe1db401314534c2b/app/assets/stylesheets/thredded/base/_variables.scss#L20

What is the full trace of the exception? Are you using your own layout with Thredded?

**Comment by kennwilson** [comment]
Nope, nothing custom at all. I'm just working on getting the application up and running for the first time, so I'm not using layouts of my own or anything like that. The default Thredded CSS should load normally.

Here's a trace. The Plan, Account, and Cart loading in the first few lines are part of my existing app.

    Started GET "/discuss" for 127.0.0.1 at 2018-01-18 13:03:41 -0800
    Processing by Thredded::MessageboardsController#index as HTML
      ESC[1mESC[36mPlan Load (0.4ms)ESC[0m  ESC[1mSELECT  `plans`.* FROM `plans` WHERE `plans`.`level` = 1 AND `plans`.`billing_period` = 1  ORDER BY `plans`.`id` ASC LIMIT 1ESC[0m
      ESC[1mESC[35mAccount Load (0.3ms)ESC[0m  SELECT  `accounts`.* FROM `accounts` WHERE `accounts`.`id` = 1004  ORDER BY `accounts`.`id` ASC LIMIT 1
      ESC[1mESC[36mCart Load (0.3ms)ESC[0m  ESC[1mSELECT  `carts`.* FROM `carts` WHERE `carts`.`account_id` = 1004  ORDER BY `carts`.`id` DESC LIMIT 1ESC[0m
      ESC[1mESC[35mSQL (4.3ms)ESC[0m  SELECT `thredded_messageboards`.`id` AS t0_r0, `thredded_messageboards`.`name` AS t0_r1, `thredded_messageboards`.`slug` AS t0_r2, `thredded_messageboards`.`description` AS t0_r3, `thredded_messageboards`.`topics_count` AS t0_r4, `thredded_messageboards`.`posts_count` AS t0_r5, `thredded_messageboards`.`position` AS t0_r6, `thredded_messageboards`.`last_topic_id` AS t0_r7, `thredded_messageboards`.`messageboard_group_id` AS t0_r8, `thredded_messageboards`.`created_at` AS t0_r9, `thredded_messageboards`.`updated_at` AS t0_r10, `thredded_messageboards`.`locked` AS t0_r11, `thredded_messageboard_groups`.`id` AS t1_r0, `thredded_messageboard_groups`.`name` AS t1_r1, `thredded_messageboard_groups`.`position` AS t1_r2, `thredded_messageboard_groups`.`created_at` AS t1_r3, `thredded_messageboard_groups`.`updated_at` AS t1_r4 FROM `thredded_messageboards` LEFT OUTER JOIN `thredded_messageboard_groups` ON `thredded_messageboard_groups`.`id` = `thredded_messageboards`.`messageboard_group_id`  ORDER BY coalesce(thredded_messageboard_groups.position, 0) asc, thredded_messageboard_groups.id asc, `thredded_messageboards`.`position` ASC, `thredded_messageboards`.`id` ASC
      Rendered /usr/local/lib/ruby/gems/2.3.0/gems/thredded-0.14.1/app/views/thredded/shared/_breadcrumbs.html.erb (1.3ms)
      Rendered /usr/local/lib/ruby/gems/2.3.0/gems/thredded-0.14.1/app/views/thredded/shared/nav/_moderation.html.erb (0.0ms)
      Rendered /usr/local/lib/ruby/gems/2.3.0/gems/thredded-0.14.1/app/views/thredded/shared/nav/_notification_preferences.html.erb (1.9ms)
      ESC[1mESC[36m (0.4ms)ESC[0m  ESC[1mSELECT COUNT(DISTINCT `thredded_private_topics`.`id`) FROM `thredded_private_topics` INNER JOIN `thredded_private_users` ON `thredded_private_users`.`private_topic_id` = `thredded_private_topics`.`id` LEFT OUTER JOIN `thredded_user_private_topic_read_states` ON `thredded_private_topics`.`id` = `thredded_user_private_topic_read_states`.`postable_id` AND `thredded_user_private_topic_read_states`.`user_id` = 1004 WHERE `thredded_private_users`.`user_id` = 1004 AND (`thredded_user_private_topic_read_states`.`id` IS NULL OR `thredded_user_private_topic_read_states`.`read_at` < `thredded_private_topics`.`last_post_at`)ESC[0m
      Rendered /usr/local/lib/ruby/gems/2.3.0/gems/thredded-0.14.1/app/views/thredded/shared/nav/_private_topics.html.erb (3.6ms)
      Rendered /usr/local/lib/ruby/gems/2.3.0/gems/thredded-0.14.1/app/views/thredded/shared/nav/_standalone_profile.html.erb (0.3ms)
      Rendered /usr/local/lib/ruby/gems/2.3.0/gems/thredded-0.14.1/app/views/thredded/shared/nav/_standalone.html.erb (0.3ms)
      Rendered /usr/local/lib/ruby/gems/2.3.0/gems/thredded-0.14.1/app/views/thredded/search/_form.html.erb (0.4ms)
      Rendered /usr/local/lib/ruby/gems/2.3.0/gems/thredded-0.14.1/app/views/thredded/shared/_nav.html.erb (25.4ms)
      Rendered /usr/local/lib/ruby/gems/2.3.0/gems/thredded-0.14.1/app/views/thredded/shared/_header.html.erb (27.9ms)
      Rendered /usr/local/lib/ruby/gems/2.3.0/gems/thredded-0.14.1/app/views/thredded/shared/_flash_messages.html.erb (0.1ms)
      ESC[1mESC[35mAccount Load (0.4ms)ESC[0m  SELECT `accounts`.* FROM `accounts` INNER JOIN `thredded_user_details` ON `thredded_user_details`.`user_id` = `accounts`.`id` WHERE (`thredded_user_details`.`last_seen_at` > '2018-01-18 20:58:41')
      Rendered /usr/local/lib/ruby/gems/2.3.0/gems/thredded-0.14.1/app/views/thredded/shared/_currently_online.html.erb (3.6ms)
      Rendered /usr/local/lib/ruby/gems/2.3.0/gems/thredded-0.14.1/app/views/thredded/shared/_page.html.erb (39.3ms)
      Rendered /usr/local/lib/ruby/gems/2.3.0/gems/thredded-0.14.1/app/views/thredded/messageboards/index.html.erb within layouts/thredded/application (46.3ms)
    Completed 401 Unauthorized in 9328ms (ActiveRecord: 6.1ms)
    
    Sass::SyntaxError - Undefined variable: "$thredded-small-spacing".:

**Comment by glebm** [comment]
I mean the Sass backtrace, i.e. where the undefined variable comes from. Also, what is the `sass` version in Gemfile.locK?

**Comment by kennwilson** [comment]
From `Gemfile.lock`:

    sass (3.4.25)
    sass-rails (5.0.7)

I'm afraid I'm not sure how to get a Sass backtrace, as I don't normally use Sass. Can you tell me what I should do here? Thanks.

**Comment by kennwilson** [comment]
I unfortunately can't update Sass due to other gem dependencies (foundation-rails depends on sass (< 3.5, >= 3.3.0)).

I may have a better trace for you though. I disabled `better_errors` and the standard Rails trace shows me more information about Sass. Is this helpful?

    Showing /usr/local/lib/ruby/gems/2.3.0/gems/thredded-0.14.1/app/views/layouts/thredded/application.html.erb where line #6 raised:
    
    Undefined variable: "$thredded-small-spacing".
    
    Extracted source (around line #20):
    
    18  border: solid 1px;
    19  border-radius: 3px;
    20  margin-bottom: $thredded-small-spacing;
    21  padding: $thredded-small-spacing;
    22  text-decoration: none;
    23 
    
    
    
    thredded (0.14.1) app/assets/stylesheets/thredded/base/_alerts.scss:20
    sass (3.4.22) lib/sass/script/tree/variable.rb:49:in `_perform'
    sass (3.4.22) lib/sass/script/tree/node.rb:58:in `perform'
    sass (3.4.22) lib/sass/tree/visitors/perform.rb:397:in `visit_prop'
    sass (3.4.22) lib/sass/tree/visitors/base.rb:36:in `visit'
    sass (3.4.22) lib/sass/tree/visitors/perform.rb:160:in `block in visit'
    sass (3.4.22) lib/sass/stack.rb:79:in `block in with_base'
    sass (3.4.22) lib/sass/stack.rb:115:in `with_frame'
    sass (3.4.22) lib/sass/stack.rb:79:in `with_base'
    sass (3.4.22) lib/sass/tree/visitors/perform.rb:160:in `visit'
    sass (3.4.22) lib/sass/tree/visitors/perform.rb:433:in `block (2 levels) in visit_rule'
    sass (3.4.22) lib/sass/tree/visitors/perform.rb:433:in `map'
    sass (3.4.22) lib/sass/tree/visitors/perform.rb:433:in `block in visit_rule'
    sass (3.4.22) lib/sass/tree/visitors/perform.rb:181:in `with_environment'
    sass (3.4.22) lib/sass/tree/visitors/perform.rb:431:in `visit_rule'
    sass (3.4.22) lib/sass/tree/visitors/base.rb:36:in `visit'
    sass (3.4.22) lib/sass/tree/visitors/perform.rb:160:in `block in visit'
    sass (3.4.22) lib/sass/stack.rb:79:in `block in with_base'
    sass (3.4.22) lib/sass/stack.rb:115:in `with_frame'
    sass (3.4.22) lib/sass/stack.rb:79:in `with_base'
    sass (3.4.22) lib/sass/tree/visitors/perform.rb:160:in `visit'
    sass (3.4.22) lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
    sass (3.4.22) lib/sass/tree/visitors/base.rb:52:in `map'
    sass (3.4.22) lib/sass/tree/visitors/base.rb:52:in `visit_children'
    sass (3.4.22) lib/sass/tree/visitors/perform.rb:169:in `block in visit_children'
    sass (3.4.22) lib/sass/tree/visitors/perform.rb:181:in `with_environment'
    sass (3.4.22) lib/sass/tree/visitors/perform.rb:168:in `visit_children'
    sass (3.4.22) lib/sass/tree/visitors/base.rb:36:in `block in visit'
    sass (3.4.22) lib/sass/tree/visitors/perform.rb:188:in `visit_root'
    sass (3.4.22) lib/sass/tree/visitors/base.rb:36:in `visit'
    sass (3.4.22) lib/sass/tree/visitors/perform.rb:159:in `visit'
    sass (3.4.22) lib/sass/tree/visitors/perform.rb:8:in `visit'
    sass (3.4.22) lib/sass/tree/root_node.rb:36:in `css_tree'
    sass (3.4.22) lib/sass/tree/root_node.rb:20:in `render'
    sass (3.4.22) lib/sass/engine.rb:281:in `render'
    sass-rails (5.0.7) lib/sass/rails/template.rb:47:in `evaluate'

**Comment by glebm** [comment]
Your stack trace shows Sass v3.4.**22** instead of v3.4.**25**. If that's different from Gemfile.lock, perhaps something is wrong in your environment.

If updating to v3.4.**25** doesn't help, perhaps you can try forking foundation-rails, removing the `sass` gem constraint, and seeing if that fixes it?

**Comment by kennwilson** [comment]
For simplicity, I just removed the Foundation gems from the app for testing. My Gemfile.lock now shows Sass 3.5.5 but I'm getting the same error with $thredded-small-spacing.

The trace is the same but we can see that sass 3.5.5 is now loaded:

    thredded (0.14.1) app/assets/stylesheets/thredded/base/_alerts.scss:20
    sass (3.5.5) lib/sass/script/tree/variable.rb:49:in `_perform'
    sass (3.5.5) lib/sass/script/tree/node.rb:50:in `perform'

Any thoughts? I'm a little perplexed.

**Comment by kennwilson** [comment]
For the former, just what you'd expect:

    $ find . | grep thredded
    ./app/assets/javascripts/thredded
    ./app/assets/javascripts/thredded/dependencies
    ./app/assets/javascripts/thredded/dependencies/ujs.js
    ./config/initializers/thredded.rb
    ./db/migrate/20180118000610_create_thredded.thredded.rb

And nothing for the latter.

The `ujs.js` file contains just two lines:

    //= require jquery3
    //= require jquery_ujs

**Comment by kennwilson** [comment]
Honestly, my preferred method is to set up a standalone app for Thredded, as noted in my other question about OAuth. I'm just taking a test drive with my existing code base as an easy way to evaluate it locally, ironically as a way to save myself the work of setting up a new app. But there's obviously something going on here so I think I'll refocus my efforts on the standalone since I won't be integrating directly with the existing site anyway.

Thanks for your help, I really appreciate that!

**Comment by glebm** [comment]
One last thing to try would be to `rm -rf tmp/`, while unlikely it could be a caching heisenbug.

**Comment by kennwilson** [comment]
Nope, didn't work, thanks though.
