### ISSUE TITLE
Change text formatting to be markdown + support for SOME bbcode

### ISSUE THREAD

**Issue by jayroh** [thredded/thredded#68]
Instead of markdown or bbcode, just standardize on markdown and let a large subset of bbcode be usable.

**Comment by glebm** [comment]
We should also add `rel="nofollow"` to links (and possibly target="_blank").

**Comment by jayroh** [comment]
100% yes on that, dude. Absolutely.

**Comment by jayroh** [comment]
This is probably a separate issue but I'll float it here ...

Looking through the newrelic and skylight stats I've noticed the rendering of posts ends up taking quite a while. It adds up.

That's more anecdotal than I would like so I'd probably have to write some benchmark code to prove this, but ... if that's actually the case it might make sense to cache the resulting output in a "rendered_content" text column.

**Comment by glebm** [comment]
:+1:

**Comment by jayroh** [comment]
> We should also add rel="nofollow" to links, and possibly target="_blank".

I can add another filter to the pipeline that takes care of this. I'll wait until this PR is merged.

**Comment by glebm** [comment]
@jayroh I think whitelist sanitizer can add attributes
