### ISSUE TITLE
Rarish bugs in onebox (can bring down demo)

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded#682]
and in testing it I broke the demo. Will remind myself how to reseed heroku, and fix it.

The bug (which I haven't validated without thredded yet) is when onebox is trying to wrap a pdf which has a broken link.

The bug occurs with the following URL, which is NOT broken, but whose https:// version **is** broken. So it looks like onebox is trying to grab a different url (which is a bug in itself) -- probably only when served from https -- it seems like onebox (or is it possibly thredded) is maybe trying to deal with mixed content errors, but in a dangerous way...

http://www.poettker.com/files/pdf/Produktkatalog_170912.pdf
vs
https://www.poettker.com/files/pdf/Produktkatalog_170912.pdf

Traceback (from thredded v0.13.8): https://gist.github.com/timdiggins/3eba95ba752092e3648b9a3a932df41b

**Comment by timdiggins** [comment]
Thinking out loud: This is a nightmare to work out how to test -- I suppose need to find out if it occurs with a simple broken link (seems unlikely), or just with the https - http switchover or a specific kind of broken link.

also maybe it only occurs when caching is on? (then testing would be excempt in any case).

so need to find out: 

* [ ] does it occur in vanilla onebox (e.g. discourse)
* [ ] does it occur with broken links (which are entered as https)
* [ ] does it occur with http server ever
* [ ] does it occur on local servers

**Comment by timdiggins** [comment]
I can replicate this with  thredded demo (v0.14.2) with onebox (1.8.39) 
When using content with an http:// link to a pdf file, onebox retrieves it using https, and then fails (breaking the page) if the SSL cert returns a err_ssl_unrecognized_name_alert. However, this doesn't happen if the page is a http

I can also validate it in onebox's test server: traceback: 
https://gist.github.com/timdiggins/a8de117d484a03e685b6dea1b1ecbff9

I've reported to https://meta.discourse.org/t/pdfonebox-part-of-onebox-gives-runtimeerror-when-pdf-is-hosted-on-poorly-configured-ssl/81064

**Comment by glebm** [comment]
Perhaps we should catch all errors from onebox, log them, and render the original input instead to avoid similar crashes in the future?

The onebox gem hasn't exactly been a pinnacle of reliability.

**Comment by timdiggins** [comment]
@glebm yes sounds good. Just looking at it now,  we can either cache the onebox failure response, or make failed oneboxes keep hitting their targets? 

Caching the failure sounds good, and can write a specific spec for OneboxFilter to check it works, but I'd like a spec which checks for the whole pipeline (in content_formatter_spec.rb) -- but don't see a way to turn off the special onebox caching for this spec (meaning only the first test run would be significant on any one machine).

thoughts?

**Comment by glebm** [comment]
By default, there is caching in development and tests, otherwise it's too slow: 

https://github.com/thredded/thredded/blob/ca7ea13d283f26f606585e290191755d92a530c6/lib/thredded/html_pipeline/onebox_filter.rb#L43-L46

To disable / reset it for a particular test, we can do something like this:

```ruby
Thredded::HtmlPipeline::OneboxFilter.onebox_views_cache = ActiveSupport::Cache::MemoryStore.new
Thredded::HtmlPipeline::OneboxFilter.onebox_data_cache = ActiveSupport::Cache::MemoryStore.new
```

**Comment by timdiggins** [comment]
Ok, that's seems easy enough. I'll see if I can fix this quickly
