### ISSUE TITLE
Secure Power Supply finds a home among extreme Oklahoma weather

### ISSUE THREAD

**Issue by luiseanrik** [thredded/thredded#685]
Oklahoma inhabitants are no outsiders to blasting summer electrical storms, hail and the terrible tornado thundering through their state. With such tempest potential and the historical backdrop of matrix blackouts they've caused, sun oriented inquisitive clients are progressively keen on reinforcement control. 

Given the high cost of section into the universe of lattice tied battery reinforcement frameworks, Ion Solar of Tulsa, OK, saw an open door for their clients to encounter reinforcement control through the Secure Power Supply (SPS) highlight of the Sunny Boy TL-US inverter.

# Opportunity power comes knocking

Since the mortgage holder's rooftop wasn't sufficiently vast or in a perfect world situated, the Ion [Solar generator](https://portablegeneratorsreview.com/best-solar-generator-reviews/) group planned a strong, ground-mount framework to withstand high breezes with an ideal introduction. The 9.5 kW framework is making power from 36 SolarWorld 270-watt monocrystalline modules, bolstered into a Sunny Boy 6000TL-US and 3000TL-US, each with SPS usefulness good to go. 

"With our extraordinary climate, our clients saw the estimation of SPS," said Seth Christ of Ion Solar. "The framework is planned to such an extent that on the off chance that they require more reinforcement abilities not far off, we can include a Sunny Island and a battery bank when the time comes. That is an incredible future chance to work with existing clients."

# More than enough power

At the mortgage holder's present rate of utilization, the framework will give 130 percent of their requests. Additional power sold back to the neighborhood utility will help accelerate the payback time frame for the framework and take into account future request development, should the need emerge. 

Notwithstanding a want to be vitality unbiased for monetary funds, the mortgage holder felt a powerful urge to introduce sun based to be all the more socially and earth dependable. On account of diminishing sun based vitality costs, individuals can have their sunlight based and keep a greater amount of their cash, as well.

**Comment by jayroh** [comment]
Yeah, no
