### ISSUE TITLE
Route calls should be called with engine namespace

### ISSUE THREAD

**Issue by michelson** [thredded/thredded#686]
Hello , I just installed this interesting engine into an existing rails app 4.2. 
I've got some deprecation warnings regarding the route generation. After some debugging I found out that in your views you are calling the routes directly. instead of doing `thredded.messageboards_path` you are calling `messageboards_path`. In terms of engine implementation that's a bad practice because the engine could collide with existing routes or just hit my issue: 
```
DEPRECATION WARNING: You are trying to generate the URL for a named route called "private_topics" but no such route was found. In the future, this will result
```
that ends rendering , in rails 4 , routes like `http://localhost:3000/forum/assets?action=new&controller=thredded%2Fmessageboards` but in rails 5 will raise error

**Comment by glebm** [comment]
> In terms of engine implementation that's a bad practice because the engine could collide with existing routes

That's not how route lookup works in an engine. Routes are looked up in the engine namespace when called from within an engine.

Check the backtrace to make sure it's not coming from your app, and also make sure you're on the latest Rails 4.2.x patch release.
