### ISSUE TITLE
User class is loaded before I18n

### ISSUE THREAD

**Issue by lukesarnacki** [thredded/thredded#689]
As shown in https://github.com/thredded/thredded/pull/688, the `User` class is loaded before I18n is loaded. I know that maybe use case shown in the PR is not the way you would write the code, but it was the simplest way I came up with to show a more general problem of `User` class being loaded too soon after installing "thredded". This also might have an impact on other libraries that need to be loaded before Rails models are loaded. While I know it might be considered an edge case, I think it is a huge change compared to how `User` class behaves without "thredded" installed.

**Comment by lukesarnacki** [comment]
@glebm don't you think that using dependency injection to not have to mix anything to user would be a better solution? 

I understand why this happens, but I spend a lot of time on debugging to find that out in a first place. Using dependency injection would prevent user from being polutted by thredded methods (and `User` model is huge in most apps anyway) and it would also prevent it from being loaded sooner thatn it would normally be.

**Comment by glebm** [comment]
I'm not sure what you mean by using dependency injection? We need to set up associations on the user so that the thredded entities that refer to a user are updated correctly when that user is deleted.

**Comment by lukesarnacki** [comment]
Ah, maybe I used the wrong term as this couldn't be classic dependency injection (you are right we need associations to make it work). But whatever it can be called, I meant using user as a dependency (association in this case) for engine model instead of using `User` directly.

I mean `Thredded::Account` for instance, which would be associated with user class. That way in case you need something from `User` model, you could use delegation instead of mixing and overwriting.

**Comment by lukesarnacki** [comment]
I will close this issue, because I am quite sure it cannot be done without changing the way thredded is initialized (it would have to be some explicit call in User class).

@glebm I am happy to open PR with `Thredded::Account` concept to have minimal changes in User class anyway as I think it would be a step into the right direction (even though it won't solve this particular issue). Let me know what you think about that.

**Comment by glebm** [comment]
We already have `Thredded::UserDetail` that does just that, if I understand your suggestion correctly.
