### ISSUE TITLE
Created by deleted user

### ISSUE THREAD

**Issue by FumbleBe** [thredded/thredded#692]
Hey guys,

every subject I create is created by "deleted user" except when I am in the the subject, reading it then it display the real user.

I have no other issues with my users...

Any idea why in the main pages it can't display user's names?

Thank you !

**Comment by glebm** [comment]
Perhaps you didn't copy the upgrade migration(s) when upgrading Thredded? Also check all your customizations.

**Comment by dkobia** [comment]
I have the same issue. No customizations yet. The `thredded_topics` table has the correct **user_id**. This issue only happens on the topic listings page. When I go to an actual topic, everything is fine.

**Comment by glebm** [comment]
The `last_user_id` column is used there:

https://github.com/thredded/thredded/blob/142afe8e12610f71734e7f851bb4954d6a43143e/app/views/thredded/topics/_topic.html.erb#L32

The initial assignment happens here:

https://github.com/thredded/thredded/blob/142afe8e12610f71734e7f851bb4954d6a43143e/app/models/thredded/topic.rb#L144-L156

**Comment by dkobia** [comment]
Thanks for the response @glebm. The `last_user_id` column is indeed empty. What would cause this?

**Comment by dkobia** [comment]
I found the problem and proposed a fix re: https://github.com/thredded/thredded/pull/760

**Comment by glebm** [comment]
Ah, makes sense. Since this seems to be a rare problem, no need to add an upgrade migration for this.

**Comment by FumbleBe** [comment]
Excuse my ignorance, but under a production environment, how can I correct this?

regards
