### ISSUE TITLE
Messaging: User selection dropdown not disappearing after selection

### ISSUE THREAD

**Issue by drusepth** [thredded/thredded#694]
After upgrading to the latest version (0.14.3) I'm now seeing a weird bug in private messaging where the dropdown for user selection is not disappearing after selecting a user to send a message to. [Here's a video of the interaction](https://drive.google.com/file/d/1AvUOusU9C9lEk8qrg1QdpxgBjOierALp/view?usp=sharing). 

Is anyone else able to reproduce this? If not, I'll close this and assume it's my own fault somewhere.

**Comment by glebm** [comment]
Looks like that user's name is "Amber " (with a trailing whitespace). I don't think we want to support trailing whitespace in usernames.

**Comment by drusepth** [comment]
Oh... wow. You're absolutely right. Jeez, I need some validators. I don't want to support trailing whitespace, either.
