### ISSUE TITLE
main_app link doesn't work for i18n

### ISSUE THREAD

**Issue by geraldtjy** [thredded/thredded#697]
Hi, I have a site that uses i18n for English and Simplified Chinese at the moment. In my routes.rb I have a route defined as:

`get '/language/:locale', to: 'settings#change_locale', as: :change_locale
`

So this goes to the Settings Controller that changes the route as follows:

```
class SettingsController < ApplicationController
  def change_locale
    l = params[:locale].to_s.strip
    l = I18n.available_locales.map(&:to_s).include?(l) ? l : I18n.default_locale
    ref = Rails.application.routes.recognize_path(request.referrer) || root_url
    ref[:locale] = l
    logger.debug(ref)
    redirect_to(ref)
  end
end
```

I then embed the link in my view as:
`<%= link_to 'Mandarin', change_locale_path("zh-CN") %>`

So when I click on the generated link 'https://example.com/language/zh-CN', it changes my route, for example, from https://example.com/en/forum to https://example.com/zh-CN/forum

This worked well before integrating Thredded. However since integrating the forum I had to use `<%= link_to 'Mandarin', main_app.change_locale_path("zh-CN") %>` (notice 'main_app' is prepended to the path because it's needed when using Thredded).

This causes a problem because the generated link gets messed up: the link becomes http://localhost:3000/language/en.zh-SG or http://localhost:3000/language/zh-SG.zh-SG (depending on which locale I am currently using). Because of that I can't switch languages properly any longer.

After a long time reviewing I'm at my wit's end so I hope to get any inputs on how I could possibly fix this. Thanks!

**Comment by geraldtjy** [comment]
**Note:** In my routes.rb I currently mount Thredded (`mount Thredded::Engine => 'forum'`) inside my locale scope: 

```
Rails.application.routes.draw do

  #other routes
  get '/language/:locale', to: 'settings#change_locale', as: :change_locale

  scope "(:locale)" do

    #other routes within locale

    mount Thredded::Engine => 'forum'

  end #end locale scope
end
```

So the routes are typically https://example.com/en/forum or https://example.com/zh-CN/forum, so the locale is in the resource path (as recommended in Rails). Somehow it seems using main_app to generate the path creates the wrong path. On views without Thredded we don't prepend main_app to the path, and have no problem.

**Comment by timdiggins** [comment]
Hi @geraldtjy 

I'm not 100% sure how to fix the problem you report with `main_app.change_locale_path`, but I think you could have a simpler option... I think you could just change the locale param within the link (ie not require a redirect). Something like:

    link_to "Mandarin", {locale: "zh-CN"}

which should (fingers crossed) generate the exact same url as the current page but with the locale param replaced with zh-CN. If that doesn't work there are other more painful options.

In order for Thredded to generate urls with the locale param set, I think you will need to get Thredded to generate these routes (Thredded doesn't "know" how it is mounted):

I assume you've done something similar to http://guides.rubyonrails.org/i18n.html#setting-the-locale-from-url-params

```
# app/controllers/application_controller.rb
def default_url_options
  { locale: I18n.locale }
end
```

I think if you monkey-patch thredded's application_controller to do the same thing it will then work. Add a new file in your code:
```
# app/controllers/thredded/application_controller.rb
require_dependency File.expand_path("../../app/controllers/thredded/application_controller",
  Thredded::Engine.called_from)

module Thredded
  class ApplicationController < ::ApplicationController
    def default_url_options
      { locale: I18n.locale }
    end
  end
end
```

**Comment by geraldtjy** [comment]
Hey @timdiggins, the first method worked out well, thank you very much for that! I'd much prefer to stick with that than any other workaround, but I reckon your alternative would work just as well, although most people should have no trouble with using the former solution if they face the same issue I did.

Thanks again! :)

**Comment by igorkasyanchuk** [comment]
I've added one addition to make it work in my app, maybe someone will need it:

```
require_dependency File.expand_path("../../app/controllers/thredded/application_controller",
  Thredded::Engine.called_from)

module Thredded
  class ApplicationController < ::ApplicationController
    def default_url_options(options = {})
      Thredded::UrlsHelper.default_url_options = { locale: I18n.locale }
      options.merge({ locale: I18n.locale })
    end
  end
end
```
