### ISSUE TITLE
Language select is missing

### ISSUE THREAD

**Issue by zevgeniy** [thredded/thredded#700]
why do I not see the language select in the header? and I can't find it in the source code anymore, but in your demo it's there. What am I missing?

<img width="1440" alt="screen shot 2018-05-16 at 17 55 18" src="https://user-images.githubusercontent.com/1324398/40128697-87df1324-5932-11e8-8f69-84acf0ed7869.png">

**Comment by glebm** [comment]
Language select is not a part of the engine. In the demo, the code for it is here:

https://github.com/thredded/thredded/blob/443216b5c8f8a683ba80582a4535923cc6f692f1/spec/dummy/app/views/shared/_header.html.erb#L30-L49

https://github.com/thredded/thredded/blob/443216b5c8f8a683ba80582a4535923cc6f692f1/spec/dummy/app/assets/stylesheets/_app_layout.scss#L164-L193

https://github.com/thredded/thredded/blob/443216b5c8f8a683ba80582a4535923cc6f692f1/spec/dummy/app/controllers/settings_controller.rb#L6-L15

https://github.com/thredded/thredded/blob/443216b5c8f8a683ba80582a4535923cc6f692f1/spec/dummy/config/routes.rb#L14
