### ISSUE TITLE
Trying to have Thredded.email_from customized for every user

### ISSUE THREAD

**Issue by yanshney** [thredded/thredded#706]
Good morning!

I am greatly enjoying the thredded gem, but what I have noticed is that for some people it is easier to respond to notification email itself than to click the link to go into the thredded messenger in my app (they don't notice that it is sent from the app account). Once they respond to the email it is sent to me, not to their intended adressee. Is there any way I can have notification sent from an email account of a user who actually sent them a message?

I was trying to play with Thredded.email_from field but when I try to customize this for every user, emails are just not getting sent out, and I could not find any example online of this field not being just a certain admin email. 

I understand that this is probably not the default behavior for most apps, but is there any way I can do it?

Thank you!

**Comment by glebm** [comment]
Perhaps you could add a prominent "Click here to reply" button to the email template? Letting the users reply directly is problematic as these replies won't appear on the website.

**Comment by yanshney** [comment]
Hi Gleb! 

Thank you for your quick reply. We do have this button in the email template, but many people still don't click the button and respond to the notification email itself. Their response does not go to the intended addressee but to our admin account because the notification is sent from our admin account. Would it be possible to have notification emails sent from the email of the user who actually sends the message in the app?

**Comment by glebm** [comment]
Thredded sends a single email to all participants via BCC:

https://github.com/thredded/thredded/blob/5510b35c7c4601f34ef718752c04ee52e690a662/app/notifiers/thredded/email_notifier.rb#L21-L23

Mailer: https://github.com/thredded/thredded/blob/master/app/mailers/thredded/private_topic_mailer.rb

You can monkey-patch these methods to send multiple emails with the appropriate `reply_to` field.

**Comment by yanshney** [comment]
It worked! Thank you so much Gleb!
