### ISSUE TITLE
Reg creation of message board

### ISSUE THREAD

**Issue by danielsamfdo** [thredded/thredded#707]
For the first time i created a messageboard group, then i try to create a message board. It always rollsback.

I saw that it was failing because of presence of last topic  in message board save in 

```
        **fail ActiveRecord::Rollback unless @messageboard.save**
        topic = Thredded::Topic.create!(
          messageboard: @messageboard,
          user: @user,
          title: first_topic_title
        )
        Thredded::Post.create!(
          messageboard: @messageboard,
          user: @user,
          postable: topic,
          content: first_topic_content
        )
        true
```

```
belongs_to :last_topic, class_name: 'Thredded::Topic', ****(Thredded.rails_gte_51? ? { optional: true } : { optional: true })**

```
in messageboard.rb

i have rails 5.0.7

so i also set it to be opt for both

```
belongs_to :last_topic, class_name: 'Thredded::Topic', **(Thredded.rails_gte_51? ? { optional: true } : { optional: true })

```

Then i faced an error 

<img width="1030" alt="screen shot 2018-06-04 at 11 02 53 pm" src="https://user-images.githubusercontent.com/5675079/40932279-7257ad68-684b-11e8-8b5f-69068f935cff.png">

**Comment by glebm** [comment]
Looks like the `@user` is a NullUser. Do you have `Thredded.current_user_method` set correctly in the initializer?

**Comment by danielsamfdo** [comment]
2.3.3 :001 > "current_#{Thredded.user_class_name.demodulize.underscore}"
 => "current_user" 
So the method is the default and current_user works well in my views, i use it to display name and email, as  current_user.name and current_user.email
So i don't know what the issue is.

Also Could you let  me know why in messageboard save transaction , we have 
"fail ActiveRecord::Rollback unless @messageboard.save"
Since it would clearly fail when we create a new message board and rails version is less than 5.1 , due to validation error ? (belongs to last_topic)

Thanks for your help...

**Comment by glebm** [comment]
belongs_to is optional by default in Rails < 5.1

**Comment by danielsamfdo** [comment]
Thredded.rails_gte_51? ? { optional: true }, {}

Isn't it optional only if rails_gte_51 ???? 

Src: https://github.com/thredded/thredded/blob/master/app/models/thredded/messageboard.rb#L36

**Comment by glebm** [comment]
In Rails < 5.1, all `belongs_to` associations are optional by default (there is no `optional:` argument). The error you're getting is unrelated to `last_topic`, in the screenshot it says `undefined method ... for Thredded::NullUser`.
