### ISSUE TITLE
Ruby 2.5

### ISSUE THREAD

**Issue by hopewise** [thredded/thredded#718]
Hi

After I have upgraded to ruby 2.5, I got this error:

    undefined method `locked?' for #<Thredded::Messageboard:0x00007fa76e3237b0> Did you mean? lock!

at:

```
def post?
      @user.thredded_admin? ||
        (!@messageboard.locked? || moderate?) &&
          @user.thredded_can_write_messageboards.include?(@messageboard)
    end
```

shall I not use ruby 2.5?

**Comment by glebm** [comment]
Hi, this looks like you've updated Thredded version but did not copy and run the upgrade migration.

See https://github.com/thredded/thredded#upgrading-an-existing-install and the list of upgrade migrations here https://github.com/thredded/thredded/tree/master/db/upgrade_migrations

**Comment by hopewise** [comment]
thanks!
