### ISSUE TITLE
Question: Integrating with RoR backend / Angular SPA front end

### ISSUE THREAD

**Issue by rdemuth** [thredded/thredded#719]
Hello,

For reasons that aren't that important, I have a system that uses a Ruby backend, but uses an Angular single page app for the UI.  That is, there are no RoR views, and the backend presents APIs to the Angular code in the browser.  I'm wondering whether integrating Thredded into such a system is feasible, whether anyone has done such a thing or anything similar, and if so, what pitfalls there might be.  

I've spend a day or so attempting to integrate, following the "Add Thredded to an existing Rails app" commentary, and have made progress, but was looking for general guidance.

I'm kind of new to Github, so I apologize if this isn't the proper place for a question such as this.

**Comment by timdiggins** [comment]
@rdemuth just scooping up some old questions -- I'm sure you've already solved this now, but to give my 10c. I have a webapp I maintain that has a thredded implementation and an AngularJS SPA (for only part of its pages). The key issue is to ensure that links from the angular part to the non-angular part are full page reloads (and it doesn't get caught by the angularjs router).

Hope that helps anyone who finds this in the future.
