### ISSUE TITLE
[Question] Rails 3.2

### ISSUE THREAD

**Issue by louim** [thredded/thredded#72]
Hello,

I was wondering what's making this rails 4+? I currently have à rails 3.2 app that I would like to add forum to. Do you think it could easily be backported to rails 3.2?

Thanks!

**Comment by jayroh** [comment]
Hey there @louim! This is a hard answer to reliably quantify but I have a hunch that outside of some gem dependencies, and adding the strong-params gem to your (parent) application, there might not be a whole lot necessary to get it working with 3.x

Now, I don't think it would be a *lot*, but I also think it's a non-trivial task that will take some trial and error and maybe some creative jury-rigging to get it to work.

I, personally, don't have this particular dependency in front of the projects I use thredded for so I won't be able to tackle this myself. However, I'd be more than happy to answer any questions or give any direction if this is something you would be willing to help on.

Thoughts?

**Comment by glebm** [comment]
Closing as obsolete

**Comment by jayroh** [comment]
Sayonara rails 3 👋🏼👋🏼👋🏼
