### ISSUE TITLE
When the title of a message board is too long, UI fails silently.

### ISSUE THREAD

**Issue by simonini** [thredded/thredded#720]
Hi!

When a user decides to put a very long title (more than 60 words) user gets no error.:

![schermata 2018-07-10 alle 17 43 56](https://user-images.githubusercontent.com/104249/42521330-d7da04ea-8468-11e8-8115-2010fd86e4dd.png)

![schermata 2018-07-10 alle 17 44 23](https://user-images.githubusercontent.com/104249/42521353-e5e90de2-8468-11e8-8647-23b7b54c7815.png)

**Comment by jayroh** [comment]
What's your expected behavior here? Is it a UI/design issue?

**Comment by glebm** [comment]
This shouldn't happen on the latest version. Did you copy and run the upgrade migrations when upgrading to v0.15?

**Comment by glebm** [comment]
Ah, sorry, confused this with the new topic screen.
