### ISSUE TITLE
Messages: Drop down selection for usernames obscures message box

### ISSUE THREAD

**Issue by zacharyedwardbull** [thredded/thredded#722]
The drop down selector remains even after a username has been selected if there are other names contained the typed in name. 

E.g. Zach & Zachary. Or Jo and Joanne 

![threddedbug](https://user-images.githubusercontent.com/34217412/43356707-af934e84-926d-11e8-8767-4db8231d840b.PNG)

**Comment by timdiggins** [comment]
@zacharyedwardbull thanks for reporting. 

Looking at this has made me think a couple of other things

#744 The users drop down should really be alphebatised.
#745 The dropdown of a participants of a private message doesn't work when there's an exact match

I think that this problem will go away if we fix #745. I'll have a go and see

**Comment by timdiggins** [comment]
Actually we ought to be hiding that drop down when you leave the text area. That's an easy fix.
