### ISSUE TITLE
Failed install due to pg error with rails 5.2+

### ISSUE THREAD

**Issue by jbillauer88** [thredded/thredded#726]
Getting this error when trying to create new thredded app

Installing pg 1.0.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

Also, been having trouble trying to add it to existing rails app

**Comment by glebm** [comment]
The error is unrelated to the gem. Most likely, your environment is missing the pq client library (e.g. `libpq-dev`), so the `pg` gem cannot compile its C extensions.
