### ISSUE TITLE
Trix, Quotes and Users

### ISSUE THREAD

**Issue by RALIST** [thredded/thredded#727]
Problem number one: 
When using trix, quotes didnt wrap in 'blockquotes' tag.
And problem number two:
how to make menition of user,  which was quoted?
Something like this: 
@User1 wrote: 
  here is quote from user1

And how to get all posts, where user was mentioned? 

Thanx a lot for your answers :)

**Comment by glebm** [comment]
Trix is not part of Thredded core. Consider contacting the author of the Trix integration code.

**Comment by andreibondarev** [comment]
@RALIST Did you figure out the solution to these issues when using Trix?
