### ISSUE TITLE
Conflict w/ thredded and rails_emoji_picker

### ISSUE THREAD

**Issue by leenyburger** [thredded/thredded#737]
I ran the rake task to install the emojis: 
`rake thredded:install:emoji`
Our app is using the `rails_emoji_picker` gem elsewhere. Thredded is working fine, but when I try to access emojis from `rails_emoji_picker` like so: `= content_with_emoji(comment.body)` I get the error: `undefined method 'asset_host' for Emoji:Module`. I've isolated it to the commit where thredded was added. Not sure if there is some kind of namespacing conflict? Any help would be appreciated!

**Comment by glebm** [comment]
Looks like the conflict is this: thredded depends on the `gemoji` v2.x gem, while `rails_emoji_picker` depends on the `emoji` gem. Both of these gems define the `Emoji` module.

**Comment by glebm** [comment]
Thredded no longer depends on `gemoji` as of v0.16.0.

https://github.com/thredded/thredded/releases/tag/v0.16.0
