### ISSUE TITLE
"Unread" icon to have "bell"

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded#750]
I think that the Unread "20" should have a bell (following) icon. in it, like the messageboards do.

<img width="892" alt="unread-icon" src="https://user-images.githubusercontent.com/18395/46881150-80457880-ce42-11e8-9b82-5ad6ebeeb7d0.png">

That would help to link in what the unread is.
Currently there's an invisible bell outside their area.

I would also like to make a helper function `inline_svg_once` that will inline svg (with id) unless it has already been inline before. This is both a performance/page load thing (though slightly) but also an html validity issue (cause we look them up by id). Any reason not to @glebm ?

**Comment by glebm** [comment]
SGTM, also `inline_svg_once` is a great idea.

**Comment by glebm** [comment]
Fixed in #751.
