### ISSUE TITLE
Question: private message with participant pre-populated

### ISSUE THREAD

**Issue by fastsyrup** [thredded/thredded#767]
Hi there,

I have mounted the thredded engine under /forum. Now in my web-app I would like to implement a "send msg" link below a given user_name.. Clicking on it should  open the thredded's /forum/private-topics/new? page with the recipient already pre-filled with this user's name.

I tried passing the user_name in as a query parameter, something like /forum/private-topics/new?user_name=xyz and then picking it up with custom javascript in order to populate the field dynamically. 
But unfortunately the url get's reset to /forum/private-topics/new? deleting my custom query parameter...

Any hints how I could easily implement my feature?

Best regards and thx in advance!

-   Mike

**Comment by glebm** [comment]
You don't need any custom JavaScript at all, simply use this for the URL:

```ruby
Thredded::UrlsHelper.send_private_message_path(current_user: current_user, to: user)
```

**Comment by fastsyrup** [comment]
Thanx for the quick response! I tried it, but it won't work correctly. It just shows the regular form without anything prepolulated or different. The only time I get a different reaction is if a) use_existing: true and current_user and user already have exchanged messages. Then instead of a new message it jumps to a existing thread between the two users...

Any idea what I'm doing wrong?

Using rails 5.1.6 and thredded 0.16.1

Cheers and thx!

**Comment by fastsyrup** [comment]
Ok, will do. Just one question, where in the demo app did you find this feature? Couldn't find anything related to prefilling the target user in the form...

**Comment by glebm** [comment]
In the demo, the user's page has a "Send private message link":

![private-message](https://user-images.githubusercontent.com/216339/48618496-75c25580-e991-11e8-884c-0ecce161f5b3.png)

**Comment by fastsyrup** [comment]
Hi,
I've found the problem and I think it is a bug. Using button_to does not work. 

So this doesn't work:

```
= button_to 'send msg', Thredded::UrlsHelper.send_private_message_path(current_user: current_user, to: r.owner), {:class => 'btn btn-success btn-xs', :method => 'get'}
```
But this does:
```
= link_to 'send msg', Thredded::UrlsHelper.send_private_message_path(current_user: current_user, to: r.owner), {:class => 'btn btn-success btn-xs'}
```

Thanks for your help!
