### ISSUE TITLE
More performant user provider for AtMentionFilter

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded#771]
As mentioned in #770, currently mentioned users are being fetched per post (and in parallel if `render_threads` > 1). There is a notion of a `user-provider`, but there's no way to currently provide them. Two ways to improve this from a performance point of view:

1) with parallel execution scan all posts in advance and aggregate users from posts and pre-fetch them within a shared UserProvider -- maybe this is a new step in the filters (prefetch). However this will mean an unnecessary scan and prefetch when the posts are already cached. However perhaps this is not such a big deal.

2) Alternatively (but this works with serial execution only - wouldn't work with render_threads > 1) don't provide in advance but have the same user provider across each post that fetches them when needed, and caches the results for future posts.  (This is quite a perf gain as within a thread the same users often get mentioned and rementioned).

**Comment by timdiggins** [comment]
Implementation notes: think this UsersProvider would be created in TopicPostsPageView and then passed to the PostView which would use it when provided (would need to wrap round the delegation of PostView#filtered_content -> Post#filtered_content)

**Comment by glebm** [comment]
For 2, the cache could be behind a Mutex, so that it'll work with render_threads > 1.
I have a similar cache here: https://github.com/glebm/i18n-tasks/blob/master/lib/i18n/tasks/concurrent/cache.rb

**Comment by glebm** [comment]
Well it would still reduce the number of User objects instantiated, but yeah getting all of them at once would be faster.

To avoid scanning and fetching users for cached posts, we can use this:

https://github.com/thredded/thredded/blob/759e3df3911198fb22fe87c4accd594fd5ee0ef5/lib/thredded/collection_to_strings_with_cache_renderer.rb#L40

**Comment by timdiggins** [comment]
Ah that looks good. Still thinking through aloud. The elements would be: 

* find the displayed posts which aren't cached
* pre-scan them for user-mentions 
* collect all the user name mappings as a user provider
* pass this user provider to the PostView

It is possible to remove (or replace) the AtMentionFilter from the pipeline -- but I think this is a relatively exotic customization.

In any case it might be good to provide a method (which could then be monkey-patched) to supply a UserProvider, given a bunch of posts. 

def Thredded.user_provider_for_topic(posts)
  Thredded::UserMentionPrescanner.new(posts).user_provider
end

This would in our augmented view do the prescanning on call, but could be replaced if required with the current version that just provides a proc, or nil if no AtMentionFilter is desired.

**Comment by glebm** [comment]
> It is possible to remove (or replace) the AtMentionFilter from the pipeline -- but I think this is a relatively exotic customization.

Posts can be rendered from other places (e.g. individually, or by user code), so I think it's better to keep it there and have the simple user provider as a fallback.

Perhaps the Prescanner should work as a wrapper around an existing `user_provider`?
Something like:

```ruby
Thredded::UserProviderPrescanner.new(posts, user_provider)
```
