### ISSUE TITLE
Multi-lingual messageboards & translation of posts?

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded#777]
I was wondering if anyone in the thredded community had used a thredded instance with a multilingual community and had integrated a translation tool (Google Cloud translation or Yandex translate api for example).

If the content is publicly available, it's possible to use tools to just translate the rendered web pages in place. But when the content is only available to registered users (and/or differentially available), and there are privacy concerns about using free tools (this would leak private data like crazy), then would need to pull together a more customised solution.

I'm not sure if this is something that warrants being in thredded core, or a plugin. Are there any useful libraries  (other than API wrappers). How best to preserve markup (translate rendered output, or translate original markdown and re-render).

I'm just starting thinking about this, so any pointers would be helpful.

**Comment by glebm** [comment]
> I'm not sure if this is something that warrants being in thredded core, or a plugin.

Pretty sure automated translation is a niche use case should be a plugin (and can easily be one).

> How best to preserve markup (translate rendered output, or translate original markdown and re-render).

Services like DeepL (GmbH) and Google Translate have allow preserving HTML ([1](https://github.com/glebm/i18n-tasks/blob/e2ffb334d79e5d61fb726dfefc7b4ced61ccb9f7/lib/i18n/tasks/translators/deepl_translator.rb#L28), [2](https://github.com/glebm/i18n-tasks/blob/e2ffb334d79e5d61fb726dfefc7b4ced61ccb9f7/lib/i18n/tasks/translators/google_translator.rb#L31)). Text not present in the markup can also come from oneboxes. So it's probably better to translate the HTML.
