### ISSUE TITLE
Web server can't connect to database in docker

### ISSUE THREAD

**Issue by 0x3A2B** [thredded/thredded#783]
mc@mc:~/thredded/thredded$ sudo docker-compose logs web
Attaching to thredded_web_1_c0c755d5280b
web_1_c0c755d5280b | Usage: script/wait-for-tcp ADDRESS PORT
web_1_c0c755d5280b | Wait for TCP connection at ADDRESS:PORT, retrying every 3 seconds, maximum 20 times.
web_1_c0c755d5280b | rake aborted!
web_1_c0c755d5280b | PG::ConnectionBad: invalid port number: "tcp://172.17.0.2:5432"
web_1_c0c755d5280b | /bundle/ruby/2.5.0/gems/pg-1.1.3/lib/pg.rb:56:in `initialize'
web_1_c0c755d5280b | /bundle/ruby/2.5.0/gems/pg-1.1.3/lib/pg.rb:56:in `new'
web_1_c0c755d5280b | /bundle/ruby/2.5.0/gems/pg-1.1.3/lib/pg.rb:56:in `connect'
web_1_c0c755d5280b | /bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:692:in `connect'
web_1_c0c755d5280b | /bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:223:in `initialize'
web_1_c0c755d5280b | /bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `new'
web_1_c0c755d5280b | /bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `postgresql_connection'
web_1_c0c755d5280b | /bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:811:in `new_connection'
web_1_c0c755d5280b | /bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:855:in `checkout_new_connection'
web_1_c0c755d5280b | /bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:834:in `try_to_checkout_new_connection'
web_1_c0c755d5280b | /bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:795:in `acquire_connection'
web_1_c0c755d5280b | /bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:523:in `checkout'
web_1_c0c755d5280b | /bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
web_1_c0c755d5280b | /bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:1010:in `retrieve_connection'
web_1_c0c755d5280b | /bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
web_1_c0c755d5280b | /bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_handling.rb:90:in `connection'
web_1_c0c755d5280b | /bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/tasks/database_tasks.rb:57:in `check_protected_environments!'
web_1_c0c755d5280b | /bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/railties/databases.rake:13:in `block (2 levels) in <top (required)>'
web_1_c0c755d5280b | /bundle/ruby/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
web_1_c0c755d5280b | /usr/bin/bundle:23:in `load'
web_1_c0c755d5280b | /usr/bin/bundle:23:in `<main>'
web_1_c0c755d5280b | Tasks: TOP => db:drop => app:db:drop => app:db:check_protected_environments
web_1_c0c755d5280b | (See full trace by running task with --trace)
I can connect 172.17.0.2:5432 on my machine but it seems web docker .What should I do?

**Comment by jayroh** [comment]
This is a docker and rails issue. I would suggest posting the question on StackOverflow.  Good luck!

**Comment by glebm** [comment]
@0x3A2B The docker commands for working on this gem are described here:

https://github.com/thredded/thredded#developing-and-testing-with-docker-compose

Not sure if they still work though.
