### ISSUE TITLE
Need to install kramdown-parser-gfm

### ISSUE THREAD

**Issue by sopwithpup** [thredded/thredded#786]
Just a heads up really, just install thredded, everything fine until tried to create a post and got a 

**kramdown has no parser to handle the specified input format: GFM**

After a bit of poking around I added the kramdown-parser-gfm gem to my gemfile which solved the problem

**Comment by glebm** [comment]
Looks like it was split out in the new v2.0.0. release https://github.com/gettalong/kramdown/blob/master/doc/news/release_2_0_0.page
