### ISSUE TITLE
Thredded CSS when Embedded 

### ISSUE THREAD

**Issue by FumbleBe** [thredded/thredded#787]
I have embedded Thredded in an application. It is working pretty well except that I can't find a way to apply css style to thredded...

So what I've done:

In my ./app/assets/stylesheets/application.scss file, I've added:

`@import "thredded";`

And, in initializers/thredded.rb file set:

`Thredded.layout = 'layouts/application'`

So now, thredded is "inside" my main application, and inherit some of the style, but it is not rendering well at all (for example, everything is align to the left...)

Any help are welcom. Sorry if it's a silly question, but I am not really in to dev...

**Comment by glebm** [comment]
Sounds like there are some styles in your application that override Thredded styles. Inspect the CSS properties to figure out what they are and where they're coming from.

**Comment by glebm** [comment]
A better approach to overriding colors and such is to set variables before importing Thredded, e.g.:

```scss
$thredded-nav-color: red;

@import "thredded";
```

Here is the full list of variables: https://github.com/thredded/thredded/blob/master/app/assets/stylesheets/thredded/base/_variables.scss

**Comment by FumbleBe** [comment]
I manage to make it works, but only if I set:
`config.assets.debug = true`

in my 

> ./config/environments/production.rb

 file

But doing this create some strange behavior in my main application :/

I'm not sure to understand why it's working with `config.assets.debug = true` and not without...

**Comment by glebm** [comment]
Perhaps you're precompiling assets in development, or checking your precompiled assets into git? Don't do that.

**Comment by FumbleBe** [comment]
And how can I avoid doing this ?

**Comment by glebm** [comment]
The default Rails setup does things right, so you've probably changed something somewhere. If you want people to help debug your issues, StackOverflow is a better platform than the issue tracker of one of your dependencies..

**Comment by FumbleBe** [comment]
I fully agree, thanks for you help and your patience ! regards
