### ISSUE TITLE
Forum per item

### ISSUE THREAD

**Issue by JamesWRC** [thredded/thredded#789]
Hi there I am wondering if it is at all possible to have a forum per user / item for my site?
So basically one item will have one forum, and another item will have another forum. so each item on my site will have the following:
![c7e849cbdee13a7af7e84ce2a3c87b1e](https://user-images.githubusercontent.com/38713144/52546879-e228e580-2e16-11e9-9f2b-fa58de7f25f9.png)
Thanks for your time,
James.

**Comment by timdiggins** [comment]
Probably too late for you @JamesWRC but just answering your question in case someone else stumbles on it.

There is no out of the box solution for this. 

But I think the closest matching pathway here is to programmatically create a separate MessageboardGroup per user or item. You'd probably want to never show "All messageboards" but instead show only a specific group. This is achievable, but difficult (in particular the kinds of customisations you need to do will be brittle, and need reviewing when Thredded updates).
