### ISSUE TITLE
@-mention filter replaces user.thredded_name but js autocomplete drops in user_name_column

### ISSUE THREAD

**Issue by mcsheu** [thredded/thredded#790]
I'm using Thredded 0.16.3 and in my Thredded initialization I have the following: 
```
Thredded.user_name_column = :unique_name

Thredded.user_display_name_method = :name
```
I'm running into a problem that when a user is typing in @-user, the js autocomplete helpfully drops in the user's unique_name (following the user_name_column), but then the at_mention_filter looks for the display_name to replace with a profile link: 

The guilty code is in thredded/html_pipeline/at_mention_filter.rb:47-54, the name variable should be `user.send(Thredded.user_name_column)`

```
@users_provider.call(names).each do |user|
  name = user.thredded_display_name
  maybe_quoted_name = name =~ /[., ()]/ ? %("#{name}") : name
  url = Thredded.user_path(@view_context, user)
  text_node_html.gsub!(
    /(^|[\s>])(@#{Regexp.escape maybe_quoted_name})([^a-z\d]|$)/i,
    %(\\1<a href="#{ERB::Util.html_escape url}">@#{ERB::Util.html_escape maybe_quoted_name}</a>\\3)
  )
```

**Comment by glebm** [comment]
Sounds right, please send a PR!
