### ISSUE TITLE
Pundit::NotDefinedError in Thredded::Messageboards#index

### ISSUE THREAD

**Issue by hopewise** [thredded/thredded#798]
I've upgraded from `'~> 0.15.3'` to `'~> 0.16.9'` , it seems so many things happened since then..
I get this error viewing previous old version message:
```
unable to find policy `Thredded::MessageboardViewPolicy` for `#<Thredded::MessageboardView:0x00007f8d49b858c0 @messageboard=#<Thredded::Messageboard id: 1, name: "Usabality", slug: "usabality", description: "Any idea that would enhance user experience", topics_count: 4, posts_count: 8, position: 1510477302, last_topic_id: 4, messageboard_group_id: nil, created_at: "2017-11-12 09:01:42", updated_at: "2018-06-30 10:40:18", locked: false>, @topics_count=4, @posts_count=8, @unread_topics_count=0, @unread_followed_topics_count=0>`
```

is there an easy way to fix this?

**Comment by glebm** [comment]
1. Have you copied and run the upgrade migration https://github.com/thredded/thredded#upgrading-an-existing-install
2. Have you customized Thredded somehow? What's in your config/initializers/thredded.rb?

**Comment by hopewise** [comment]
Thanks, I run the migration now and removed the customized `_messageboard.html.erb ` which was based on v0.15

its working now
