### ISSUE TITLE
some links are shown while use not signed in

### ISSUE THREAD

**Issue by hopewise** [thredded/thredded#799]
As in attachment, I can see links that should be shown only for authenticated user, I took this snapshot while user is not signed it yet:

![screen shot 2019-03-08 at 1 30 00 pm](https://user-images.githubusercontent.com/1061157/54026433-6a946f00-41a6-11e9-8041-6650ef8f531f.png)

**Comment by jayroh** [comment]
@hopewise do you mean some of the messageboards that you expect to see are NOT visible if you are signed out?

There must be some user permissions preventing those messageboards from showing up on that page.

**Comment by hopewise** [comment]
I mean the links `Private Messages` and `Notification Settings` are shown to non-signed in visitor, if click on them, it will ask to sign in first.. but why are they viewed while not signed it ..

**Comment by jayroh** [comment]
Oh, you should have said that in the first place! I thought you meant the
messageboards - I didn't even see the links at the top of your screenshot.

That being said - yeah man those should probably not be shown if you're
signed out. Might be a legit bug there.

**Comment by glebm** [comment]
They're shown by default to demonstrate the feature available if you sign in and to provide consistent navigation.

If you click on one of them, it will tell you to sign in to access the functionality.

**Comment by jayroh** [comment]
well hell that's a pretty good reason right there 😄

**Comment by glebm** [comment]
To display the sign-in form right there as well and if you use devise, add the following to `config/initializers/thredded.rb`:

```ruby
Rails.application.config.to_prepare do
  Thredded::ApplicationController.module_eval do
    rescue_from Thredded::Errors::LoginRequired do |exception|
      flash.now[:notice] = exception.message
      controller = Users::SessionsController.new # <-- or try Devise::SessionsController
      controller.request = request
      controller.request.env['devise.mapping'] = Devise.mappings[:user]
      controller.response = response
      controller.response_options = { status: :forbidden }
      controller.process(:new)
    end
  end
end
```
