### ISSUE TITLE
Thredded CSS/ Styles Issue

### ISSUE THREAD

**Issue by createwithneets** [thredded/thredded#803]
Hi there,

I've followed the instructions [here](https://www.rubydoc.info/gems/thredded/0.15.4#Application_layout) and am still having trouble with changing the styles in my embedded Thredded app. (Note: I've changed it to "Thredded.layout" in the initializer, have imported the stylesheet & javascript, etc.) 

What I've been trying is:

"$thredded-brand: #c16290;
@import "thredded";" 

in applications.scss.

**Comment by glebm** [comment]
In you `application.html.erb`, what do your `<%= stylesheet_link_tag ` look like?

**Comment by createwithneets** [comment]
@glebm  it's currently:

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <script src="https://js.stripe.com/v3/"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

**Comment by glebm** [comment]
That looks right. Are you sure you didn't accidentally precompile the assets in development or check in precompiled assets?

**Comment by createwithneets** [comment]
@glebm - Apologies as I'm still quite new (this is my first RoR app I'm attemping to build)- how would it have accidentally happened/ how do I check if it's happened?

**Comment by glebm** [comment]
Check the `public` directory, it shouldn't have any assets in it. If it does, simply delete them.

**Comment by glebm** [comment]
I've had a look at your `application.scss` here:

https://github.com/createwithneets/betty/blob/420f192b36eea757536d7c03080a3e9a81680ab8/app/assets/stylesheets/application.scss

1. Instead of using require, use `@import`, for *all* your SCSS.
2. The `import` statements should be outside of the comment block.
