### ISSUE TITLE
Markdown for tables text-align not working

### ISSUE THREAD

**Issue by mentor-dyun** [thredded/thredded#804]
ContentFormatter strips out the text-align attributes created by the markdown:
<th text-align="left"> sanitize => <th>

Added config/initializer/thredded.rb:
Thredded::ContentFormatter.whitelist[:elements] += %w[text-align]

But the text-align is still being ignored.

Here is an example of the markdown post. In github preview, it renders the text-align correctly. In Thredded, all the text-align is stripped.

| Tables        | Are           | Cool  |
| ------------- |:-------------| -----:|
| col 3 is      | left-aligned | right-align |

**Comment by glebm** [comment]
Marked as a bug, because we should have `text-align` whitelisted on `th` and `td` by default.

In the meantime, try this workaround:

```ruby
Thredded::ContentFormatter.whitelist.tap do |w|
  %w[th td].each do |t|
    w[:attributes][t] ||= []
    w[:attributes][t] += %w[style]
  end
  w[:css] ||= {}
  w[:css][:properties] ||= []
  w[:css][:properties] += %w[text-align]
end
```

**Comment by mentor-dyun** [comment]
Workaround is perfect! Thanks glebm.
