### ISSUE TITLE
Autonotify is extremely slow with large numbers of users

### ISSUE THREAD

**Issue by jflat06** [thredded/thredded#807]
I have about 900k users, and creating any post appears to do a query that goes over this entire userbase, 50k at a time. This is causing extreme slowdown of the site. 

I am testing this with the :async activejob, so it might not be as slow with a better job backend, but this still seems crazy to have to query all users. 

I have confirmed that this is indeed what is causing the slowdown by monkey patching the autonotify code with the following:

```
Thredded::AutofollowUsers.class_eval do
        def auto_followers
                Thredded.user_class.where(id: 0)
        end
end
```

Autonotification isn't a feature I care about, and it's surprising to me that it performs such an expensive operation. Is there a better way to disable auto-notify?

**Comment by glebm** [comment]
It should be possible to optimize `auto_followers` (it's just a couple of left joins).

What you have is an OK way to disable it in the meantime.

If you have 900k users you really shouldn't be running `async` -- it's only ever been intended for development and it silently drop all the queued jobs when you deploy, restart the server, etc.

**Comment by glebm** [comment]
@jflat06 Can you try out #808 and see if it fixes the issue for you?

**Comment by jflat06** [comment]
Awesome! - That pull request seems to have done it.

Super fast, and the auto-notify appears to be working correctly.

**Comment by glebm** [comment]
Thanks for confirming!
