### ISSUE TITLE
Feature request: view messageboards by messageboard_group

### ISSUE THREAD

**Issue by shelmire** [thredded/thredded#810]
Basically have a show view for messageboard_groups and links to them instead of the plain titles.

This is a request for an app I've been working on. I've got a rough draft pr that you can see here (I will just go ahead and use this personally if there's no interest in this feature here): https://github.com/shelmire/thredded/pull/1/files

(made a slight error here, the where clause in the show action should be where(group: params[:id]) not id: params[:id])

I've been extremely lazy about this because I didn't want to get into messing with the views, but perhaps a maintainer would be interested in finishing this up.

Content of that pr is useable under MIT license as the main project is.

**Comment by jayroh** [comment]
Could you post a screenshot of what that would look like? I'm having a tough time wrapping my head around what this is for.

**Comment by shelmire** [comment]
Sure, I've got this working in a staging environment. Main forum index looks the same, except that the group names are now links. Click on a link and you'll just see the messageboards associated with that group. This lets us link directly to groups of forums, rather than being stuck with either all or one. Functionally, my application has many Projects, and I want to provide a link to the several forums associated with a given project, rather than to the forum index or to individual forums.

<img width="984" alt="Screen Shot 2019-05-09 at 2 12 11 PM" src="https://user-images.githubusercontent.com/5061248/57476479-ab6f3980-7264-11e9-804c-05a88ac63077.png">
<img width="554" alt="Screen Shot 2019-05-09 at 2 12 24 PM" src="https://user-images.githubusercontent.com/5061248/57476481-ad38fd00-7264-11e9-8432-2fd22ba2ecf8.png">
<img width="1015" alt="Screen Shot 2019-05-09 at 2 12 32 PM" src="https://user-images.githubusercontent.com/5061248/57476489-af9b5700-7264-11e9-8002-8b5924c6b9da.png">

**Comment by glebm** [comment]
This does not seem like a common use case, so maybe as setting (off by default)?

Something like `Thredded.show_messageboard_group_page`?

**Comment by shelmire** [comment]
I'd actually argue that this is closer to the default forum use case. See, for example, https://www.mtgsalvation.com/forums ; each of the large forum groups has a number of subforums under it. Other forums such as https://www.carforums.com/forums/ or https://us.battle.net/forums/en/ similarly have separate pages for groups of forums (these were just random picks of forums I'm aware of). It's also a fairly innocuous change (I can't imagine this breaking anything).

**Comment by shelmire** [comment]
See working changes on https://github.com/shelmire/thredded (use `gem 'thredded', :git => 'https://github.com/shelmire/thredded.git'` in your Gemfile to test). I've deferred the question of whether groups should use a slug instead of id.
