### ISSUE TITLE
Gem::DependencyResolutionError while installing Thredded gem

### ISSUE THREAD

**Issue by Scribal** [thredded/thredded#821]
When attempting to install Thredded v0.9.3, I come across this issue:

```
ERROR:  While executing gem ... (Gem::DependencyResolutionError)
    conflicting dependencies nokogiri (~> 1.6.0) and nokogiri (>= 0)
  Activated nokogiri-1.8.4
  which does not match conflicting dependency (~> 1.6.0)

  Conflicting dependency chains:
    thredded (>= 0), 0.9.3 activated, depends on
    nokogiri (>= 0), 1.8.4 activated

  versus:
    thredded (>= 0), 0.9.3 activated, depends on
    jquery-rails (>= 4.2.1), 4.3.5 activated, depends on
    rails-dom-testing (< 3, >= 1), 1.0.7 activated, depends on
    nokogiri (~> 1.6.0)

  Gems matching nokogiri (~> 1.6.0):
    nokogiri-1.6.8.1-x64-mingw32
```
Any suggestions on what I should do to bypass this issue?

EDIT: I forgot to state, I'm currently running Ruby version `ruby 2.2.1p85 (2015-02-26 revision 49769) [x64-mingw32]` and Rails version `Rails 4.2.7.1`

**Comment by timdiggins** [comment]
Hi @Scribal sorry for the late response -- hope you solved it (maybe worth putting here what you did) - but it's really hard for us to help when you're using such old versions of thredded (v0.9.3 came out 3 years ago...) and ruby -- this kind of dependency lock problem is quite likely to happen. 

For future reference if someone else stumbles on this:

The "best" solution is to upgrade things (thredded, ruby, rails) to versions that are more recent and well supported.
 
If you can't upgrade thredded and/or other libraries, your best bet is to fork thredded and use that fork in your project, and loosen the dependencies it stipulates in its gemspec. This is a non-trivial way of fixing this, and full of risks and problems. But it would get around this issue.
