### ISSUE TITLE
svg icons not showing up

### ISSUE THREAD

**Issue by andreibondarev** [thredded/thredded#825]
Using `thredded 1.16.12`, `rails 5.2.3`. Just noticed that none of the svg icons were showing up. None of them are showing up on the demo site either: https://thredded.org/thredded/ (the settings cog or the private topics envelope for example)

**Comment by glebm** [comment]
The icons are only displayed on small screen sizes, when there is not enough space for text.

**Comment by andreibondarev** [comment]
@glebm You're right, sorry about that!
