### ISSUE TITLE
Removing default topic/thread from messageboard

### ISSUE THREAD

**Issue by mrfollowfollow** [thredded/thredded#827]
When i create a messageboard there is always a default topic/thread created called "Welcome to your messageboard's very first thread"

Is it possible to stop this from happening?

**Comment by glebm** [comment]
Only with a monkey-patch at the moment:

```ruby
# config/initializers/thredded.rb

Rails.application.config.to_prepare do
  # Only save the messageboard, do not create a demo thread:
  module Thredded::CreateMessageboard
    def run
     @messageboard.save
    end
  end
end
```

**Comment by mrfollowfollow** [comment]
Ah thanks very much. I will try that now and see if it works.

**Comment by mrfollowfollow** [comment]
running into an error: undefined method `new' for Thredded::CreateMessageboard:Module

```
@new_messageboard = Thredded::Messageboard.new(messageboard_params)
      authorize_creating @new_messageboard
      if Thredded::CreateMessageboard.new(@new_messageboard, thredded_current_user).run
        redirect_to root_path
      else
```

**Comment by glebm** [comment]
Ah, sorry, should be `class` not `module` in the monkey-patch (I've now updated the code above)

**Comment by mrfollowfollow** [comment]
perfect thanks thats worked a treat.
