### ISSUE TITLE
Allow non-admins to create messageboard

### ISSUE THREAD

**Issue by mrfollowfollow** [thredded/thredded#828]
Is it possible to allow non-admin members who are logged in to create a messageboard within an already existing group?

**Comment by glebm** [comment]
There is no way to do this via permissions but you can monkey-patch `Thredded::MessageboardPolicy#create?`:
https://github.com/thredded/thredded/blob/8b2cda3bdfe703992e307c7b811524838d74ed28/app/policies/thredded/messageboard_policy.rb#L32-L34
