### ISSUE TITLE
Running Thredded with Rails 6 and webpack

### ISSUE THREAD

**Issue by dazzaroonie** [thredded/thredded#831]
I can't seem to find a way to run Thredded using Rails 6 and webpack.

There is no way to require the javascript.

Any plans to have it on npm? Or is there a way I can have this working with Webpack?

**Comment by glebm** [comment]
Thredded still uses Sprockets, which Rails 6 still supports.

**Comment by glebm** [comment]
> Any plans to have it on npm?

Not currently.

> Or is there a way I can have this working with Webpack?

I found this on including JavaScript from gems directly into the pack:

https://github.com/rails/webpacker/issues/57#issuecomment-491317195

**Comment by glebm** [comment]
Perhaps Thredded can provide a helper for this

**Comment by glebm** [comment]
Released v0.16.4 with Webpack support!
https://github.com/thredded/thredded/blob/v0.16.14/README.md#add-thredded-javascripts-webpack
