### ISSUE TITLE
Using thredded without unique usernames?

### ISSUE THREAD

**Issue by pickhardt** [thredded/thredded#832]
I have a Rails site with a User model without unique usernames. It has columns for email and name (like "Jeff"), and a method display_name which users can configure to display full name "Jeff Pickhardt" or a short name "Jeff P."

Just curious if there are going to be unexpected bugs if I leave
`Thredded.user_name_column = :name`
or perhaps
`Thredded.user_name_column = :display_name`

I'm installing it now and I know it says you need a unique username but I'm wondering what'll happen if I don't use one?

**Comment by glebm** [comment]
At the very least, `@` mentions won't work correctly.

**Comment by pickhardt** [comment]
That's OK with me. I'm OK with disabling functionality like that, as long as it won't cause actual user-facing bugs.

**Comment by glebm** [comment]
Don't know what else may break. As this is not a supported configuration, it isn't tested.

**Comment by pickhardt** [comment]
Any chance this issue can be re-opened as a feature request: support sites without unique usernames? (It's OK to disable the at-mentions)

From debugging, I am finding some other things that are broken, like automatic email notifications.

Error performing Thredded::AutoFollowAndNotifyJob: RuntimeError (Column "forum_display_name" not found on table "users")

**Comment by glebm** [comment]
That error is unrelated, looks like you've configured `forum_display_name` to be the column name of User's display name in your initializer.

You could, as a hack, disable all at-mention functionality by monkey-patching `call` and `mentioned_users` in `Thredded::HtmlPipeline::AtMentionFilter`
https://github.com/thredded/thredded/blob/master/lib/thredded/html_pipeline/at_mention_filter.rb

**Comment by pickhardt** [comment]
I know, I did that because I didn't have an actual column in the database for usernames. It's my hacky workaround that I thought might work.

I ended up making some new unique column that's only used by thredded.
