### ISSUE TITLE
username in different table to devise

### ISSUE THREAD

**Issue by netpenthe** [thredded/thredded#835]
Hi

I have two tables - my devise table (Table A), but the username I want to use is in a different table (Table B) and it is joined.

The thredded initializer wants a symbol:
` Thredded.user_name_column = :username`

I was able to get around this by just doing a "def" in Table A that returned the username from Table B, that seemed to work for most pages, but some don't work with:
`Column "username" not found on table "teachers"`

Is there a better way to do this? Worse case I have to de-normalize and have the username in Table A as well.

**Comment by glebm** [comment]
I think you might have to denormalize, there is quite a few places where Thredded makes this assumption about usernames:

https://github.com/thredded/thredded/blob/51c60e9e7bc6f5fcb1f8b9de3c41ab053ec2e969/lib/thredded/users_provider.rb#L8-L9
https://github.com/thredded/thredded/blob/93e6dab7e5c76330aff829070a3464702e031b92/app/controllers/thredded/autocomplete_users_controller.rb#L31
https://github.com/thredded/thredded/blob/a2337c74bc266f10dd9076e1fc351168d2ccf201/app/forms/thredded/private_topic_form.rb#L42
https://github.com/thredded/thredded/blob/f1874fba333444255979c0789ba17f8dc24a4d6f/app/controllers/thredded/moderation_controller.rb#L64
https://github.com/thredded/thredded/blob/6e7dab4f3af4dd0a62bc73141978ab2b78550443/app/mailer_previews/thredded/base_mailer_preview.rb#L105

**Comment by netpenthe** [comment]
Thanks - appreciate that
