### ISSUE TITLE
can you set currently_online_enabled at run time?

### ISSUE THREAD

**Issue by netpenthe** [thredded/thredded#836]
I found 
`Thredded.currently_online_enabled = true`

But this can't be set in the initializer - I guess it has to be done at install time?

Is there a way to toggle this on and off? (short of hiding it with css?)

**Comment by glebm** [comment]
> But this can't be set in the initializer

All Thredded settings can and should be set in the initializer.

It's a global setting for all users. You can set change outside of the initializer but I'm not sure why you'd want to?

**Comment by netpenthe** [comment]
I added it to my initializer but now I get this when i try to start Puma: ?

`/config/initializers/thredded.rb:32:in `<top (required)>': undefined method `currently_online_enabled=' for Thredded:Module (NoMethodError)`

**Comment by netpenthe** [comment]
Oh i see what happened.

It installed 0.14.2 as I only have rails 4.2.6.

Upgrading to 4.2.10 seems difficult - any reason why 0.16.13 needs 4.2.10?

**Comment by jayroh** [comment]
Upgrading from 4.2.6 to 4.2.10 shouldn't be too bad (especially if your app is well tested). I recommend giving it a try and letting us know how it goes. Patch releases like that generally involve a whole lot less of a change.

As for "why" thredded 0.16.3 needs 4.2.10 -- there are probably some updates under the thredded hood that necessitate that upgrade. Maybe ActiveRecord related?
