### ISSUE TITLE
JS assets failing to load "couldn't find file 'thredded/dependencies' with type 'text/ecmascript-6'"

### ISSUE THREAD

**Issue by ericcf** [thredded/thredded#840]
Using Sprockets and a manifest file with `//=require thredded`, I'm getting the following error:
`couldn't find file 'thredded/dependencies' with type 'text/ecmascript-6'`. I'm stumped as to what to try next, but I assume I'm missing a proper configuration somewhere. Any help appreciated! Thanks.

**Comment by glebm** [comment]
Ah, you likely need to add the sprockets-es6 gem

**Comment by ericcf** [comment]
I have that gem installed, although it looks like Sprockets 4 should have that capability built in.

**Comment by glebm** [comment]
This shouldn't be an issue with recent versions of Thredded. If it is, please reopen with detailed information about your gems and configuration.
