### ISSUE TITLE
Last updated by html

### ISSUE THREAD

**Issue by hopewise** [thredded/thredded#843]
Hi

I am not sure when this started to happen, but I got `Last updated by html` instead of user name as here: https://dcaclab.com/forum

Any idea?

**Comment by timdiggins** [comment]
Hi @hopewise this looks like your system can't find your locale / local files and or/there is no fallback locale (Last updated by html is a human-readable version of the key that i18n uses to look up the translation from your locale files). 

This could be set in your code with something looking like `config.i18n.default_locale =` or `I18n.locale =`.  

Also check your code for configuration like `config.i18n.fallbacks = true` if this is the case you'll need to change it as per https://github.com/ruby-i18n/i18n/releases/tag/v1.1.0

**Comment by timdiggins** [comment]
Closing this as it's quite old now. Please reopen if you have more information.
