### ISSUE TITLE
Translation for Korean language

### ISSUE THREAD

**Issue by tkang** [thredded/thredded#844]
Dear All, 

I came across this wonderful project while preparing for my personal project need. Thank you all for building this wonderful stuff, first of all.

I noticed translation for Korean language is missing and am adding translation yml file for myself. Is there a guideline for me to contribute my translation file to this project?

Best Regards,
Taeho

**Comment by jayroh** [comment]
Hey @tkang - thanks for checking in and expressing interest 😄 

To contribute a new translation your best bet would be to copy over the english locale `en.yml` to `ko.yml` and start translating the values there. I don't _think_ there's much to it outside of that. (I trust that @glebm will correct me if/where I'm wrong though.)
