### ISSUE TITLE
Currently online not working

### ISSUE THREAD

**Issue by Klashe** [thredded/thredded#849]
Happy New Year!
So first of all when I installed Thredded this morning, most things worked out of the box except for some few things.
When I tried to make my UI consistent by changing 
`# The layout for rendering Thredded views.
Thredded.layout = 'thredded/application'`

to 

`# The layout for rendering Thredded views.
Thredded.layout = 'application'`

Things made sense with that but I noticed the currently online didn't show up my name (as th only person online.). I reversed the process back to normal and things worked fine.

How do I fix the 'currently online' while maintaining a global UI?

**Comment by timdiggins** [comment]
Happy New Year! I don't have the answer, but it may to know whether the currently online box is not being rendered in the html (`aside.thredded--currently-online`), or whether it is being rendered but is not visible for some reason.  Can you compare the HTML returned for both options?

**Comment by Klashe** [comment]
Yes, it was rendered. Modifying the Thredded.layout caused it but is there other ways to fix this?

**Comment by glebm** [comment]
Sounds like your CSS styles are interfering with the `aside.thredded--currently-online` element. Inspect and fix your app styles.
