### ISSUE TITLE
How to use custom profile url?

### ISSUE THREAD

**Issue by Klashe** [thredded/thredded#850]
I don't have the normal users_path set up in my app as I'm using a custom route for the users profile as seen below
`  get ':username', to: 'profiles#show', as: :profile
   get ':username/edit', to: 'profiles#edit', as: :edit_profile
   patch ':username/edit', to: 'profiles#update', as: :update_profile`

I tried tweaking the below code but it won't work.

`Thredded.user_path = ->(user) {
  user_path = :"#{Thredded.user_class_name.demodulize.underscore}_path"
  main_app.respond_to?(user_path) ? main_app.send(user_path, user) : "/users/#{user.to_param}"
}`

How do I fix please?

**Comment by timdiggins** [comment]
Looks like your user path should be `profile_path(user.name)` and you should prefix that with main_app in case calling from within the thredded engine, so `main_app.profile_path(user.name)`

Couple of questions:

1) can you post the actual code you wrote (the tweaked code)? I'm guessing should be something like 

    ```ruby
    Thredded.user_path = ->(user) {  main_app.profile_path(user.name) }
    ```


2) when you say "it won't work" -- in what way -- does it give you an error / traceback, or does it not linkify the usernames, or does it give the wrong url for the usernames?

**Comment by Klashe** [comment]
Thanks @timdiggins . The profile link works fine outside the thredded engine as in main_app.profile_path(user.username).

I changed the initial thredded settings from
`Thredded.user_path = ->(user) {
  user_path = :"#{Thredded.user_class_name.demodulize.underscore}_path"
  main_app.respond_to?(user_path) ? main_app.send(user_path, user) : "/users/#{user.to_param}"
}` 
to
`Thredded.profile_path(user.username) = ->(user) {
  main_app.profile_path(user.username) = :"#{Thredded.user_class_name.demodulize.underscore}_path"
  main_app.respond_to?(profile_path) ? main_app.send(profile_path, user.username) : "/:username"
}`

I'm getting the error
`syntax error, unexpected '=', expecting end-of-input (SyntaxError)
...d.profile_path(user.username) = ->(user) {`

**Comment by glebm** [comment]
There a syntax error in your code just as Ruby says.

Try this instead:

```ruby
Thredded.user_path = ->(user) {  main_app.profile_path(user.username) }
```
