### ISSUE TITLE
How do i add decription and content fields. 

### ISSUE THREAD

**Issue by Klashe** [thredded/thredded#851]
I only have the title field for the new message board and topic. How do I display the description and content fields in the form as it is in the demo app?

**Comment by Klashe** [comment]
Edit:
I figured out this isn't showing because I modified the initializer's
`Thredded.layout = 'application'` because I want my app UI be consistent. 

When this was reversed to the default, it worked fine.

**Comment by glebm** [comment]
Sounds like your app CSS styles interfering with Thredded styles are the cause of this one as well.
