### ISSUE TITLE
Activity displays wrong tag (started vs posted)

### ISSUE THREAD

**Issue by stephlaf** [thredded/thredded#870]
Hello 👋🏼 ,

Just found a little error in a conditional, which had the wrong 'tag' (`started`, `posted`) displayed alongside a `post` in `moderation/activity`

Screenshot of original logic. Notice the last `post` is the one tagged as **started**, and the 1st one as **posted**

![image](https://user-images.githubusercontent.com/37821714/84442189-21ce3000-ac0b-11ea-90da-8da51a052ab2.png)

This is the original Thredded code in `_header_with_user_and_topic.html.erb` \:
```
      if topic.first_post == post.to_model
        t 'thredded.users.user_started_topic_html', user_link: post_user_link, topic_link: topic_link
      else
        t 'thredded.users.user_posted_in_topic_html', user_link: post_user_link, topic_link: topic_link
      end
```
Here is my fix:

```
      if topic.posts.first == post.to_model
        t 'thredded.users.user_started_topic_html', user_link: post_user_link, topic_link: topic_link
      else
        t 'thredded.users.user_posted_in_topic_html', user_link: post_user_link, topic_link: topic_link
      end
```
which gives us:

![image](https://user-images.githubusercontent.com/37821714/84442579-ea13b800-ac0b-11ea-870d-13b3decdfaf6.png)

Hopes this helps! Thanks again for your work 🙏🏻

**Comment by BGMP** [comment]
Have you considered submitting a pull request, or is there any reason why this shouldn't go into one? It's a lot more helpful to propose changes that way rather than in issues.
