### ISSUE TITLE
实现中文搜索

### ISSUE THREAD

**Issue by zengfengbo** [thredded/thredded#876]
# 安装postgres中文分词组件 zhparser
https://github.com/amutu/zhparser
## 需要安装依赖
$ sudo apt install postgresql-server-dev-11
$ sudo apt-get install postgresql-contrib-11

# 导入拓展
```sql
-- create the extension
CREATE EXTENSION zhparser;

-- 查看已安装的扩展
SELECT * FROM pg_extension;

CREATE TEXT SEARCH CONFIGURATION zhparser (PARSER = zhparser);
ALTER TEXT SEARCH CONFIGURATION zhparser ADD MAPPING FOR n,v,a,i,e,l,j WITH simple;

-- 测试
SELECT * FROM ts_parse('zhparser', 'hello world! 2010年保障房建设在全国范围内获全面启动，从中央到地方纷纷加大了保障房的建设和投入力度 。2011年，保障房进入了更大规模的建设阶段。住房城乡建设部党组书记、部长姜伟新去年底在全国住房城乡建设工作会议上表示，要继续推进保障性安居工程建设。');
```

# 修改postgres配置文件
$ vi /etc/postgresql/11/main/postgresql.conf
```conf
zhparser.multi_short = true #短词复合: 1
zhparser.multi_duality = true  #散字二元复合: 2
zhparser.multi_zmain = true  #重要单字复合: 4
zhparser.multi_zall = false  #全部单字复合: 8
```

# rails下修改thredded全文搜索的默认配置

$ vi config/initializers/thredded.rb

```ruby
if Rails.env.production?
  DbTextSearch::FullText::DEFAULT_PG_TS_CONFIG = %q('zhparser')
end
```

# 重启postgres服务

以ubuntu为例。其他linux版本，命令可能不同。
$ sudo service postgresql restart

**Comment by timdiggins** [comment]
Hi @zengfengbo, thanks for contribution, but it doesn't look like an issue, looks more like instructions/ how to? I'm closing this for now, but please reopen if you can re-phrase it (would be helpful if you can pre-translate it too!)
