### ISSUE TITLE
clean install builds (including travis) are failing because of DatabaseCleaner changes

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded#883]
Travis builds (and would be the same for clean install on any dev machine) seem to be failing because of a database cleaner changes in v2.0 (removal of `reset_ids` arg, which was deprecated in [1.99](https://github.com/DatabaseCleaner/database_cleaner/blob/main/History.rdoc#label-1.99.0+2021-01-31))

We can either pin database_cleaner to `~> 1.0` and we're done, or pin to `~> 2.0` and fix. Also DatabaseCleaner is a bit old school in rails post 5.1. Should we still be using it, or maybe only for rails 4.2 - 5.1 builds?  Ugh?

Should we maybe be dropping *some* old versions of rails? I know it's great to be so backward supporting, but it also makes working on the gem so much harder...

Thoughts? Quickest fix might be to pin to `~> 1.0`, so I might try that initially

**Comment by glebm** [comment]
I don't mind dropping support for some old versions of Rails, certainly 4.x can go

**Comment by glebm** [comment]
5.0 as well

**Comment by timdiggins** [comment]
So this particular issue is fixed by #884.

I've made a separate issue for dropping older rails ( #885). Maybe will look at that at some point, but for now I'm keen to get us back to green on CI as that will make everything easier... will discuss that in #881...
