### ISSUE TITLE
Can threaded allow for multiple user_class?

### ISSUE THREAD

**Issue by staycreativedesign** [thredded/thredded#890]
Thredded.user_class = 'Contractor'
Thredded.user_class = 'Member  

Would this work?

**Comment by jayroh** [comment]
It would not.

At this point I believe you would be best served by using one roll-up user class and designating permissions on a per-object basis.  What's the use-case you're trying to address by asking the question above? Maybe we can help

**Comment by staycreativedesign** [comment]
I just had 2 different type of users so instead having Users I creted the models.
