### ISSUE TITLE
Undefined method `size' for #<Thredded::TopicsPageView:0x00007ff4d7f311b8>

### ISSUE THREAD

**Issue by RailsCod3rFuture** [thredded/thredded#901]
After clicking on a topic, I receive undefined method `size' for #<Thredded::TopicsPageView:0x00007ff4d7f311b8>
for this code block.

```
NoMethodError in Thredded::Topics#index
def size         
@collection.size       
end
```

Any idea why this happens?

**Comment by JsfasdF252** [comment]
{work in progress}

**Comment by timdiggins** [comment]
I think this is because Thredded doesn't yet support rails 6.1 / rails master (7 alpha) -- after a long delay I'm working on this. Redirecting you to #877. Please reopen if this was with rails 6.0 or earlier.
