### ISSUE TITLE
Test against Rails main on CI, and nightly too -- and rails 7 too

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded#904]
It took us a long time to get up to speed on rails 6.1. Obviously we're an community driven project dependent on a handful of developers with limited time etc. But I think our tooling could give us a bit more support.

It strikes me we add rails master to our test matrix for this (and for plugins too). When rails 7 is released we add that to the matrix and continue to test against rails master.

As a bonus, we could also run a nightly or weekly test (https://docs.travis-ci.com/user/cron-jobs/) that runs our tests to see if anything has broken (both on rails and on published versions)

**Comment by rickychilcott** [comment]
I heard an interview with Rafael Franca today and he said that Rails 7 is likely to be released in the next week or so. He's not 100% sure, but he said 2nd week of Dec. Can we add the [alpha2 release](https://github.com/rails/rails/tree/v7.0.0.alpha2) and also add [rails/rails#master](https://github.com/rails/rails/tree/main)

**Comment by timdiggins** [comment]
done in #919
