### ISSUE TITLE
Guys, your website is dead

### ISSUE THREAD

**Issue by alfuken** [thredded/thredded#908]
Link in the sidebar to https://thredded.org points to non-existing heroku application.

**Comment by rickychilcott** [comment]
:(

**Comment by pickhardt** [comment]
Should I add this to https://github.com/pickhardt/maintainers-wanted?

Does this gem still work with Rails 7?

**Comment by timdiggins** [comment]
Hey thanks for the reminder. I've fixed this now. 

@pickhardt We can always do with more contributors (it's really just me contributing at present). And if anyone contributes a lot, they can maintain it too! 

We aren't testing against rails 7 or rails master. but you know, it's on the roadmap.

I would really welcome a PR to test against rails 7  -- you should be able to get it building on travis on your own branch. And if there are then failures, PRs to fix...

**Comment by timdiggins** [comment]
@pickhardt update. Not yet working on rails 7.0, but very close: watch #919
