### ISSUE TITLE
Translation Errors: wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by rakshassa** [thredded/thredded#943]
[actionview (6.1.4.7) lib/action_view/helpers/translation_helper.rb:70:in `translate'](http://localhost:3333/forum/admin/moderation#)
[thredded (1.0.0) app/views/thredded/moderation/_post_moderation_record.html.erb:22](http://localhost:3333/forum/admin/moderation#)

Using ruby '3.1.1'

Changing the translation method invocation to this will fix the problem:
<%= t('thredded.moderation.post_approved_html',
          moderator: user_link(record.moderator),
          time_ago:  time_ago(record.created_at)) %>

**Comment by timdiggins** [comment]
@rakshassa thanks for the notification. Are you able to create a PR for this (ideally with a spec showing the error is fixed?)
