### ISSUE TITLE
Incompatible with: html-pipeline version > 2

### ISSUE THREAD

**Issue by rakshassa** [thredded/thredded#944]
HTML::Pipeline::SanitizationFilter::WHITELIST is not available.

NOTE: using gem 'html-pipeline', '~> 1.11' fixes this problem.

**Comment by timdiggins** [comment]
@rakshassa thanks for reporting this. I think this changed was introduced in html-pipeline actually in v2.13.1 (but reverted accidentally in v2.14.0 and reintroduced in v2.14.1). PR #945 (merged) largely addresses this by limiting the version, but a new PR will allow for more recent (> 2.14.1) versions of html-pipeline.

**Comment by timdiggins** [comment]
Again, thanks for the report! This should be fixed in master because of #951 -- please reopen this you have anything to add.
