### ISSUE TITLE
Moderation record error: undefined local variable or method `post' for #<ActionView::Base:0x00000000025580>

### ISSUE THREAD

**Issue by zebleck** [thredded/thredded#946]
After clicking on moderation history in the navbar, it yielded this error:

undefined local variable or method `post' for #<ActionView::Base:0x00000000025580>

No params were given to the page.

Trace:
[thredded (e41338d5dea7) app/views/thredded/moderation/_post_moderation_record_content.html.erb:2](http://127.0.0.1:3000/forum/admin/moderation/history#)
[actionview (6.1.4.7) lib/action_view/base.rb:247:in `public_send'](http://127.0.0.1:3000/forum/admin/moderation/history#)
[actionview (6.1.4.7) lib/action_view/base.rb:247:in `_run'](http://127.0.0.1:3000/forum/admin/moderation/history#)
[actionview (6.1.4.7) lib/action_view/template.rb:154:in `block in render'](http://127.0.0.1:3000/forum/admin/moderation/history#)
[activesupport (6.1.4.7) lib/active_support/notifications.rb:205:in `instrument'](http://127.0.0.1:3000/forum/admin/moderation/history#)
[actionview (6.1.4.7) lib/action_view/template.rb:345:in `instrument_render_template'](http://127.0.0.1:3000/forum/admin/moderation/history#)
[actionview (6.1.4.7) lib/action_view/template.rb:152:in `render'](http://127.0.0.1:3000/forum/admin/moderation/history#)
[actionview (6.1.4.7) lib/action_view/renderer/partial_renderer.rb:285:in `block in render_partial_template'](http://127.0.0.1:3000/forum/admin/moderation/history#)
[activesupport (6.1.4.7) lib/active_support/notifications.rb:203:in `block in instrument'](http://127.0.0.1:3000/forum/admin/moderation/history#)
[activesupport (6.1.4.7) lib/active_support/notifications/instrumenter.rb:24:in `instrument'](http://127.0.0.1:3000/forum/admin/moderation/history#)
[activesupport (6.1.4.7) lib/active_support/notifications.rb:203:in `instrument'](http://127.0.0.1:3000/forum/admin/moderation/history#)
[actionview (6.1.4.7) lib/action_view/renderer/partial_renderer.rb:280:in `render_partial_template'](http://127.0.0.1:3000/forum/admin/moderation/history#)
[actionview (6.1.4.7) lib/action_view/renderer/object_renderer.rb:31:in `render_partial_template'](http://127.0.0.1:3000/forum/admin/moderation/history#)
[actionview (6.1.4.7) lib/action_view/renderer/partial_renderer.rb:271:in `render'](http://127.0.0.1:3000/forum/admin/moderation/history#)
[actionview (6.1.4.7) lib/action_view/renderer/object_renderer.rb:16:in `render_object_with_partial'](http://127.0.0.1:3000/forum/admin/moderation/history#)
[thredded (e41338d5dea7) lib/thredded/collection_to_strings_with_cache_renderer.rb:106:in `block in render_partials_serial'](http://127.0.0.1:3000/forum/admin/moderation/history#)
[thredded (e41338d5dea7) lib/thredded/collection_to_strings_with_cache_renderer.rb:104:in `map'](http://127.0.0.1:3000/forum/admin/moderation/history#)
[thredded (e41338d5dea7) lib/thredded/collection_to_strings_with_cache_renderer.rb:104:in `render_partials_serial'](http://127.0.0.1:3000/forum/admin/moderation/history#)
[thredded (e41338d5dea7) lib/thredded/collection_to_strings_with_cache_renderer.rb:90:in `block (3 levels) in render_partials'](http://127.0.0.1:3000/forum/admin/moderation/history#)
[activerecord (6.1.4.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:462:in `with_connection'](http://127.0.0.1:3000/forum/admin/moderation/history#)
[thredded (e41338d5dea7) lib/thredded/collection_to_strings_with_cache_renderer.rb:89:in `block (2 levels) in render_partials'](http://127.0.0.1:3000/forum/admin/moderation/history#)

**Comment by timdiggins** [comment]
Thanks for your report. I can see that I can recreate this by visiting the history (http://localhost:3000/thredded/admin/moderation/history) after there has been some moderation activity.

It gives different errors in different versions of rails. 

In rails 7 it gives 

```
ArgumentError in Thredded::ModerationController#history
missing keywords: :records, :associations

./app/models/thredded/post_moderation_record.rb:36:in `new'
./app/models/thredded/post_moderation_record.rb:36:in `block in <class:PostModerationRecord>'
./app/controllers/thredded/moderation_controller.rb:23:in `history'
```

The moderation system is I think under tested and we need a few system specs for it (and then fixes)

**Comment by timdiggins** [comment]
@zebleck actually the issue that I found with rails 7 has nothing to do with your issue under rails 6.0 which I can't reproduce. What version of thredded do you have installed (check your Gemfile.lock).

**Comment by timdiggins** [comment]
We've included some specs and fixes for known issues in moderation in https://github.com/thredded/thredded/pull/954.

@zebleck  if you have more data on your specific issue and can reproduce it under Thredded v1+ please reopen.
