### ISSUE TITLE
Request for code explanation

### ISSUE THREAD

**Issue by drusepth** [thredded/thredded#959]
Hey y'all, I'm trying to trace down what looks like a performance issue with my forums in the moderation area. For a long time now, `ModerationController#pending` has taken a looong time to load -- specifically, the page now takes over 10 minutes to fully load when using my production database at peak load times.

I traced the query taking so long to run to be
```sql
SELECT "thredded_posts".* FROM "thredded_posts"
  WHERE "thredded_posts"."deleted_at" IS NULL
  AND (
    "thredded_posts".created_at = (
      SELECT MAX(p2.created_at) from "thredded_posts" p2
      WHERE p2.postable_id = "thredded_posts".postable_id
    )
  )
  AND "thredded_posts"."postable_id" IN (...list of 23 integers...)
  ORDER BY "thredded_posts"."created_at" ASC, "thredded_posts"."id" ASC;
```
which is generated from [ModerationController#pending L11-13](https://github.com/thredded/thredded/blob/main/app/controllers/thredded/moderation_controller.rb#L11). The rest of the queries on the page look great; it's just this one that's so slow.

The specific culprit seems to be the `preload_first_topic_post` scope but, honestly, I've never seen preloading done like this and it's a bit over my head; I was wondering if someone might be able to shed some light on the design goal of this scope. Code pasted below for convenience:

```ruby
    scope :preload_first_topic_post, -> {
      posts_table_name = Thredded::Post.quoted_table_name
      result = all
      owners_by_id = result.each_with_object({}) do |r, h|
        h[r.post.postable_id] = r.post.postable if r.post
      end
      next result if owners_by_id.empty?
      preloader = Thredded::Compat.association_preloader(
        records: owners_by_id.values, associations: [:first_post],
        scope: Thredded::Post.unscoped.where(<<~SQL.delete("\n"))
          #{posts_table_name}.created_at = (
          SELECT MAX(p2.created_at) from #{posts_table_name} p2 WHERE p2.postable_id = #{posts_table_name}.postable_id)
        SQL
      )
      preloader[0].preloaded_records.each do |post|
        topic = owners_by_id.delete(post.postable_id)
        next unless topic
        topic.association(:first_post).target = post
      end
      result
    }
```

If I don't preload this way (by commenting out the scope in `ModerationController#pending`), the page load time drops from 10+ minutes to ~15 seconds, but the resulting N+1 query hammers my db pool pretty hard. Quite a sizable decrease! But still pretty darn long for a web request.

I'm still trying to investigate why this query is running so slow, how to speed it up, and would love to report any results I find, but any advice you might be able to provide in the meantime would be much appreciated!

For context, I'm working with a DB that has around 3 million `Thredded::Post`s and testing on the latest v1.0.1 gem release. The page load time also seems to scale pretty drastically on the number of posts in the moderation queue. For the huge load times above, I had 50+ items in queue; as the queue gets smaller, the page gets significantly faster to load.

**Comment by drusepth** [comment]
Upon closer inspection, I'm gonna guess that this issue is due to me extending posts with `acts_as_paranoid`, which adds the `deleted_at=nil` default scope -- but there isn't an index for [:id, :deleted_at]. I've since cleared my queue and am unable to repro by just adding random posts to it, but I'll add that missing index if the issue pops up again.

**Comment by glebm** [comment]
Glad to hear thtedded scales up to so many posts!
Yeah, the missing index is probably what caused it to be so slow.
