### ISSUE TITLE
Handling default root_urls with a subdirectory in url_helpers

### ISSUE THREAD

**Issue by laraferroni** [thredded/thredded#963]
We have a rails project with a default root of "/garage".  As such we redirect any URL that doesn't start with /garage e.g. project529.com/forum to project529.com/garage/forum. Unfortunately, this creates a problem for POST urls that are created with the thredded url_helpers... they don't include the garage, so get 302 redirected, which turns them into GET requests after the redirect. 

I tried to mounting the Thredded engine to 'garage/forum', but that doesn't work either because of the way we handle /garage in the path. 

Is there a way to override the url_helper methods to add the subdrectory (without me just tinkering with the gem directly)

**Comment by timdiggins** [comment]
@laraferroni do you have any other routes-mounted engines that are working in this case? (e.g. Devise?) and if so how are you indicating to those gems the root url?

Does rails know about the subpath? (https://guides.rubyonrails.org/configuring.html#deploy-to-a-subdirectory-relative-url-root) If not, that's where I would start (and remove any hardcoded references to garage in your code).

But if it does, then I wonder why Thredded isn't picking it up.

**Comment by timdiggins** [comment]
I'm closing this now as there was no response - but feel free to reply if you have more info
