### ISSUE TITLE
thredded_create_app-0.2.2 requires Ruby version ~> 2.5. The current ruby version is 3.0.3.

### ISSUE THREAD

**Issue by unixneo** [thredded/thredded#978]
FYI (in case this has not been addressed)

```bash
macos$ gem install --user thredded_create_app
ERROR:  Error installing thredded_create_app:
	thredded_create_app-0.2.2 requires Ruby version ~> 2.5. The current ruby version is 3.0.3.
```

FYI:

```bash
macos$ rbenv global
3.0.3
```

**Comment by timdiggins** [comment]
Thanks for noticing. https://github.com/thredded/thredded_create_app needs updating - it hasn't been updated in a while. 
In the meantime, you'd have to use a much earlier (out of date) version of ruby to get it to work.

**Comment by x1wins** [comment]
@timdiggins Is there any other way? I used ruby 3.2.2. I have same problem.

**Comment by timdiggins** [comment]
I don't think we're (I'm) going to be able to support [thredded_create_app](https://github.com/thredded/thredded_create_app). 
There's enough work to do keeping thredded going.
