### ISSUE TITLE
thredded.org website down

### ISSUE THREAD

**Issue by MMachado05** [thredded/thredded#997]
Since the website doesn't have its own repo, I figured to make this issue here: the thredded.org website seems to be having issues with regards to the Heroku hosting platform. Here is what the website currently looks like:
![image](https://github.com/user-attachments/assets/3a6e78ae-7f31-4a92-a716-6c190bc60210)

**Comment by timdiggins** [comment]
Hi @MMachado05 thanks for your report - but we know thredded.org doesn't work (no one is paying for it 😁 ) and there are other PRs discussing this: #976 #962

**Comment by MMachado05** [comment]
I figured it was a hosting issue! Sorry about the duplicate issue, hopefully y'all find a home for the website soon. 🙂
